### ISSUE TITLE
TargetFramework property in Directory.Build.props file

### ISSUE THREAD

**Issue by martinfletcher** [Microsoft/msbuild#3574] opened 2018-08-02 10:13 UTC
### Steps to reproduce
Create a new solution
Create a Directory.Build.Props file with <TargetFramework>netstandard2.0</TargetFramework>
Create a Net Standard 2.0 class library
Edit the csproj file and remove the TargetFramework> property

Solution/
     src/
          Directory.Build.props
          NetStandardClassLibrary/
               NetStandardClassLibrary.csproj

src/Directory.Build.props:

<Project>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>

src/NetStandardClassLibrary/NetStandardClassLibrary.csproj

<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Some_Package_Reference" Version="1.0.0" />
  </ItemGroup>
</Project>

### Expected  behavior
Solution and class library function/build as normal in vs2017

### Actual behavior
The following popup is shown
![image](https://user-images.githubusercontent.com/5081397/43577824-e3b3fc42-9644-11e8-92c1-d17e32afbe64.png)

### Environment data
Visual Studio 2017 Professional

OS info:
Windows 10 Enterprise

**Comment by jeffkl** [comment] 2018-08-02 13:48
Duplicate of https://github.com/dotnet/project-system/issues/1358

**Closed by jeffkl** 2018-08-02 13:48 UTC

**Comment by jurby** [comment] 2019-02-18 20:55
Problem is in `TargetFramework`. When is property in external build props file - build not working in VS 2017. In dotnet cli this setup working.

Not working in VS:
```
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../build/NugetProject.build.props" />
  ....
```

Working in VS:
```
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../build/NugetProject.build.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
```
