### ISSUE TITLE
Microsoft.CSharp.Core.targets not found in OS X.

### ISSUE THREAD

**Issue by mfilippov** [Microsoft/msbuild#469] opened 2016-02-06 15:44 UTC
I try use xplat msbuild on Mac. I build it but I got error when I try start.
`msbuild
Microsoft (R) Build Engine version 14.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/6/16 6:38:22 PM.
Project "/Users/mfilippov/Projects/DemoApp/DemoApp.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x86".
Project "/Users/mfilippov/Projects/DemoApp/DemoApp.sln" (1) is building "/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj" (2) on node 1 (default targets).
/Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.CurrentVersion.targets(321,5): error MSB4019: The imported project "/Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj]
Done Building Project "/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj" (default targets) -- FAILED.
Done Building Project "/Users/mfilippov/Projects/DemoApp/DemoApp.sln" (default targets) -- FAILED.

Build FAILED.

"/Users/mfilippov/Projects/DemoApp/DemoApp.sln" (default target) (1) ->
"/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj" (default target) (2) ->
  /Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.CurrentVersion.targets(321,5): error MSB4019: The imported project "/Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.58
`
I found this target file in package: msbuild/packages/Microsoft.Net.Compilers.1.2.0-beta1-20160108-01/tools/Microsoft.CSharp.Core.targets
But not in OSX_Deployment folder.

**Comment by JunielKatarn** [comment] 2016-02-10 09:22
What exactly was the command you ran?

**Comment by mfilippov** [comment] 2016-02-10 09:48
I use:
```
mb:DemoApp mfilippov$ cat /usr/local/bin/msbuild 
/Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/corerun /Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/MSBuild.exe $1
mb:DemoApp mfilippov$ msbuild DemoApp.sln 
Microsoft (R) Build Engine version 14.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/10/16 12:47:07 PM.
Project "/Users/mfilippov/Projects/DemoApp/DemoApp.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x86".
Project "/Users/mfilippov/Projects/DemoApp/DemoApp.sln" (1) is building "/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj" (2) on node 1 (default targets).
/Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.CurrentVersion.targets(321,5): error MSB4019: The imported project "/Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj]
Done Building Project "/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj" (default targets) -- FAILED.
Done Building Project "/Users/mfilippov/Projects/DemoApp/DemoApp.sln" (default targets) -- FAILED.

Build FAILED.

"/Users/mfilippov/Projects/DemoApp/DemoApp.sln" (default target) (1) ->
"/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj" (default target) (2) ->
  /Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.CurrentVersion.targets(321,5): error MSB4019: The imported project "/Users/mfilippov/Projects/msbuild/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/Users/mfilippov/Projects/DemoApp/DemoApp/DemoApp.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.67
```

**Comment by mfilippov** [comment] 2016-02-10 09:50
I try build simple console app created for .NET Framework 4.5.1:
```
using System;

namespace DemoApp
{
	class MainClass
	{
		public static void Main (string[] args)
		{
			Console.WriteLine ("Hello World!");
		}
	}
}
```

**Comment by JunielKatarn** [comment] 2016-02-10 09:53
Looks like you are using the corerun build. I haven't been able to compile it before. I'm currently building the Mono version (``).

You might want to start testing with a more simple project file. @cdmihai suggested something like this:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="HelloWorld" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="HelloWorld">
      <Message Text="HelloWorld"></Message>
    </Target>
</Project>
```
Meaning, way before compiling actual source code, see if the MSBuild engine works.

Out of curiosity, did you build MSBuild in your machine, or download the artifacts somewhere?

**Comment by mfilippov** [comment] 2016-02-10 09:54
I try you sample:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="HelloWorld" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="HelloWorld">
      <Message Text="HelloWorld"></Message>
    </Target>
</Project>
```
It worked but if I want build csharp code I got error.

**Comment by mfilippov** [comment] 2016-02-10 09:55
I build MSBuild on my machine.
How I understand problem in missing target file: Microsoft.CSharp.Core.targets in destination directory.

**Comment by mfilippov** [comment] 2016-02-10 09:57
This is file from package: Microsoft.Net.Compilers

**Comment by JunielKatarn** [comment] 2016-02-10 11:00
Yeah, I took a look, and looks like the file is just missing from the build.
The `Microsoft.CSharp.Core.targets` file is expected at `<your MSBuild local copy>/bin/Debug-Netcore/OSX_Deployment`. That particular one is not there.

I suggest you rename this issue to something like "Microsoft.CSharp.Core.targets not found in OS X", which is more specific.

**Comment by JunielKatarn** [comment] 2016-02-10 11:02
... come to think of it, it makes total sense. MSBuild shouldn't be able to compile C# by itself.
There should be a way to install the .NET compilers into your local build.

**Comment by JunielKatarn** [comment] 2016-02-10 11:09
For what it's worth, foud the file at:
`<Your MSBuild local copy>/packages/Microsoft.Net.Compilers.1.2.0-beta1-20160108-01/tools/Microsoft.CSharp.Core.targets`

**Comment by mfilippov** [comment] 2016-02-10 11:16
@JunielKatarn I found csc.exe in out MSBuild folder I try run corerun csc.exe it worked.

**Comment by cdmihai** [comment] 2016-02-10 19:10
MSBuild's xplat build scripts are currently a bit out of date. Working on bringing them up.

**Comment by cdmihai** [comment] 2016-02-10 20:03
@mfilippov 

As a temporary workaround, try using the `OSX_Deployment_Test` directory. I was reading through the tangled build scripts and apparently those targets only get copied for the tests. Working on fixing it.

**Comment by JunielKatarn** [comment] 2016-02-11 10:03
> apparently those targets only get copied for the tests

@cdmihai I don't think that is the case.
File `Microsoft.CSharp.targets` can be found at several locations, including:
- `./bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.targets`
- `./bin/Debug-Netcore/OSX_Deployment_Test/Microsoft.CSharp.targets`
- `./bin/Debug-Netcore/Output/Microsoft.CSharp.targets`

All of them are identical.

Is there a way to have MSBuild search/include the targets files under `packages/Microsoft.Net.Compilers.<version>/tools`?

**Comment by cdmihai** [comment] 2016-02-11 18:55
@JunielKatarn 
The missing targets are `Microsoft.CSharp.Core.targets`

Ideally these targets get pulled down by nuget via nuget restore and the nuget resolve package assets msbuild task. We shouldn't need to have any extra logic to locate them.

As another workaround until I get my change in, add the following packages into runtime.project.json:

```
        "Microsoft.Net.Compilers.NetCore": "1.2.0-beta1-20160122-02",
        "Microsoft.Net.Compilers.Targets.NetCore": "0.1.4-dev",
        "Microsoft.Net.Compilers.Targets.NetCore": "0.1.4-dev",
```

They will bring down the core targets into the deployment dir.

**Comment by JunielKatarn** [comment] 2016-02-12 10:58
@cdmihai FYI.
The workaround succeeded in adding the `.Core.targets` to the deployment directory.
However, building a trivial C# project fails with the following message:
```
/Volumes/DATA/Build/msb/buildme/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.Core.targets(67,5): error MSB4018: The "Csc" task failed unexpectedly. [/Volumes/DATA/Build/msb/samples/cslib/TrivialLib.csproj]
/Volumes/DATA/Build/msb/buildme/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.Core.targets(67,5): error MSB4018: This is an unhandled exception from a task -- PLEASE OPEN A BUG AGAINST THE TASK OWNER. [/Volumes/DATA/Build/msb/samples/cslib/TrivialLib.csproj]
/Volumes/DATA/Build/msb/buildme/bin/Debug-Netcore/OSX_Deployment/Microsoft.CSharp.Core.targets(67,5): error MSB4018: System.MethodAccessException: Attempt by method 'Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ListHasNoDuplicateItems(Microsoft.Build.Framework.ITaskItem[], System.String, System.String, Microsoft.Build.Utilities.TaskLoggingHelper)' to access method 'System.Collections.Hashtable..ctor(System.Collections.IEqualityComparer)' failed. [/Volumes/DATA/Build/msb/samples/cslib/TrivialLib.csproj]
```

**Comment by cdmihai** [comment] 2016-02-17 19:37
@JunielKatarn 

I also ran into that issue, but haven't had the time to look into it. My assumption is that the compiler package is old and references an old version of System.Collections that had that constructor public.

One way to reproduce this on Windows is to try to build net core msbuild, copy the deployment output folder to some other location and then try to rebuild msbuild net core with itself.

I'll see if it this still happens when I finish net core self hosting. If it does, then we may have to submit an issue to the csc package owners to update to rc2

**Comment by cdmihai** [comment] 2016-03-04 17:01
This should be fixed in #501. Those targets should now get in both the deployment folders. They get copied there in DeployDependencies.targets from our runtime project.json

**Comment by radical** [comment] 2016-03-08 22:53
It is fixed for the mono/osx case that I use.

**Comment by cdmihai** [comment] 2016-03-09 04:17
Closing the issue; Even more, with #516, the deployment directories should be self contained and usable to do builds.

**Closed by cdmihai** 2016-03-09 04:17 UTC
