### ISSUE TITLE
Cross-targeting doesn't handle multiple build targets correctly

### ISSUE THREAD

**Issue by tmat** [Microsoft/msbuild#1724] opened 2017-02-17 20:35 UTC
Repro:

1) Create a .NET Core library with multiple target frameworks:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.0;net46</TargetFrameworks>
  </PropertyGroup>
</Project>
```

2) Run msbuild:

```
msbuild /p:Restore ClassLibrary.csproj
msbuild /p:Clean;Build ClassLibrary.csproj
```

Expected:
Both Clean and Build tasks are executed in both inner and outer build. 

Actual:
Build task is not executed in inner build. The library binaries are not built.

The problem seems to be in reuse of ```DispatchToInnerBuilds``` target in Microsoft.Common.CrossTargeting.targets:

```xml
  <Target Name="Clean" DependsOnTargets="_SetCleanInnerTarget;DispatchToInnerBuilds" />
  <Target Name="Build" DependsOnTargets="_SetBuildInnerTarget;DispatchToInnerBuilds" />
```

The log shows that DispatchToInnerBuilds is skipped when executing Build target:

```
Target "Clean: (TargetId:59)" in file "Microsoft.Common.CrossTargeting.targets" from project "ClassLibrary.csproj" (entry point):
Done building target "Clean" in project "ClassLibrary.csproj".: (TargetId:59)
Target "_CleanPackageFiles" skipped, due to false condition; ('$(GeneratePackageOnBuild)' == 'true') was evaluated as ('false' == 'true').
Target "_SetBuildInnerTarget: (TargetId:60)" in file "Microsoft.Common.CrossTargeting.targets" from project "ClassLibrary.csproj" (target "Build" depends on it):
Done building target "_SetBuildInnerTarget" in project "ClassLibrary.csproj".: (TargetId:60)

Target "DispatchToInnerBuilds" skipped. Previously built successfully.
```

**Comment by tmat** [comment] 2017-02-17 20:36
FYI: @srivatsn @nguerrera

**Comment by rainersigwald** [comment] 2017-02-17 20:40
Duplicate of https://github.com/Microsoft/msbuild/issues/1065, which didn't meet the bar for RTW but has been fixed for the future.

**Closed by rainersigwald** 2017-02-17 20:40 UTC
