### ISSUE TITLE
Intellisense only provides basic properties

### ISSUE THREAD

**Issue by bradphelan** [microsoft/msbuild#2563] opened 2017-09-28 14:02 UTC
![image](https://user-images.githubusercontent.com/17650/30970737-2e3c39a4-a466-11e7-8b57-e954508d9b2c.png)

However there are a many more

![image](https://user-images.githubusercontent.com/17650/30970783-5695c758-a466-11e7-8879-ef9a5827f85f.png)

Why don't they appear?

I've downloaded 

![image](https://user-images.githubusercontent.com/17650/30970815-6b7da28a-a466-11e7-98b5-e5d7239863c5.png)

**Comment by bradphelan** [comment] 2017-09-28 14:06
Turning off resharper now shows me something different

![image](https://user-images.githubusercontent.com/17650/30970973-f26d9aa2-a466-11e7-855e-5699e3bb1c91.png)

but the field I'm looking for

CopyToOutputDirectory 

is not there.

**Comment by rainersigwald** [comment] 2020-05-06 16:22
Duplicate of #1774

**Closed by rainersigwald** 2020-05-06 16:22 UTC
