### ISSUE TITLE
[Question] What are the minimal software requirements to build a .Net project with MSBuild

### ISSUE THREAD

**Issue by f0rt** [Microsoft/msbuild#2383] opened 2017-08-02 11:59 UTC
Hi team,

I have a .NET solution that I built on a build system with MSBuild 14, VS 2015 installed and  Windows 10.  I'm now trying to find the minimal setup for building that project. I have Windows Server 2016 OS. I prefer all the build tools to be standalone if possible. I'm currently able to build the project with MSBuild and VS2015/VS2017 installed but I'm unable to build without VS installed. Is it possible? Is there a standalone edition of the latest MSBuild?

Thank you in advance,
Nedko

**Comment by Veigres** [comment] 2017-08-02 15:30
I think that the Build Tools for Visual Studio 2017 have a standalone version of MSBuild for Windows. You can download it [here](https://www.visualstudio.com/downloads/) (at the bottom of the page, under "Other Tools and Frameworks")

**Comment by f0rt** [comment] 2017-08-04 05:00
Thanks. Is there a copy deploy-able distribution?

**Comment by f0rt** [comment] 2017-08-04 11:17
I was able to build successfully on a clean OS by just copying:
1. **MSBuild** - <ProgramFiles(x86)>\Microsoft Visual Studio\2017\Professional\MSBuild
2. **Reference Assemblies** - <ProgramFiles(x86)>\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5

**Comment by AndyGerlicher** [comment] 2017-08-08 22:35
Team Triage:
The current supported way to distribute MSBuild is via the Build Tools installer (which @Veigres linked), through Visual Studio, or through dotnet CLI. We don't have an xcopy-able deployment supported at this time.

Closing as a duplicate of #1602

**Closed by AndyGerlicher** 2017-08-08 22:35 UTC

**Comment by f0rt** [comment] 2017-08-14 13:19
Thanks.
