### ISSUE TITLE
Certain colors in MSBuild output are difficult to read

### ISSUE THREAD

**Issue by pavelbraginskiy** [Microsoft/msbuild#3596] opened 2018-08-09 14:17 UTC
MSBuild, invoked from the console, uses various colors in order to output. This is fine, marking errors in red really does help in locating them. However, a lot of the output is in dark gray, which on my terminal looks like:

![image](https://user-images.githubusercontent.com/29113974/43904439-7e1aecf6-9ba3-11e8-9f5b-8e22b8a84ccf.png)

I have some vision problems, but with some effort I can make out what it says. However, here's what the output looks like using the Solarized Dark color scheme, which is popular and comes as an option on most terminals:

![image](https://user-images.githubusercontent.com/29113974/43904660-1e80cd00-9ba4-11e8-8be0-2a36e411437c.png)

As you can see, the dark gray output is just flat-out not visible.

Both screenshots taken using Konsole on Linux.

**Comment by 4creators** [comment] 2018-08-09 21:57
Impaired color vision is present in roughly 30% of men population - problematic colors lie around green-red. Devs should ask for help accessibility team in MSFT to make more readable or customizable for different vision deficiencies output.

**Comment by rainersigwald** [comment] 2018-08-14 15:44
Duplicate of #2364

**Closed by rainersigwald** 2018-08-14 15:44 UTC
