### ISSUE TITLE
`msbuild /t:<anyTask> foo.sln` fails if solution file has comment inside projectSection

### ISSUE THREAD

**Issue by rrelyea** [microsoft/msbuild#4451] opened 2019-06-18 22:30 UTC
NuGet team broke our solution file, so msbuild was no longer able to successfully parse it.
It turned out that a comment in the wrong place of the solution file, worked fine in VS, but broke msbuild parsing of that solution.

Not a critical bug to fix...but nice to have eventually.

Our Issue: https://github.com/NuGet/Home/issues/8239
Our fix: https://github.com/NuGet/NuGet.Client/commit/686dd6b060639a0fb401eceb4c3a4029c1482023

### Steps to reproduce

Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "NuGetConsole.Host.PowerShell", "src\NuGet.Clients\NuGetConsole.Host.PowerShell\NuGetConsole.Host.PowerShell.csproj", "{5A79EEF3-51C0-4A14-8D37-50EF38AD835D}"
	# This comment is ok.
	ProjectSection(ProjectDependencies) = postProject
		# This comment will cause problems.
		{26DC17AC-A390-4515-A2C0-07A0950036C5} = {26DC17AC-A390-4515-A2C0-07A0950036C5}
	EndProjectSection
EndProject

### Expected  behavior
`msbuild /t:restore nuget.sln` works

### Actual behavior
Output:
error: Parent project GUID not found in "NuGetConsole.Host.PowerShell" project dependency section. C:\repos\nc-dotnetlist\NuGet.sln

### Environment data
reproduced this in msbuild 15.9 and msbuild 16.1
I think it also reproed with `dotnet msbuild`

**Comment by rainersigwald** [comment] 2019-06-18 22:31
Thanks for the report. I believe this was reported earlier, let me see if I can find the original.

**Comment by rainersigwald** [comment] 2019-06-18 22:32
Duplicate of #4328

**Closed by rainersigwald** 2019-06-18 22:32 UTC
