### ISSUE TITLE
Embedded newlines in .resx files are treated differently by .NET Core and full framework

### ISSUE THREAD

**Issue by rainersigwald** [Microsoft/msbuild#2362] opened 2017-07-28 20:01 UTC
The resources embedded in the output assembly differ between .NET Core and full framework msbuild when a `.resx` file contains a string with newlines in it.

On full framework, the newlines appear to be embedded as they are in the file (on my machine, that's CRLF), but when building using `dotnet build` the resources are embedded with plain LF.

(I noticed this while piloting SDK conversion in this repo, when the test [`HelpMessagesAreValid`](https://github.com/Microsoft/msbuild/blob/69cd7348fe5d095880807ea1ab614fabc6cde9d8/src/MSBuild.UnitTests/CommandLineSwitches_Tests.cs#L1336) started failing because it splits on `Environment.NewLine` which didn't appear in the .NET Core-embedded resources.)

**Comment by nguerrera** [comment] 2017-10-12 07:45
Duplicate of #2206

**Closed** 2018-01-19 18:49 UTC
Labels: .NET Core
