### ISSUE TITLE
Calling clean + build targets on solution skips all multi-targeting projects

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#1734] opened 2017-02-21 23:34 UTC
**Repro**
https://github.com/aspnet/Common/blob/8688579b29eb37f5b3a5b5dfdb83f0fad1063af5/Common.sln

dotnet msbuild "/t:Clean;Build" Common.sln

**Expected**
Builds all projects

```
  Microsoft.Extensions.Primitives -> C:\dev\Universe\Common\src\Microsoft.Extensions.Primitives\bin\Debug\netstandard1.0\Microsoft.Extensions.Primitives.dll
  Microsoft.Extensions.ObjectPool -> C:\dev\Universe\Common\src\Microsoft.Extensions.ObjectPool\bin\Debug\net451\Microsoft.Extensions.ObjectPool.dll
  Microsoft.Extensions.CommandLineUtils -> C:\dev\Universe\Common\src\Microsoft.Extensions.CommandLineUtils\bin\Debug\net451\Microsoft.Extensions.CommandLineUtils.dll
  Microsoft.Extensions.ObjectPool -> C:\dev\Universe\Common\src\Microsoft.Extensions.ObjectPool\bin\Debug\netstandard1.3\Microsoft.Extensions.ObjectPool.dll
  Microsoft.Extensions.CommandLineUtils -> C:\dev\Universe\Common\src\Microsoft.Extensions.CommandLineUtils\bin\Debug\netstandard1.3\Microsoft.Extensions.CommandLineUtils.dll
  Microsoft.Extensions.Internal.Test -> C:\dev\Universe\Common\test\Microsoft.Extensions.Internal.Test\bin\Debug\netcoreapp1.1\Microsoft.Extensions.Internal.Test.dll
  Microsoft.Extensions.ObjectPool.Test -> C:\dev\Universe\Common\test\Microsoft.Extensions.ObjectPool.Test\bin\Debug\netcoreapp1.1\Microsoft.Extensions.ObjectPool.Test.dll
  Microsoft.Extensions.CommandLineUtils.Tests -> C:\dev\Universe\Common\test\Microsoft.Extensions.CommandLineUtils.Tests\bin\Debug\netcoreapp1.1\Microsoft.Extensions.CommandLineUtils.Tests.dll
  Microsoft.Extensions.Internal.Test -> C:\dev\Universe\Common\test\Microsoft.Extensions.Internal.Test\bin\Debug\net452\Microsoft.Extensions.Internal.Test.dll
  Microsoft.Extensions.ObjectPool.Test -> C:\dev\Universe\Common\test\Microsoft.Extensions.ObjectPool.Test\bin\Debug\net452\Microsoft.Extensions.ObjectPool.Test.dll
  Microsoft.Extensions.Primitives.Tests -> C:\dev\Universe\Common\test\Microsoft.Extensions.Primitives.Tests\bin\Debug\netcoreapp1.1\Microsoft.Extensions.Primitives.Tests.dll
  Microsoft.Extensions.CommandLineUtils.Tests -> C:\dev\Universe\Common\test\Microsoft.Extensions.CommandLineUtils.Tests\bin\Debug\net452\Microsoft.Extensions.CommandLineUtils.Tests.dll
  Microsoft.Extensions.Primitives.Tests -> C:\dev\Universe\Common\test\Microsoft.Extensions.Primitives.Tests\bin\Debug\net452\Microsoft.Extensions.Primitives.Tests.dll
```

**Actual**
Only builds single-TFM projects

```
  Microsoft.Extensions.Primitives -> C:\dev\Universe\Common\src\Microsoft.Extensions.Primitives\bin\Debug\netstandard1.0\Microsoft.Extensions.Primitives.dll
```

**Details**
MSBuild: 15.1.548.43366
dotnet.exe 1.0.0-rc4-004842

**Comment by rainersigwald** [comment] 2017-02-22 00:05
Same root cause as https://github.com/Microsoft/msbuild/issues/1065, which is fixed in post-RTW builds but didn't meet the bar for RTW.

**Closed by rainersigwald** 2017-02-22 00:05 UTC
