### ISSUE TITLE
Static string expressions on metadata are too clumsy

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/msbuild#1465] opened 2016-12-09 20:45 UTC
To call static (string) functions on properties, I simply write like `$(Prop.Function(...))`.
To call static (string) functions on bare metadata, I apparently have to use a trick with the static string Copy function. 

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <ItemGroup>
    <Files Include="foo">
      <SourcePath>blah.fr.dll</SourcePath>
    </Files>
    <Files Include="bar">
      <SourcePath>some.de.dll</SourcePath>
    </Files>
  </ItemGroup>

  <PropertyGroup>
    <Prop>baz.fr.dll</Prop>
  </PropertyGroup>

  <Target Name="t">

    <Warning Text="$(Prop) contains fr" Condition="'$(Prop.Contains(`.fr.`))' == true"/>

    <Warning Text="%(Files.SourcePath) contains fr" Condition="$([System.String]::Copy('%(Files.SourcePath)').Contains('.fr.'))"/>
  </Target>
 
</Project>
```

correctly emits
```
  C:\play\foo.proj(18,5): warning : baz.fr.dll contains fr
  C:\play\foo.proj(20,5): warning : blah.fr.dll contains fr
```

Where the item type is provided, so there's already one period, it is possible for evaluation to unambiguously allow a function (which would add a second period). 

For example, `%(Files.SourcePath.Contains('.fr.'))` is not ambiguous and much better than `$([System.String]::Copy('%(Files.SourcePath)').Contains('.fr.'))`

**Comment by cdmihai** [comment] 2016-12-13 16:44
Closing as duplicate of #1155

**Closed by cdmihai** 2016-12-13 16:44 UTC
