### ISSUE TITLE
VS 2015 PCL build breaks when upgrading from 2017 RC3 to D15Rel/26129 (MSB5016)

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/msbuild#1654] opened 2017-02-01 21:12 UTC
1. Create a new PCL project in VS 2015 (or skip ahead to step 5 and use the attached project)
2. Add a second PCL project to the solution which references the first
3. Build it in 2015 - works fine
4. Reopen the project in 2017, and clean the project
5. Try to build

Project:
[PCLForNet46AndCore.zip](https://github.com/Microsoft/msbuild/files/746165/PCLForNet46AndCore.zip)

Result:
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1556,5): error MSB5016: The name ".NETStandard,Version" contains an invalid character ".".  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

This works with the RC3 build.

Which is raised at this stack:
```
>	Microsoft.Build.dll!Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(string errorSubCategoryResourceName, Microsoft.Build.Shared.IElementLocation elementLocation, string resourceName, object[] args)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject(bool condition, string errorSubCategoryResourceName, Microsoft.Build.Shared.IElementLocation elementLocation, string resourceName, object arg0, object arg1)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Shared.XmlUtilities.VerifyThrowProjectValidElementName(string name, Microsoft.Build.Shared.IElementLocation location)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Execution.ProjectPropertyInstance.Create(string name, string escapedValue, bool mayBeReserved, Microsoft.Build.Construction.ElementLocation location, bool isImmutable)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Execution.ProjectPropertyInstance.Create(string name, string escapedValue, Microsoft.Build.Construction.ElementLocation location)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskHost.BuildProjectFilesInParallelAsync(string[] projectFileNames, string[] targetNames, System.Collections.IDictionary[] globalProperties, System.Collections.Generic.IList<string>[] undefineProperties, string[] toolsVersion, bool returnTargetOutputs)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.Build.Framework.BuildEngineResult>.Start<Microsoft.Build.BackEnd.TaskHost.<BuildProjectFilesInParallelAsync>d__53>(ref Microsoft.Build.BackEnd.TaskHost.<BuildProjectFilesInParallelAsync>d__53 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskHost.BuildProjectFilesInParallelAsync(string[] projectFileNames, string[] targetNames, System.Collections.IDictionary[] globalProperties, System.Collections.Generic.IList<string>[] undefineProperties, string[] toolsVersion, bool returnTargetOutputs)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskHost.InternalBuildProjects(string[] projectFileNames, string[] targetNames, System.Collections.IDictionary[] globalProperties, System.Collections.Generic.IList<string>[] undefineProperties, string[] toolsVersion, bool returnTargetOutputs)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Microsoft.Build.Framework.BuildEngineResult>.Start<Microsoft.Build.BackEnd.TaskHost.<InternalBuildProjects>d__49>(ref Microsoft.Build.BackEnd.TaskHost.<InternalBuildProjects>d__49 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskHost.InternalBuildProjects(string[] projectFileNames, string[] targetNames, System.Collections.IDictionary[] globalProperties, System.Collections.Generic.IList<string>[] undefineProperties, string[] toolsVersion, bool returnTargetOutputs)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.MSBuild.ExecuteTargets(Microsoft.Build.Framework.ITaskItem[] projects, System.Collections.Hashtable propertiesTable, string[] undefineProperties, System.Collections.ArrayList targetLists, bool stopOnFirstFailure, bool rebaseOutputs, Microsoft.Build.Framework.IBuildEngine3 buildEngine, Microsoft.Build.BackEnd.TaskLoggingHelper log, System.Collections.ArrayList targetOutputs, bool useResultsCache, bool unloadProjectsOnCompletion, string toolsVersion)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<Microsoft.Build.BackEnd.MSBuild.<ExecuteTargets>d__77>(ref Microsoft.Build.BackEnd.MSBuild.<ExecuteTargets>d__77 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.MSBuild.ExecuteTargets(Microsoft.Build.Framework.ITaskItem[] projects, System.Collections.Hashtable propertiesTable, string[] undefineProperties, System.Collections.ArrayList targetLists, bool stopOnFirstFailure, bool rebaseOutputs, Microsoft.Build.Framework.IBuildEngine3 buildEngine, Microsoft.Build.BackEnd.TaskLoggingHelper log, System.Collections.ArrayList targetOutputs, bool useResultsCache, bool unloadProjectsOnCompletion, string toolsVersion)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.MSBuild.BuildProjectsInParallel(System.Collections.Hashtable propertiesTable, string[] undefinePropertiesArray, System.Collections.ArrayList targetLists, bool success, bool[] skipProjects)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<Microsoft.Build.BackEnd.MSBuild.<BuildProjectsInParallel>d__74>(ref Microsoft.Build.BackEnd.MSBuild.<BuildProjectsInParallel>d__74 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.MSBuild.BuildProjectsInParallel(System.Collections.Hashtable propertiesTable, string[] undefinePropertiesArray, System.Collections.ArrayList targetLists, bool success, bool[] skipProjects)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.MSBuild.ExecuteInternal()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<Microsoft.Build.BackEnd.MSBuild.<ExecuteInternal>d__73>(ref Microsoft.Build.BackEnd.MSBuild.<ExecuteInternal>d__73 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.MSBuild.ExecuteInternal()	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26>(ref Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.InitializeAndExecuteTask(Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.ItemBucket bucket, System.Collections.Generic.IDictionary<string, string> taskIdentityParameters, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.Build.BackEnd.TaskBuilder.<InitializeAndExecuteTask>d__24>(ref Microsoft.Build.BackEnd.TaskBuilder.<InitializeAndExecuteTask>d__24 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.InitializeAndExecuteTask(Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.ItemBucket bucket, System.Collections.Generic.IDictionary<string, string> taskIdentityParameters, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask, System.Collections.Generic.Dictionary<string, string> lookupHash)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.Build.BackEnd.TaskBuilder.<ExecuteBucket>d__19>(ref Microsoft.Build.BackEnd.TaskBuilder.<ExecuteBucket>d__19 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask, System.Collections.Generic.Dictionary<string, string> lookupHash)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup lookup)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18>(ref Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__18 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup lookup)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(Microsoft.Build.BackEnd.Logging.TargetLoggingContext loggingContext, Microsoft.Build.BackEnd.BuildRequestEntry requestEntry, Microsoft.Build.BackEnd.ITargetBuilderCallback targetBuilderCallback, Microsoft.Build.Execution.ProjectTargetInstanceChild taskInstance, Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup inferLookup, Microsoft.Build.BackEnd.Lookup executeLookup, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13>(ref Microsoft.Build.BackEnd.TaskBuilder.<ExecuteTask>d__13 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(Microsoft.Build.BackEnd.Logging.TargetLoggingContext loggingContext, Microsoft.Build.BackEnd.BuildRequestEntry requestEntry, Microsoft.Build.BackEnd.ITargetBuilderCallback targetBuilderCallback, Microsoft.Build.Execution.ProjectTargetInstanceChild taskInstance, Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup inferLookup, Microsoft.Build.BackEnd.Lookup executeLookup, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder, Microsoft.Build.BackEnd.Logging.TargetLoggingContext targetLoggingContext, Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup lookupForInference, Microsoft.Build.BackEnd.Lookup lookupForExecution)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__48>(ref Microsoft.Build.BackEnd.TargetEntry.<ProcessBucket>d__48 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder, Microsoft.Build.BackEnd.Logging.TargetLoggingContext targetLoggingContext, Microsoft.Build.BackEnd.TaskExecutionMode mode, Microsoft.Build.BackEnd.Lookup lookupForInference, Microsoft.Build.BackEnd.Lookup lookupForExecution)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder, Microsoft.Build.BackEnd.BuildRequestEntry requestEntry, Microsoft.Build.BackEnd.Logging.ProjectLoggingContext projectLoggingContext, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__42>(ref Microsoft.Build.BackEnd.TargetEntry.<ExecuteTarget>d__42 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder, Microsoft.Build.BackEnd.BuildRequestEntry requestEntry, Microsoft.Build.BackEnd.Logging.ProjectLoggingContext projectLoggingContext, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetBuilder.ProcessTargetStack(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__22>(ref Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__22 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetBuilder.ProcessTargetStack(Microsoft.Build.BackEnd.ITaskBuilder taskBuilder)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetBuilder.BuildTargets(Microsoft.Build.BackEnd.Logging.ProjectLoggingContext loggingContext, Microsoft.Build.BackEnd.BuildRequestEntry entry, Microsoft.Build.BackEnd.IRequestBuilderCallback callback, string[] targetNames, Microsoft.Build.BackEnd.Lookup baseLookup, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__11>(ref Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__11 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.TargetBuilder.BuildTargets(Microsoft.Build.BackEnd.Logging.ProjectLoggingContext loggingContext, Microsoft.Build.BackEnd.BuildRequestEntry entry, Microsoft.Build.BackEnd.IRequestBuilderCallback callback, string[] targetNames, Microsoft.Build.BackEnd.Lookup baseLookup, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.RequestBuilder.BuildProject()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57>(ref Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.RequestBuilder.BuildProject()	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49>(ref Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.RequestBuilder.BuildAndReport()	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(bool setThreadParameters)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48>(ref Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48 stateMachine)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.RequestBuilder.RequestThreadProc(bool setThreadParameters)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.RequestBuilder.StartBuilderThread.AnonymousMethod__44_2()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(object obj)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart(object obj)	Unknown
```

From the verbose build logs, that string comes from:
```
1>NuGetTargetMoniker = .NETPlatform,Version=v5.0;.NETStandard,Version=v1.0;.NETStandard,Version=v1.1;.NETStandard,Version=v1.2;.NETStandard,Version=v1.3;.NETStandard,Version=v1.4;.NETStandard,Version=v1.5;.NETStandard,Version=v1.6
...
Set Property: ReferringTargetFrameworkForProjectReferences=.NETPlatform,Version=v5.0;.NETStandard,Version=v1.0;.NETStandard,Version=v1.1;.NETStandard,Version=v1.2;.NETStandard,Version=v1.3;.NETStandard,Version=v1.4;.NETStandard,Version=v1.5;.NETStandard,Version=v1.6
1>Using "MSBuild" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
1>Task "MSBuild" (TaskId:9)
1>  Task Parameter:Projects=..\PCLForNet46AndCore.csproj (TaskId:9)
1>  Task Parameter:Targets=GetTargetFrameworkProperties (TaskId:9)
1>  Task Parameter:BuildInParallel=True (TaskId:9)
1>  Task Parameter:
1>      Properties=
1>          Configuration=Debug
1>          Platform=AnyCPU
1>          ReferringTargetFramework=.NETPlatform,Version=v5.0
1>          .NETStandard,Version=v1.0
1>          .NETStandard,Version=v1.1
1>          .NETStandard,Version=v1.2
1>          .NETStandard,Version=v1.3
1>          .NETStandard,Version=v1.4
1>          .NETStandard,Version=v1.5
1>          .NETStandard,Version=v1.6 (TaskId:9)
```

**Comment by rainersigwald** [comment] 2017-02-01 21:15
Should be fixed by https://github.com/Microsoft/msbuild/pull/1644. Dupe of internal bug [377419](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=377419&_a=edit), but let's keep this one open for tracking.

Thanks for the report @gregg-miskelly.

**Comment by rainersigwald** [comment] 2017-02-03 00:48
Fix now inserted to VS.

**Closed by rainersigwald** 2017-02-03 00:48 UTC
Labels: .NET Core
