### ISSUE TITLE
msbuild not embedding resources when they have a ".cs" in the filename

### ISSUE THREAD

**Issue by FreeApophis** [microsoft/msbuild#4910] opened 2019-11-12 10:01 UTC
### Steps to reproduce

It has to do with the name of the resource, when I remove the .cs or even just rename it to .cx the Resource shows up. I made a minimal Project which exhibits this behaviour.

There is no error, it just silently refuses to embed the resource.

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="some.cs.template" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="some.cs.template" />
  </ItemGroup>

</Project>
```

some.cs.template is some none-empty text...

Program.cs to reproduce
```
using System;
using System.Reflection;

namespace ListResources
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Resources");
            var assembly = Assembly.GetExecutingAssembly();
            foreach (var resource in assembly.GetManifestResourceNames())
            {
                Console.WriteLine($"* {resource}");
            }
        }
    }
}
```

Command used: "dotnet build"

## Expected  behavior

The 'some.cs.template' Resource should be embedded.

### Actual behavior

The 'some.cs.template' is not embedded as resource.

### Environment data

If you rename some.cs.template to some.cx.template - it works.
Even more strange, renaming it to some.cs does also work correctly.

The "None Remove" entry seems to be generated by Visual Studio, but seems not necessary - same behaviour with or without that entry.

**Comment by rainersigwald** [comment] 2019-11-12 15:41
Duplicate of #3064

Thanks for the report! @BenVillalobos fyi, this might be a better repro than the one you're looking at.

**Closed by rainersigwald** 2019-11-12 15:41 UTC

**Comment by FreeApophis** [comment] 2019-11-13 19:27
Thanks
