### ISSUE TITLE
Build single project with multiple CPUs?

### ISSUE THREAD

**Issue by nurbles** [Microsoft/msbuild#3146] opened 2018-03-28 14:51 UTC
This is a suggestion (OK, wish list item) for the MSBuild process...

I know MSBuild can use multiple CPUs at a one CPU per project level when building and that is great.

I wish that MSBuild could do the same with individual C files, too.  The last project built in my solution has over 100 source files and takes about 10 minutes to build.  The thing is, 23 of the 24 cores are idle during that time and I *REALLY* wish the build could be sped up by using more of them.

(And yes, I said "C" files.  Our projects are all Native C, 64 bit Windows code -- no MFC, .NET or other frameworks involved.)

**Comment by rainersigwald** [comment] 2018-03-28 16:01
Duplicate of #74.

For your specific case, it sounds like enabling the VC++ compiler's `/MT` mode for your "last project" might be a clean win. It's dangerous to do that for all projects, because MSBuild will build NUMPROCS projects at once, and each will launch NUMPROCS compiler processes, leading to NUMPROCS² processes contending and slowing down overall. But if you have one bottleneck expensive project that depends on most or all of the other projects, you can enable CL parallelism within it.

**Closed by rainersigwald** 2018-03-28 16:01 UTC

**Comment by nurbles** [comment] 2018-03-28 16:13
Thanks!  I did not find the /MT option, but I found a /MP option that did what I wanted.  The build time is now one minute 46 seconds!

**Comment by rainersigwald** [comment] 2018-03-28 16:15
Sorry for the error! I corrected it in my post above for posterity. Glad it's working out for you.
