### ISSUE TITLE
MSBuild File globbing is slow on large directory layouts (e.g. node_modules)

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#2238] opened 2017-06-21 23:49 UTC
Issue ported from:
- developer community (**workaround available**) https://developercommunity.visualstudio.com/content/problem/50110/visual-studio-is-extremely-slow-when-node-modules.html
- internal https://devdiv.visualstudio.com/DevDiv/MSBuild/_workitems?id=447520

**Comment by cdmihai** [comment] 2017-06-21 23:55
From internal investigation:

> When there's a large number of files, the Build FileMatcher.GetFilesRecursive allocates a huge amount of strings.
> 
> Name                                                                                                                                                             Inc %              Inc
>  Type System.String                                                                                                                                               55.8    1,446,726,272
> + microsoft.build.ni![COLD] Microsoft.Build.Shared.FileUtilities.PathsEqual(System.String, System.String)                                                         27.3      708,307,520
> |+ Microsoft.Build!Microsoft.Build.Shared.FileMatcher+<>c__DisplayClass29_0.<GetFilesRecursive>b__0(class System.String)                                          27.3      708,307,520
> | + microsoft.build.ni![COLD] Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(System.Collections.Generic.IList`1, RecursionState, System.String, Boolean,    27.3      708,307,520
> |  + microsoft.build.ni!FileMatcher.GetFilesRecursive                                                                                                             27.3      707,986,112
> |  |+ microsoft.build.ni!FileMatcher.GetFiles                                                                                                                     27.3      707,986,112
> |  | + microsoft.build.ni!EngineFileUtilities.GetFileList                                                                                                         27.3      707,986,112
> |  |  + microsoft.build.ni!EngineFileUtilities.GetFileListEscaped                                                                                                 27.3      707,986,112
> |  |   + microsoft.build.ni!Microsoft.Build.Evaluation.LazyItemEvaluator`4+LazyItemOperation[System.__Canon,System.__Canon,System.__Canon,System.__Canon].Apply   27.3      707,986,112
> |  |    + microsoft.build.ni!Microsoft.Build.Evaluation.LazyItemEvaluator`4+MemoizedOperation[System.__Canon,System.__Canon,System.__Canon,System.__Canon].Appl   27.3      707,986,112
> |  |     + microsoft.build.ni!Microsoft.Build.Evaluation.LazyItemEvaluator`4+LazyItemList[System.__Canon,System.__Canon,System.__Canon,System.__Canon].ComputeI   27.3      707,986,112
> |  |      + microsoft.build.ni!Microsoft.Build.Evaluation.LazyItemEvaluator`4+LazyItemList[System.__Canon,System.__Canon,System.__Canon,System.__Canon].GetItem   27.3      707,986,112
> |  |       + microsoft.build.ni!Microsoft.Build.Evaluation.LazyItemEvaluator`4+<>c[System.__Canon,System.__Canon,System.__Canon,System.__Canon].<GetAllItems>b_   27.3      707,986,112
> |  |        + microsoft.build.ni!System.Linq.Buffer`1[Microsoft.Build.Evaluation.LazyItemEvaluator`4+ItemData[System.__Canon,System.__Canon,System.__Canon,Syst   27.3      707,986,112
> |  |         + microsoft.build.ni!System.Linq.OrderedEnumerable`1+<GetEnumerator>d__1[Microsoft.Build.Evaluation.LazyItemEvaluator`4+ItemData[System.__Canon,Sy   27.3      707,986,112
> |  |          + microsoft.build.ni!System.Collections.Generic.List`1[Microsoft.Build.Evaluation.LazyItemEvaluator`4+ItemData[System.__Canon,System.__Canon,Syst   27.3      707,986,112
> |  |           + microsoft.build.ni!System.Linq.Enumerable.ToList[Microsoft.Build.Evaluation.LazyItemEvaluator`4+ItemData[System.__Canon,System.__Canon,System.   27.3      707,986,112
> |  |            + microsoft.build.ni!Microsoft.Build.Evaluation.LazyItemEvaluator`4[System.__Canon,System.__Canon,System.__Canon,System.__Canon].GetAllItems()    27.3      707,986,112
> |  |             + microsoft.build.ni!Microsoft.Build.Evaluation.Evaluator`4[System.__Canon,System.__Canon,System.__Canon,System.__Canon].Evaluate()              27.3      707,986,112
> |  |              + microsoft.build.ni!Microsoft.Build.Evaluation.Evaluator`4[System.__Canon,System.__Canon,System.__Canon,System.__Canon].Evaluate(Microsoft.B   27.3      707,986,112
> |  |               + microsoft.build.ni!Project.Reevaluate                                                                                                        27.3      707,986,112
> |  |                + microsoft.build.ni!Project.ReevaluateIfNecessary                                                                                            27.3      707,986,112
> |  |                 + microsoft.build.ni!Project.Initialize                                                                                                      27.3      707,986,112

> Relevant code is here:
> https://github.com/Microsoft/msbuild/blob/master/src/Shared/FileMatcher.cs#L765
> 
>                                 excludeNextSteps[i].Subdirs.Any(excludedDir => FileUtilities.PathsEqual(excludedDir, subdir)))
> 
> This Any() creates an allocation for the delegate (every iteration of the loop), and it runs the PathsEqual function per every exclude item per every sub directory - this can be a lot.
> The function to compare two paths allocates at least 4 strings and two char arrays (from ToSlash() and TrimTrailingSlashes() )
> https://github.com/Microsoft/msbuild/blob/master/src/Shared/FileUtilities.cs#L1042-L1056
> 
> This could be mitigated by running the comparison on less files (ideal). Alternatively this can be written using a custom comparison function which ignores trailing slashes and considers forward/backward slashes to be equivalent. Then the comparisons can be done without allocation

**Comment by cdmihai** [comment] 2017-06-21 23:57
The orthogonal optimization to back out of certain excluded directories is tracked here: #2000

**Comment by jasselin** [comment] 2017-07-08 02:08
Might be related: https://developercommunity.visualstudio.com/content/problem/73964/visual-studio-msbuild-scans-every-file-in-an-aspne.html

**Comment by rainersigwald** [comment] 2017-07-10 15:02
@jasselin It is related, though I suspect #2000 would have a larger impact in that scenario. Since source files in ASP.NET Core projects are included by glob, the rename operation is essentially:

1. Rename the file (on disk), telling MSBuild nothing about it
1. Ask MSBuild to reevaluate the project, discovering all files referred to by the globs

The latter step hits these performance limitations.

**Comment by jasselin** [comment] 2017-07-10 23:30
@rainersigwald Is there any workaround like opting out of globbing and reverting to the old way of including files in a project? I tried setting EnableDefaultItems to True and including every file manually but it doesn't seem to help.

**Comment by dsplaisted** [comment] 2017-07-17 22:58
I'm seeing what looks like a similar issue in a slightly different codepath (ComparePathsNoThrow -> NormalizePathForComparisonNoThrow):

```
Name | Inc % | Inc
-- | -- | --
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|+ microsoft.build!ItemFragment.MatchCount | 40.7 | 18,266
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|+ microsoft.build!Microsoft.Build.Internal.EngineFileUtilities+<>c__DisplayClass6_0.<GetFileSpecMatchTester>b__0(class System.String) | 40.2 | 18,042
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|+ microsoft.build!FileUtilities.ComparePathsNoThrow | 40.1 | 18,021
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|+ microsoft.build!FileUtilities.NormalizePathForComparisonNoThrow | 38.8 | 17,441
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ microsoft.build!FileUtilities.GetFullPathNoThrow | 24.6 | 11,029
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ OTHER <<mscorlib.ni!Path.Combine>> | 6.0 | 2,690
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ OTHER <<clr!COMString::Replace>> | 2.5 | 1,126
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ microsoft.build!FileUtilities.PathIsInvalid | 1.7 | 762
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ microsoft.build!FileUtilities.get_InvalidFileNameChars | 1.3 | 573
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ OTHER <<?!?>> | 0.4 | 193
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ OTHER <<clr!COMString::IndexOfCharArray>> | 0.3 | 147
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ microsoft.build!FileUtilities.NormalizePath | 0.0 | 8
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|\|+ OTHER <<clr!JIT_NewArr1>> | 0.0 | 3
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|+ OTHER <<?!?>> | 0.1 | 43
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|+ OTHER <<mscorlib.ni!Path.Combine>> | 0.0 | 12
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|+ microsoft.build!FileUtilities.GetFullPathNoThrow | 0.0 | 10
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|+ microsoft.build!FileUtilities.PathIsInvalid | 0.0 | 8
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|+ OTHER <<clr!COMString::Replace>> | 0.0 | 7
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|\|+ OTHER <<clr!ThePreStub>> | 0.0 | 1
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|\|+ microsoft.build!FileUtilities.NormalizePathForComparisonNoThrow | 0.0 | 4
\|\|\| \|\|\|\|\| \|\| \|\|\| \|\|\|\|+ microsoft.build!FileUtilities.ComparePathsNoThrow | 0.0 | 3


```

**Comment by rainersigwald** [comment] 2017-07-17 23:10
@jasselin Sorry, missed this:

>Is there any workaround like opting out of globbing and reverting to the old way of including files in a project? 

Yes, you can always avoid the implicit globbing and explicitly specify the files of your choice, either individually or via your own more-specific glob. It looks like you'll have to do it [for each item type](https://github.com/dotnet/sdk/blob/a4bceb67b160c72318a581d87d52796e4fa31794/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.targets#L20-L22), unfortunately. I would have also expected that setting `EnableDefaultItems` to false would do the trick.

**Comment by dsplaisted** [comment] 2017-07-17 23:12
@rainersigwald Setting `EnableDefaultItems` to false will disable the implicit items for all of the item types.  See for example https://github.com/dotnet/sdk/blob/a4bceb67b160c72318a581d87d52796e4fa31794/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.props#L25-L28

**Comment by rainersigwald** [comment] 2017-07-17 23:14
You're right! Corrected my comment.

**Comment by jasselin** [comment] 2017-07-17 23:36
@rainersigwald @dsplaisted Still having the same issue with EnableDefaultItems set to false. It seems devenv.exe is still scanning every subdirectory. Is it MSBuild or Visual Studio related?

**Comment by davkean** [comment] 2017-07-18 00:50
@jasselin How are you setting `EnableDefaultItems`?

**Comment by davkean** [comment] 2017-07-18 00:51
@rainersigwald @cdmihai We should sync on path manipulation - I'm in the process of rewriting CPS's to avoid much the same issues.

**Comment by jasselin** [comment] 2017-07-18 00:54
@davkean I do.

**Comment by davkean** [comment] 2017-07-18 00:56
@jasselin Sorry my question is "_how_ do you set it?"

**Comment by jasselin** [comment] 2017-07-18 00:58
@davkean Sorry, misread.

In the csproj file.

```
  <PropertyGroup>
    <AssemblyName>App</AssemblyName>
    <PackageId>App</PackageId>
    <EnableDefaultItems>False</EnableDefaultItems>
  </PropertyGroup>
```

**Comment by jasselin** [comment] 2017-07-18 01:03
If it could help diagnose, I found out the whole thing originates from this:;

`  87,1%   MoveNext  •  8 268 ms  •  Microsoft.VisualStudio.ProjectSystem.Items.SourceItemsService+<SetUnvaluatedIncludesCoreWithGlobbingHelperAsync>d__117.MoveNext()
    84,4%   ReevaluateIfNecessary  •  8 011 ms  •  Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary()
      84,4%   ReevaluateIfNecessary  •  8 011 ms  •  Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService, ProjectLoadSettings)
        84,4%   Reevaluate  •  8 011 ms  •  Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService, ProjectLoadSettings)
          84,4%   Evaluate  •  8 011 ms  •  Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData, ProjectRootElement, ProjectLoadSettings, Int32, PropertyDictionary, ILoggingService, IItemFactory, IToolsetProvider, ProjectRootElementCache, BuildEventContext, ProjectInstance)
            84,3%   Evaluate  •  8 003 ms  •  Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
              83,3%   GetAllItems  •  7 910 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4.GetAllItems()
                83,3%   ToList  •  7 910 ms  •  System.Linq.Enumerable.ToList(IEnumerable)
                  83,3%   Microsoft.Build.ni.dll  •  7 910 ms
                    83,3%   MoveNext  •  7 909 ms  •  System.Linq.OrderedEnumerable`1+<GetEnumerator>d__1.MoveNext()
                      83,3%   Buffer`1..ctor  •  7 906 ms  •  System.Linq.Buffer`1..ctor(IEnumerable)
                        83,2%   <GetAllItems>b__22_0  •  7 901 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+<>c.<GetAllItems>b__22_0(LazyItemList)
                          83,2%   GetItems  •  7 901 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+LazyItemList.GetItems(ImmutableHashSet)
                            83,2%   ComputeItems  •  7 901 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+LazyItemList.ComputeItems(LazyItemList, ImmutableHashSet)
                              83,2%   Apply  •  7 900 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+MemoizedOperation.Apply(Builder, ImmutableHashSet)
                                83,1%   Apply  •  7 888 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+LazyItemOperation.Apply(Builder, ImmutableHashSet)
                                  77,1%   GetFileListEscaped  •  7 316 ms  •  Microsoft.Build.Internal.EngineFileUtilities.GetFileListEscaped(String, String, IEnumerable)
                                    77,1%   GetFileList  •  7 316 ms  •  Microsoft.Build.Internal.EngineFileUtilities.GetFileList(String, String, Boolean, IEnumerable)
                                      77,0%   GetFiles  •  7 308 ms  •  Microsoft.Build.Shared.FileMatcher.GetFiles(String, String, IEnumerable, GetFileSystemEntries, DirectoryExists)
                                        76,9%   GetFilesRecursive  •  7 296 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList, RecursionState, String, Boolean, GetFileSystemEntries, IList, Dictionary)
                                          76,5%   GetFilesRecursive  •  7 261 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList, RecursionState, String, Boolean, GetFileSystemEntries, IList, Dictionary)
                                            54,3%   GetFilesRecursive  •  5 156 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList, RecursionState, String, Boolean, GetFileSystemEntries, IList, Dictionary)
                                              29,9%   GetFilesRecursiveStep  •  2 842 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursiveStep(RecursionState, String, Boolean, GetFileSystemEntries)
                                                27,4%   GetAccessibleFileSystemEntries  •  2 603 ms  •  Microsoft.Build.Shared.FileMatcher.GetAccessibleFileSystemEntries(FileSystemEntity, String, String, String, Boolean)
                                                  16,5%   GetAccessibleDirectories  •  1 565 ms  •  Microsoft.Build.Shared.FileMatcher.GetAccessibleDirectories(String, String)
                                                    16,4%   GetDirectories  •  1 560 ms  •  System.IO.Directory.GetDirectories(String)
                                                      9,60%   List`1..ctor  •  911 ms  •  System.Collections.Generic.List`1..ctor(IEnumerable)
                                                      ► 9,52%   MoveNext  •  904 ms  •  System.IO.FileSystemEnumerableIterator`1.MoveNext()
                                                        0,02%   IsResultIncluded  •  2,3 ms  •  System.IO.StringResultHandler.IsResultIncluded(SearchResult)
                                                      ► 0,02%   Dispose  •  2,1 ms  •  System.IO.FileSystemEnumerableIterator`1.Dispose(Boolean)
                                                        0,01%   Dispose  •  0,9 ms  •  System.Runtime.InteropServices.SafeHandle.Dispose(Boolean)
                                                        0,01%   mscorlib.ni.dll  •  0,8 ms
                                                        0,00%   [Unknown]  •  0,4 ms
                                                        0,00%   [CPU Ready]  •  0,003 ms
                                                      ► 0,00%   clr.dll  •  0,0006 ms
                                                    ► 6,22%   FileSystemEnumerableIterator`1..ctor  •  590 ms  •  System.IO.FileSystemEnumerableIterator`1..ctor(String, String, String, SearchOption, SearchResultHandler, Boolean)
                                                      0,47%   [Unknown]  •  45 ms
                                                    ► 0,10%   clr.dll  •  9,2 ms
                                                      0,01%   mscorlib.ni.dll  •  1,4 ms
                                                      0,01%   GetDemandDir  •  0,8 ms  •  System.IO.Directory.GetDemandDir(String, Boolean)
                                                      0,00%   [CPU Ready]  •  0,001 ms
                                                    0,00%   [Unknown]  •  0,1 ms
                                                    0,00%   [CPU Ready]  •  0,0005 ms
                                                ► 10,9%   GetAccessibleFiles  •  1 030 ms  •  Microsoft.Build.Shared.FileMatcher.GetAccessibleFiles(String, String, String, Boolean)
                                                  0,01%   GetFiles  •  1,0 ms  •  System.IO.Directory.GetFiles(String, String)
                                                  0,01%   GetDirectories  •  0,8 ms  •  System.IO.Directory.GetDirectories(String)
                                                  0,01%   StartsWith  •  0,6 ms  •  System.String.StartsWith(String, StringComparison)
                                                  0,01%   RemoveInitialDotSlash  •  0,5 ms  •  Microsoft.Build.Shared.FileMatcher.RemoveInitialDotSlash(String[])
                                                  0,00%   [Unknown]  •  0,2 ms
                                                  0,00%   [CPU Ready]  •  0,05 ms
                                              ► 1,39%   IsMatch  •  132 ms  •  System.Text.RegularExpressions.Regex.IsMatch(String)
                                                0,99%   [Unknown]  •  94 ms
                                              ► 0,06%   IndexOf  •  5,3 ms  •  System.String.IndexOf(String, Int32, Int32, StringComparison)
                                              ► 0,03%   clr.dll  •  2,5 ms
                                                0,01%   mscorlib.ni.dll  •  0,8 ms
                                                0,01%   IndexOf  •  0,8 ms  •  System.Globalization.CompareInfo.IndexOf(String, String, Int32, Int32, CompareOptions)
                                                0,00%   [CPU Ready]  •  0,01 ms
                                              19,3%   GetFilesRecursive  •  1 828 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList, RecursionState, String, Boolean, GetFileSystemEntries, IList, Dictionary)
                                              ► 17,7%   GetFilesRecursiveStep  •  1 680 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursiveStep(RecursionState, String, Boolean, GetFileSystemEntries)
                                                0,87%   GetFilesRecursive  •  82 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList, RecursionState, String, Boolean, GetFileSystemEntries, IList, Dictionary)
                                                ► 0,46%   GetFilesRecursive  •  44 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursive(IList, RecursionState, String, Boolean, GetFileSystemEntries, IList, Dictionary)
                                                ► 0,37%   GetFilesRecursiveStep  •  35 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursiveStep(RecursionState, String, Boolean, GetFileSystemEntries)
                                                  0,04%   [Unknown]  •  3,6 ms
                                                ► 0,00%   <GetFilesRecursive>b__0  •  0,0000004 ms  •  Microsoft.Build.Shared.FileMatcher+<>c__DisplayClass29_0.<GetFilesRecursive>b__0(String)
                                                0,61%   [Unknown]  •  58 ms
                                              ► 0,03%   Microsoft.Build.ni.dll  •  2,8 ms
                                              ► 0,01%   TrimTrailingSlashes  •  1,1 ms  •  Microsoft.Build.Shared.FileUtilities.TrimTrailingSlashes(String)
                                              ► 0,01%   <GetFilesRecursive>b__0  •  1,0 ms  •  Microsoft.Build.Shared.FileMatcher+<>c__DisplayClass29_0.<GetFilesRecursive>b__0(String)
                                                0,01%   clr.dll  •  0,7 ms
                                              3,08%   [Unknown]  •  292 ms
                                            ► 1,74%   <GetFilesRecursive>b__0  •  165 ms  •  Microsoft.Build.Shared.FileMatcher+<>c__DisplayClass29_0.<GetFilesRecursive>b__0(String)
                                            ► 0,09%   TrimTrailingSlashes  •  8,7 ms  •  Microsoft.Build.Shared.FileUtilities.TrimTrailingSlashes(String)
                                            ► 0,07%   clr.dll  •  7,0 ms
                                            ► 0,02%   Microsoft.Build.ni.dll  •  1,7 ms
                                            ► 0,01%   Any  •  1,4 ms  •  System.Linq.Enumerable.Any(IEnumerable, Func)
                                              0,01%   mscorlib.ni.dll  •  1,2 ms
                                              0,01%   IndexOf  •  0,9 ms  •  System.String.IndexOf(String, Int32, Int32, StringComparison)
                                            ► 0,01%   TryGetValue  •  0,8 ms  •  System.Collections.Generic.Dictionary`2.TryGetValue(!0, out !1)
                                            ► 0,01%   PathsEqual  •  0,6 ms  •  Microsoft.Build.Shared.FileUtilities.PathsEqual(String, String)
                                            ► 0,01%   NormalizeForPathComparison  •  0,6 ms  •  Microsoft.Build.Shared.FileUtilities.NormalizeForPathComparison(String)
                                              0,00%   [CPU Ready]  •  0,1 ms
                                            ► 0,00%   Add  •  0,0000008 ms  •  System.Collections.Generic.List`1.Add(!0)
                                          ► 14,3%   <GetFilesRecursive>b__0  •  1 355 ms  •  Microsoft.Build.Shared.FileMatcher+<>c__DisplayClass29_0.<GetFilesRecursive>b__0(String)
                                            6,27%   [Unknown]  •  596 ms
                                          ► 1,45%   GetFilesRecursiveStep  •  138 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursiveStep(RecursionState, String, Boolean, GetFileSystemEntries)
                                          ► 0,08%   Microsoft.Build.ni.dll  •  7,8 ms
                                          ► 0,02%   Any  •  1,5 ms  •  System.Linq.Enumerable.Any(IEnumerable, Func)
                                            0,01%   MoveNext  •  1,4 ms  •  System.SZArrayHelper+SZGenericArrayEnumerator`1.MoveNext()
                                            0,01%   mscorlib.ni.dll  •  1,0 ms
                                          ► 0,01%   TryGetValue  •  0,9 ms  •  System.Collections.Generic.Dictionary`2.TryGetValue(!0, out !1)
                                          ► 0,01%   NormalizeForPathComparison  •  0,8 ms  •  Microsoft.Build.Shared.FileUtilities.NormalizeForPathComparison(String)
                                            0,00%   [CPU Ready]  •  0,004 ms
                                            0,00%   clr.dll  •  0,000002 ms
                                          ► 0,00%   Add  •  0,0000004 ms  •  System.Collections.Generic.List`1.Add(!0)
                                          ► 0,00%   TrimTrailingSlashes  •  0,0000004 ms  •  Microsoft.Build.Shared.FileUtilities.TrimTrailingSlashes(String)
                                          0,20%   [Unknown]  •  19 ms
                                        ► 0,09%   <GetFilesRecursive>b__0  •  8,3 ms  •  Microsoft.Build.Shared.FileMatcher+<>c__DisplayClass29_0.<GetFilesRecursive>b__0(String)
                                        ► 0,05%   GetFilesRecursiveStep  •  5,0 ms  •  Microsoft.Build.Shared.FileMatcher.GetFilesRecursiveStep(RecursionState, String, Boolean, GetFileSystemEntries)
                                          0,01%   clr.dll  •  0,8 ms
                                      ► 0,06%   GetFileSearchData  •  6,1 ms  •  Microsoft.Build.Shared.FileMatcher.GetFileSearchData(String, String, GetFileSystemEntries, DirectoryExists, out Boolean, out RecursionState)
                                      ► 0,04%   Exists  •  4,2 ms  •  System.IO.Directory.Exists(String)
                                        0,02%   [Unknown]  •  1,6 ms
                                        0,00%   clr.dll  •  0,0000004 ms
                                    ► 0,09%   Sort  •  8,3 ms  •  System.Array.Sort(!!0[], IComparer)
                                ► 5,62%   SelectItems  •  533 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+RemoveOperation.SelectItems(Builder, ImmutableHashSet)
                                ► 0,16%   SelectItems  •  15 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+IncludeOperation.SelectItems(Builder, ImmutableHashSet)
                                ► 0,12%   SaveItems  •  12 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+IncludeOperation.SaveItems(ICollection, Builder)
                                  0,11%   [Unknown]  •  11 ms
                                ► 0,02%   GetEnumerator  •  1,5 ms  •  System.Collections.Immutable.ImmutableList`1.GetEnumerator()
                                ► 0,00%   ToList  •  0,000002 ms  •  System.Linq.Enumerable.ToList(IEnumerable)
                                ► 0,00%   ToBuilder  •  0,0000008 ms  •  System.Collections.Immutable.ImmutableList`1.ToBuilder()
                                ► 0,00%   IncreaseListCapacityIfNecessary  •  0,0000004 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+IncludeOperation.IncreaseListCapacityIfNecessary(List, Int32)
                              ► 0,10%   Apply  •  9,1 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+UpdateOperation.Apply(Builder, ImmutableHashSet)
                              ► 0,03%   MutateItems  •  3,1 ms  •  Microsoft.Build.Evaluation.LazyItemEvaluator`4+IncludeOperation.MutateItems(ICollection)
                              0,00%   [Unknown]  •  0,2 ms
                            ► 0,00%   Push  •  0,0000004 ms  •  System.Collections.Generic.Stack`1.Push(!0)
                      ► 0,04%   MoveNext  •  3,7 ms  •  System.Linq.Enumerable+<SelectManyIterator>d__16`2.MoveNext()
                      ► 0,01%   clr.dll  •  1,2 ms
                    ► 0,03%   Sort  •  2,7 ms  •  System.Linq.EnumerableSorter`1.Sort(!0[], Int32)
                      0,00%   [Unknown]  •  0,2 ms
                  ► 0,01%   clr.dll  •  0,8 ms
            ► 0,72%   EvaluateItemGroupElement  •  68 ms  •  Microsoft.Build.Evaluation.Evaluator`4.EvaluateItemGroupElement(ProjectItemGroupElement, LazyItemEvaluator)
            ► 0,16%   PerformDepthFirstPass  •  15 ms  •  Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement)
            ► 0,09%   AddItem  •  8,7 ms  •  Microsoft.Build.Evaluation.Project+Data.AddItem(ProjectItem)
              0,01%   [Unknown]  •  1,2 ms
            ► 0,01%   ReadTargetElement  •  0,9 ms  •  Microsoft.Build.Evaluation.Evaluator`4.ReadTargetElement(ProjectTargetElement, LinkedList, Dictionary)
            ► 0,00%   Add  •  0,0000004 ms  •  System.Collections.Generic.List`1.Add(!0)
          ► 0,06%   AddItemIgnoringCondition  •  5,6 ms  •  Microsoft.Build.Evaluation.Project+Data.AddItemIgnoringCondition(ProjectItem)
            0,02%   [Unknown]  •  1,5 ms
  ► 2,66%   SetResult  •  253 ms  •  System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(!0)
  ► 0,04%   GetItemProvenance  •  3,8 ms  •  Microsoft.Build.Evaluation.Project.GetItemProvenance(ProjectItem)
`

**Comment by dsplaisted** [comment] 2017-07-18 02:06
@cdmihai @rainersigwald @AndyGerlicher I did some investigation into this, and did a local fix for optimizing `ComparePathsNoThrow` which significantly speeded things up, but on further investigation I think we have an O(n^2) perf issue with the following code pattern:

```xml
<None Update="@(None)" Foo="Bar" />
```

Adding this line to a very simple project with around 11,000 `None` items changed the build time from 0.63 seconds to 32 seconds (after applying my other fix, before then it took about 8 minutes).

`UpdateOperation.Apply` [calls `ItemSpec.MatchesItem`](https://github.com/Microsoft/msbuild/blob/07c3b3392dc05e0e3aba18bdec235a374aa72301/src/Build/Evaluation/LazyItemEvaluator.UpdateOperation.cs#L36) for each item currently in the list.  When there is a fragment of type `ItemExpressionFragment`, then it ends up comparing the item against each referenced item, which when using the pattern `<None Update="@(None)" />` is all of the items in the list.  So each item ends up [being compared](https://github.com/Microsoft/msbuild/blob/07c3b3392dc05e0e3aba18bdec235a374aa72301/src/Build/Evaluation/ItemSpec.cs#L359) with all the items in the list, resulting in an n^2 runtime.

**Comment by jasselin** [comment] 2017-07-18 14:44
@rainersigwald @davkean @dsplaisted I did some further testing and I am pretty sure `EnableDefaultItems` is ignored or overridden by Visual Studio. When I update or add something to `DefaultItemExcludes`, I see (using procmon) that the pattern I added is looked for in every subdirectories. Is there a way to see the MSBuild output when called from within devenv.exe so I can confirm the value used for `EnableDefaultItems`?

**Comment by rainersigwald** [comment] 2017-07-18 15:36
@jasselin Yes; check out https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#diagnosing-design-time-builds -- because you're using a new-sdk project, follow the "new project system" instructions.

I wonder if this is related to the VS-ignores-conditions-so-it-can-display-source-files-from-all-flavors-of-the-project behavior?

**Comment by jasselin** [comment] 2017-07-18 20:10
@rainersigwald Sadly, I thing your right. When I comment the following sections, everything is lightning fast.

https://github.com/dotnet/sdk/blob/a4bceb67b160c72318a581d87d52796e4fa31794/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.props#L25-L33

https://github.com/aspnet/websdk/blob/dev/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L27-L45

I was able to confirm using the "Build - Design-time" output that `EnableDefaultItems` is set to `False`. Is there anything we can do to make this work properly?

**Comment by DavidUrting** [comment] 2017-09-25 14:45
I have a project with two **nodes_modules** folders which make Visual Studio extremely slow. After
adding <EnableDefaultItems>false</EnableDefaultItems> the performance is better but then there seems to be a problem when precompiling razor views: the <projectname>.PrecompiledViews.dll is generated but it is empty.

When setting <EnableDefaultItems>true</EnableDefaultItems> the dll is generated with the razor views included.

Does anyone has the same problem?

**Comment by dsplaisted** [comment] 2017-09-25 19:36
@DavidUrting See [this comment](https://github.com/dotnet/cli/issues/5918#issuecomment-331740052) for a workaround which should addrcess the perf issue you are hitting.

**Comment by ofir-shapira-como** [comment] 2017-10-05 07:38
```XML
<DefaultItemExcludes>$(DefaultItemExcludes);path\to\node_modules\**</DefaultItemExcludes>

Helped me.

**Comment by StarpTech** [comment] 2017-10-09 19:28
Does not work for me.

**Comment by ofir-shapira-como** [comment] 2017-10-10 05:01
@StarpTech, where is your `node_modules` located?

**Comment by StarpTech** [comment] 2017-10-10 08:47
@ofir-shapira-como wwwroot/node_modules

**Comment by StarpTech** [comment] 2017-10-10 08:50
@ofir-shapira-como forget it seems to work know, thank you.

**Comment by rainersigwald** [comment] 2018-03-27 16:38
There's been a lot of perf work in this area, so we're going to close this. If you have a specific case that's still bad, please open a new issue with repro steps.

**Closed by rainersigwald** 2018-03-27 16:38 UTC
Labels: Feature - Globbing, performance
