### ISSUE TITLE
Preventing SDKs from automatically adding assemblies

### ISSUE THREAD

**Issue by jaredpar** [microsoft/msbuild#1511] opened 2017-01-02 03:15 UTC
Consider as an example here the VS SDK.  When installed on a machine it will cause new references to be available to programs by default.  

This is certainly convenient for many simple applications.  It allows for references to be added with no alterations to the standard MSBuild project file. 

This is decidedly inconvenient though for more complex applications.  In particular those where predictability of the build is more important than little conveniences like this.  For such projects it would be nice to opt-out of automatically inserting references to the build.  That helps ensure builds are consistent from machine to machine.

Take the [following PR](https://github.com/dotnet/roslyn/pull/16142) as an example of why this important.  There are two commits here.  The [first of which](https://github.com/dotnet/roslyn/pull/16142/commits/a202711501e26a514309b65f2554d2e03e441940) builds clean on a machine with Dev14, but fails on a machine with Dev15.  This happens because the Dev15 SDK inserts extra references that causes conflicts with the change.  It took the [second commit](https://github.com/dotnet/roslyn/pull/16142/commits/453b5a3cb927a37a4d1f2306c49cbcc3f5945a09) to cleanup the Dev15 SDK errors.  

Ideally we could avoid this problem by having a clean / predictable build option for MSBuild that ignored global state like the VS SDK.

**Comment by AlexEyler** [comment] 2017-01-05 03:25
This would be fantastic - as a (hopefully short) aside, one of my long term goals for the VSSDK reference story is to get completely out of installing any reference assemblies at all but it doesn't seem reachable in the near future - it would break many existing projects. We (our team) need to do better to support deterministic building and the best tool for that right now is NuGet.

Having said that, I also know that usage of `AssemblysFolderEx` in the registry is pretty widespread - I would be in support of a build option that allows the assembly search path to be configurable. Also, I believe this is similarly proposed in #772.

**Comment by jaredpar** [comment] 2017-01-05 17:14
I've made some progress here by customizing the `AssemblySearchPaths` property:

> https://github.com/dotnet/roslyn/pull/16249

Been able to remove GAC, AssemblyFoldersEx, AssemblyFolders and a couple of other items from our search so far.

It's workable and gets me close to the proposal.  The problem though is I feel like this is still very undocumented.  The original value for `AssemblySearchPaths` is the following:

``` xml
    <AssemblySearchPaths Condition=" '$(AssemblySearchPaths)' == ''">
      {CandidateAssemblyFiles};
      $(ReferencePath);
      {HintPathFromItem};
      {TargetFrameworkDirectory};
      {Registry:$(FrameworkRegistryBase),$(TargetFrameworkVersion),$(AssemblyFoldersSuffix)$(AssemblyFoldersExConditions)};
      {AssemblyFolders};
      {GAC};
      {RawFileName};
      $(OutDir)
    </AssemblySearchPaths>
 ```

There are [some comments](https://referencesource.microsoft.com/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/14.0/bin_/amd64/Microsoft.Common.CurrentVersion.targets,543) explaining the meaning of some of these values.  For others though the only way I could discern what they did was to simply delete them, rebuild and see what broke.  Would be nice to better understand what these values mean.

**Comment by jeffkl** [comment] 2017-01-05 17:28
@jaredpar What if we introduce a boolean property for controlling this?  Let's say it's called `RestrictAssemblySearchPaths` and when you set it to `true`, then the default `AssemblySearchPaths` is your narrowed down list.  This would allow users to toggle it for code bases where they only want references to come from packages or the build itself.  Users could still override the search paths with a custom list but a toggle like this would probably satisfy the major scenarios.

**Comment by jaredpar** [comment] 2017-01-05 18:57
@jeffkl that might work.  I'm still a bit uncertain though exactly what I've narrowed my list down to.  I have some ideas on what they are but that's mostly based on what broke when I deleted them.  Maybe it would help to understand a bit better what these mean and what type of references are expected in those locations.

**Comment by rainersigwald** [comment] 2018-04-17 16:12
There is documentation for the include paths in the SearchPaths section of https://docs.microsoft.com/en-us/visualstudio/msbuild/resolveassemblyreference-task, but it's a bit stale (`{AssemblyFolders}` isn't actually restricted to Visual Studio.NET 2003, for instance).

**Comment by rainersigwald** [comment] 2019-02-26 21:16
We've talked about it but I didn't see it written down here:

In addition to a big "don't look in the machine-dependent locations" flag, we should also have an off-switch property for each location. That way, even a project that uses one of the "bad" locations can shut off the others.

**Comment by rainersigwald** [comment] 2019-10-07 20:37
I have no idea how we didn't notice this until now but I'm going to mark this as a duplicate (we had almost the exact same discussion there).

**Comment by rainersigwald** [comment] 2019-10-07 20:37
Duplicate of #772

**Closed by rainersigwald** 2019-10-07 20:37 UTC
Labels: Documentation, Task: Resolve Assembly References (RAR)
