### ISSUE TITLE
Adopt new Roslyn location when moved out of the msbuild\bin folder

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/msbuild#1183] opened 2016-10-12 00:07 UTC
In MSBuild 15.0 Roslyn can no longer correctly load a custom version of` Microsoft.Build.Tasks.CodeAnalysis.dll.  This is done as part of our basic check-in process to validate the new compiler can be self hosted by our code base.

The details here are that Roslyn uses the following snippet to load our just build task:

``` xml
  <UsingTask TaskName="Microsoft.CodeAnalysis.BuildTasks.Csc"
             AssemblyFile="$(BootstrapBuildPath)\Microsoft.Build.Tasks.CodeAnalysis.dll"
             Condition="'$(BootstrapBuildPath)' != ''" />
```

This will successfully load our newly built task.  This task DLL has a dependency on Microsoft.CodeAnalysis.dll.  This DLL exists next to Microsoft.Build.Tasks.CodeAnalysis.dll on disk and previously was loaded by MSBuild 14.0 in this setup.  In MSBuild 15.0 the Microsoft.CodeAnalysis.dll which ships with MSBuild is loaded instead.

The failure in action can be viewed in [this Jenkins job](https://ci.dot.net/job/dotnet_roslyn/job/dev15-rc/job/windows_debug_unit32_prtest/13/).  Full diagnostic build log available [here](https://ci.dot.net/job/dotnet_roslyn/job/dev15-rc/job/windows_debug_unit32_prtest/13/artifact/Binaries/Build.log).  

Has anything related to assembly loading changed in MSBuild recently? 

This blocks our ability to use MSBuild 15.0.  It took us a while to notice because the break isn't evident until a portion of the contract between Microsoft.Build.Tasks.CodeAnalysis and Microsoft.CodeAnalysis changes.  That tends to happen in waves and we just recently ran into it.

**Comment by jeffkl** [comment] 2016-10-12 14:50
@tmeschter would your recent change address this?
```
error MSB4018: The "Csc" task failed unexpectedly.
error MSB4018: System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.BuildPaths' from assembly 'Microsoft.CodeAnalysis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
error MSB4018:    at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
error MSB4018:    at Microsoft.Build.Utilities.ToolTask.Execute()
```

@jaredpar is the same invocation of MSBuild loading different `Microsoft.Build.Tasks.CodeAnalysis.dll` instances?  Or does this one invocation only try to load one version of the DLL?

**Comment by jaredpar** [comment] 2016-10-12 15:12
@jeffkl in this scenario there are three dlls of interest:

1. Microsoft.Build.Tasks.CodeAnalysis
1. Microsoft.CodeAnalysis.CSharp
1. Microsoft.CodeAnalysis

The first is our build task assembly and it references the other two.  Our 'UsingTask' explicitly loads Microsoft.Build.Tasks.CodeAnalysis.  This properly loads from our build location.  The other two though load instead from the MSBuild installation path, instead of our build location.

I just added some extra validation this morning to catch when this type of bad load occurs.  It validates the above description:

> https://github.com/dotnet/roslyn/pull/14445/commits/f32cfb9018e95f71428f157572b76483b457fc6e

**Comment by jeffkl** [comment] 2016-10-12 15:50
I'm fairly certain that @tmeschter just fixed this.  Tom?

**Comment by tmeschter** [comment] 2016-10-12 16:22
@jaredpar @jeffkl That should be *partially* fixed now. We used to explicitly look next to msbuild.exe when resolving assemblies. Now we only do that for Microsoft.Build.* assemblies so that we can redirect to the current version.

There's still a potential issue in that the binaries located next to msbuild.exe may be picked up by the default assembly loader before MSBuild gets any say in the matter. I don't think there's anything that can be done about that on the MSBuild side.* I've advised the dotnet CLI guys to stop doing that.

*In theory what we can do is implement our own `AssemblyLoadContext` to isolate task assembly loading and dependency resolution. Unfortunately there are loading bugs in the runtime that won't be fixed for RTM that effectively preclude us from doing that.

**Comment by rainersigwald** [comment] 2016-10-15 12:21
@jaredpar This is happening when building with an LKG Dev15 install right (Preview 5?)?

What is the major/minor version of the just-built Roslyn that you want to load? If it matches the major/minor of the assemblies in the MSBuild folder the CLR loader will prefer the copy in the application base directory (MSBuild's bin) over the copy that it would eventually find from `LoadFrom`.

**Comment by jaredpar** [comment] 2016-10-17 16:18
@rainersigwald this is with Dev15 Preview 5

> If it matches the major/minor of the assemblies in the MSBuild folder the CLR loader will prefer the copy in the application base directory (MSBuild's bin) over the copy that it would eventually find from LoadFrom.

We need to change this behavior then or have a suitable work around.  Roslyn fundamentally depends, and has depended on, the ability to load custom built versions of our DLLs in order to validate our compiler.  For many other reasons the versions of these DLLs tend to match those installed with MSBuild (binding redirects, and config files force our hand here).  

This has worked for quite some time now.  What changed to break this?

**Comment by tmeschter** [comment] 2016-10-17 16:43
@jaredpar @rainersigwald I'm confused--are we talking about MSBuild on _Desktop_ or MSBuild on _Core_? Because they now have different assembly loading behavior. I assumed we were talking about Core.

**Comment by jaredpar** [comment] 2016-10-17 16:57
@tmeschter I'm specifically talking about Desktop for this bug.

**Comment by rainersigwald** [comment] 2016-10-21 14:45
The core of the issue is that Roslyn's task assembly (`Microsoft.Build.Tasks.CodeAnalysis.dll`) depends on other assemblies (`Microsoft.CodeAnalysis.dll`) that are _in the MSBuild folder_. Location of the C# compiler is primarily a historical accident--both `MSBuild.exe` and `csc.exe` used to ship with the .NET Framework and so were colocated, and after MSBuild moved out it was easiest to bring the compiler with it.

The fix for this will be to move the Roslyn assemblies to a different folder so the CLR loader won't find them in MSBuilds Application Base directory. That will require coordinated effort here and in the Roslyn repo: https://github.com/dotnet/roslyn/issues/14660 tracks moving the assemblies in the Roslyn setup component, and this bug now tracks adjusting [the default `UsingTasks`](https://github.com/Microsoft/msbuild/blob/1a55490345b6882f8610a07f68671554b16d64b3/src/XMakeTasks/Microsoft.Common.tasks#L170-L172) that we ship to deal with the new location.

We must also be careful to test both x86 and amd64 MSBuild with these changes, as Roslyn will likely want to stop redundantly shipping the same assembly in two folders.

**Closed** 2016-11-22 16:34 UTC
Labels: Priority 1
