### ISSUE TITLE
"None" build Item files causes MSBuild to rebuild if they are inside a folder

### ISSUE THREAD

**Issue by chinwobble** [Microsoft/msbuild#2873] opened 2018-01-18 04:53 UTC
### Steps to reproduce

1. Run the below project file 
2. Build repeatedly in VS 2017 15.5.4 
3. The project will build repeatedly despite not making changes 

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KonradSikorski.OpenCvSharp3-NativeDlls" Version="3.2.0.201704192" />
    <PackageReference Include="OpenCvSharp3-WithoutDll" Version="3.3.1.20171117" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(NativeDlls)\x64\OpenCvSharpExtern.dll">
      <Link>x64\OpenCvSharpExtern.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="$(NativeDlls)\x64\opencv_ffmpeg320_64.dll">
      <Link>x64\opencv_ffmpeg320_64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

```

Directory contents:
```
/
- ClassLibrary1.csproj
- Class1.cs
```

Command line
```
msbuild ClassLibrary1.csproj /t:Build
```

### Expected  behavior

If no files have changed, the project should report "up-to-date" and not recompile

### Actual behavior

The project will rebuild even if no files have changed.
However if the linked files are linked to the root of the project output rather than a folder inside the output directory for instance:
`<Link>opencv_ffmpeg320_64.dll</Link>` instead of `<Link>x64\opencv_ffmpeg320_64.dll</Link>` then project will correctly report that it is up to date. 

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 14.0.25420.1

OS info:
Windows 10 

other info:

**Comment by dasMulli** [comment] 2018-01-18 12:11
If this is only about the up-to-date check inside VS and not msbuild itself, this may be a duplicate of https://github.com/dotnet/project-system/issues/3023

**Comment by rainersigwald** [comment] 2018-01-25 14:15
Duplicate of dotnet/project-system#3023.

And on my internal build of VS, it works!

```
1>FastUpToDate: Latest write timestamp on input is 1/25/2018 8:12:16 AM on 's:\work\attemptrepro2873\attemptrepro2873\obj\attemptrepro2873.csproj.nuget.g.targets'. (attemptrepro2873)
1>FastUpToDate: Earliest write timestamp on output is 1/25/2018 8:12:25 AM on 's:\work\attemptrepro2873\attemptrepro2873\obj\Debug\netstandard2.0\attemptrepro2873.pdb'. (attemptrepro2873)
1>FastUpToDate: Checking PreserveNewest file 'C:\Users\raines\.nuget\packages\konradsikorski.opencvsharp3-nativedlls\3.2.0.201704192\NativeDlls\x64\opencv_ffmpeg320_64.dll': (attemptrepro2873)
1>FastUpToDate:     Write 6/20/2017 5:25:04 PM: 'C:\Users\raines\.nuget\packages\konradsikorski.opencvsharp3-nativedlls\3.2.0.201704192\NativeDlls\x64\opencv_ffmpeg320_64.dll'. (attemptrepro2873)
1>FastUpToDate:     Output file write 6/20/2017 5:25:04 PM: 's:\work\attemptrepro2873\attemptrepro2873\bin\Debug\netstandard2.0\x64\opencv_ffmpeg320_64.dll'. (attemptrepro2873)
1>FastUpToDate: Checking PreserveNewest file 'C:\Users\raines\.nuget\packages\konradsikorski.opencvsharp3-nativedlls\3.2.0.201704192\NativeDlls\x86\OpenCvSharpExtern.dll': (attemptrepro2873)
1>FastUpToDate:     Write 6/20/2017 5:25:10 PM: 'C:\Users\raines\.nuget\packages\konradsikorski.opencvsharp3-nativedlls\3.2.0.201704192\NativeDlls\x86\OpenCvSharpExtern.dll'. (attemptrepro2873)
1>FastUpToDate:     Output file write 6/20/2017 5:25:10 PM: 's:\work\attemptrepro2873\attemptrepro2873\bin\Debug\netstandard2.0\OpenCvSharpExtern.dll'. (attemptrepro2873)
1>FastUpToDate: Checking PreserveNewest file 'C:\Users\raines\.nuget\packages\konradsikorski.opencvsharp3-nativedlls\3.2.0.201704192\NativeDlls\x86\opencv_ffmpeg320.dll': (attemptrepro2873)
1>FastUpToDate:     Write 6/20/2017 5:25:14 PM: 'C:\Users\raines\.nuget\packages\konradsikorski.opencvsharp3-nativedlls\3.2.0.201704192\NativeDlls\x86\opencv_ffmpeg320.dll'. (attemptrepro2873)
1>FastUpToDate:     Output file write 6/20/2017 5:25:14 PM: 's:\work\attemptrepro2873\attemptrepro2873\bin\Debug\netstandard2.0\opencv_ffmpeg320.dll'. (attemptrepro2873)
1>FastUpToDate: Checking PreserveNewest file 'C:\Users\raines\.nuget\packages\konradsikorski.opencvsharp3-nativedlls\3.2.0.201704192\NativeDlls\x64\OpenCvSharpExtern.dll': (attemptrepro2873)
1>FastUpToDate:     Write 6/20/2017 5:24:58 PM: 'C:\Users\raines\.nuget\packages\konradsikorski.opencvsharp3-nativedlls\3.2.0.201704192\NativeDlls\x64\OpenCvSharpExtern.dll'. (attemptrepro2873)
1>FastUpToDate:     Output file write 6/20/2017 5:24:58 PM: 's:\work\attemptrepro2873\attemptrepro2873\bin\Debug\netstandard2.0\x64\OpenCvSharpExtern.dll'. (attemptrepro2873)
1>FastUpToDate: Project is up to date. (attemptrepro2873)
```

**Closed by rainersigwald** 2018-01-25 14:15 UTC
