### ISSUE TITLE
CoreCompileInputs.cache is not removed by clean

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#1647] opened 2017-02-01 11:31 UTC
All the other caches are being cleaned up.

1. Create a new .NET Core project
2. Build
3. Clean

Expected: obj to be empty
Actual: CoreCompileInputs.cache exists

You can see that it's not being added to [Project].FileListAbsolute.txt.

**Comment by jeffkl** [comment] 2017-02-01 15:32
Dupe of #1577

**Closed by jeffkl** 2017-02-01 15:32 UTC
