### ISSUE TITLE
MSBuild extensions should get dependencies from the package cache

### ISSUE THREAD

**Issue by AArnott** [microsoft/msbuild#1755] opened 2017-02-27 02:36 UTC
MSBuild extensions on .NET Framework have to embed all their own dependencies in the NuGet package that delivers them. This makes them extra large even though the user may already have similar contents in their package cache elsewhere.

In the MSBuild Core world, it is unreasonable for MSBuild extensions to embed all their own dependencies because the dependencies may vary with the OS and CPU architecture. This would be very large, and anyway MSBuild doesn't provide Tasks a way for the CoreCLR to load the assemblies appropriately.

This should work recursively for a Task, as an MSBuild Task itself may support "extensions" of its own (such as [CodeGeneration.Roslyn](https://github.com/aarnott/codegeneration.roslyn)) which may come with their own dependencies as well.

This applies to both managed and unmanaged DLLs. 

See also https://github.com/Microsoft/msbuild/issues/858#issuecomment-238268449

**Comment by mwpowellhtx** [comment] 2019-08-01 21:20
Running into this very issue, I think; or at minimum a close neighbor, [with some slight, key philosophical CGR differences](https://github.com/mwpowellhtx/Code.Generation.Roslyn).

**Comment by mungojam** [comment] 2020-06-16 14:04
Is there any known workaround to this? It's just hit me badly after a day of switching to using a custom MsBuild Task

**Comment by rainersigwald** [comment] 2020-06-24 16:09
@mungojam The task can redistribute all non-system dependencies. #5037 will resolve this in the future.

**Comment by rainersigwald** [comment] 2020-06-24 16:09
Duplicate of #5037

**Closed by rainersigwald** 2020-06-24 16:09 UTC

**Comment by AArnott** [comment] 2020-06-24 16:13
@rainersigwald Thanks for looking at this issue. I don't see it as a duplicate of #5037 however. It's not just that msbuild tasks have their own ALC. I'm proposing that the ALC come preconfigured to load dependencies from the nuget package cache so that runtime dependencies don't have to even ship with the msbuild task. Also, since runtime dependencies vary based on OS and .NET runtime, msbuild tasks would get very heavy if they shipped the transitive closure of all their nuget package dependencies for every single OS and runtime, while the nuget package cache can very efficiently represent this.

**Comment by rainersigwald** [comment] 2020-06-24 16:17
`AssemblyDependencyResolver` does all that, and is covered by #5037.
