### ISSUE TITLE
How to get help with PR?

### ISSUE THREAD

**Issue by cclauson** [Microsoft/msbuild#3333] opened 2018-05-20 06:52 UTC
Hi,

I have a PR up that should fix an issue with the MSBuild expression parser.  The PR is here:
https://github.com/Microsoft/msbuild/pull/3165

I posted previously here:
https://github.com/Microsoft/msbuild/issues/3163
but got no replies.  Can anyone with MSBuild help me with this?

Thank you so much.

**Comment by rainersigwald** [comment] 2018-05-21 15:07
Duplicate of #3163

**Closed by rainersigwald** 2018-05-21 15:07 UTC

**Comment by cclauson** [comment] 2018-05-21 21:35
@rainersigwald Maybe, but how do I actually get help?  Is there any procedure for this?  Thanks so much.
