### ISSUE TITLE
Cache warnings on disk, and re-display on re-build

### ISSUE THREAD

**Issue by foriequal0** [microsoft/msbuild#5066] opened 2020-01-22 01:33 UTC
### Steps to reproduce

1. Make a new project
```shell
dotnet new console --name TestWarn
```
2. Edit `Program.cs`
```
using System;

namespace TestWarn
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = 0;
        }
    }
}
```
3. Build twice
First build:
```shell
dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 29.64 ms for /.../TestWarn/TestWarn.csproj.
Program.cs(9,17): warning CS0219: The variable 'x' is assigned but its value is never used [/.../TestWarn/TestWarn.csproj]
  TestWarn -> /.../TestWarn/bin/Debug/netcoreapp3.1/TestWarn.dll

Build succeeded.

Program.cs(9,17): warning CS0219: The variable 'x' is assigned but its value is never used [/.../TestWarn/TestWarn.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.98
```
You get warnings.

Second build:
```shell
dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 32.44 ms for /.../TestWarn/TestWarn.csproj.
  TestWarn -> /.../TestWarn/bin/Debug/netcoreapp3.1/TestWarn.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.88
```
You don't get warnings.

### Expected  behavior
You get warnings again when you re-build like Rust's Cargo.
If you do the exact same thing on Rust (with Cargo >= 1.40), you can get warnings twice, even though it builds incrementally.

```shell
cargo new test-warn
cd test-warn
cat <<EOF > src/main.rs
fn main() {
   let x = 0;
}
EOF
```
```shell
cargo build    
   Compiling test-warn v0.1.0 (/.../test-warn)
warning: unused variable: `x`
 --> src/main.rs:2:9
  |
2 |     let x = 0;
  |         ^ help: consider prefixing with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.23s

cargo build
warning: unused variable: `x`
 --> src/main.rs:2:9
  |
2 |     let x = 0;
  |         ^ help: consider prefixing with an underscore: `_x`
  |
  = note: `#[warn(unused_variables)]` on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
```
Cargo changelog: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#added-2

I prefer to separate the build step and the lint step for CI. `dotnet clean` between the steps won't be necessary if we cache warnings. I could make a workaround by saving the output and `grep`-ing it though, but this is a little bit fragile.

### Environment data
```shell
dotnet --info
.NET Core SDK(global.json 반영):
 Version:   3.1.100
 Commit:    cd82f021f4

런타임 환경:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

I've made an issue on the dotnet Roslyn repo first https://github.com/dotnet/roslyn/issues/40986 but I've been suggested to move it to here.

**Comment by rainersigwald** [comment] 2020-01-27 20:38
This is a great idea that unfortunately is very difficult to implement in MSBuild. The core problem is that the MSBuild engine itself isn't stateful; we don't have a place to store things like warnings. We've thought about adding such a store (#701) but haven't done so yet because it's a high-complexity problem.

Even if we had a place to store the warnings, this is made more complicated by partial incremental builds of targets and other ingrained MSBuild behaviors.

IDEs tend to harvest warnings in a different way so they have their own persistence story and wouldn't be helped by changing this at the MSBuild level.

As a result, I don't think we'll be able to do this in the foreseeable future.

**Comment by foriequal0** [comment] 2020-01-29 01:08
Thank you for your reply! I understand that it is hard to do in the foreseeable future under the current design of the MSBuild. I always appreciate recent improvements of the MSBuild. I'm looking forward to the day to make it possible.

**Comment by rainersigwald** [comment] 2020-04-15 14:46
Duplicate of #3046

**Closed by rainersigwald** 2020-04-15 14:46 UTC
Labels: Area: Debuggability, blocked
