### ISSUE TITLE
Content not copied to output of dependent project

### ISSUE THREAD

**Issue by drauch** [microsoft/msbuild#5052] opened 2020-01-14 10:48 UTC
### Steps to reproduce

I have the following repro solution structure (see attachmeent):

```
Solution
|- ProjectA "DependentProjectsOutputNotCopied_Dependency"
   |- Content: Content.txt (Copy if newer)
|- ProjectB "DependentProjectsOutputNotCopied_Reference"
   |- ProjectReference: ProjectA
```

Both projects target .NET Framework 4.7.2, both are using the new SDK-styled project format.

### Expected  behavior

When I build ProjectB in such a way that ProjectA is built at the same time (e.g., if ProjectA is not up-to-date or by performing “Rebuild all”) the Content.txt is correctly put into the output folder of ProjectB. This should also be the case if ProjectA is not built in this MSBuild run.

### Actual behavior

In all cases where ProjectA is not built (e.g., because it is up-to-date), the Content.txt is NOT copied to the output folder of ProjectB. When I “execute” ProjectB (unit test project) it runs into runtime problems because the necessary Content.txt is not available.

### Environment data
MSBuild used by VS 2019 16.4.1

OS info: Windows 10 1903

**Comment by drauch** [comment] 2020-01-14 10:48
Attachment (repro):
[DependentProjectsOutputNotCopied.zip](https://github.com/microsoft/msbuild/files/4058706/DependentProjectsOutputNotCopied.zip)

**Comment by rainersigwald** [comment] 2020-04-29 16:24
Duplicate of #1054

**Closed by rainersigwald** 2020-04-29 16:24 UTC

**Comment by rainersigwald** [comment] 2020-04-29 16:25
@drauch can you try setting MSBuildCopyContentTransitively=true in all of your projects (probably with a Directory.Build.props file)? It was introduced in 16.5 by #4865 for just this problem.

**Comment by drauch** [comment] 2020-04-29 17:10
Oh, that sounds lovely, will try tomorrow and report back!
