### ISSUE TITLE
"virtual" static libraries

### ISSUE THREAD

**Issue by seanmiddleditch** [Microsoft/msbuild#415] opened 2015-12-24 01:03 UTC
A common trick with hand-rolled build systems - and available to various degrees in popular meta-build systems - is support for "virtual" static library targets.

Such targets are collections of source files that are compiled into object files but _not_ combined into a single archive library. This has several advantages, including a speed boost (less needless disk I/O) and provides a sort of portable version of MSBuild's "Use Dependency Inputs" option that would be implicit in the target's type rather than in the dependee's configuration. This ends up being handy as many "organizational" uses of static libraries are hampered by some of the archaic linker behavior present in C++, especially on Windows (static libraries linked into DLLs can't use `declspec(export)` and global variables with construction side-effects are often accidentally lost).

This request is to directly support such "object collection" libraries directly in MSBuild allowing us to build `.obj` files without generating a `.lib` file and with referencees automatically linking in the objects of the target.

Essentially, this is a request for [CMake's OBJECT libraries](https://cmake.org/Wiki/CMake/Tutorials/Object_Library) (aka "source sets" in [Chromium's GN build tool](https://chromium.googlesource.com/chromium/src/+/master/tools/gn/docs/cookbook.md)) to be directly supported in MSBuild.

**Comment by rainersigwald** [comment] 2016-01-05 19:40
Thanks for the suggestion.

This is a limitation of the C++ build system for Visual Studio that uses MSBuild, but isn't part of the open source MSBuild release. `Microsoft.Cpp.targets` and friends are owned by the Microsoft C++ team and ship with Visual Studio.

I forwarded your request to the owners of C++ build internally. They pointed out that there is a property that controls whether a `.lib` file will be generated that you could set after importing the default (that sets it to true):

```xml
<Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
…

  <PropertyGroup>
    <LibCompiled>false</LibCompiled>
  </PropertyGroup>
```

But they warn that this might have side effects that cause problems elsewhere in your build, since it's not a mainstream scenario. I think you'd still have to (redundantly) specify the use-`.obj` property on the consuming side, but at least the time spent invoking the librarian wouldn't be wasted.

**Comment by seanmiddleditch** [comment] 2016-04-08 07:05
@rainersigwald  - thanks. Is there a public issue tracker to which the suggestion was forwarded?

**Comment by rainersigwald** [comment] 2016-04-08 15:02
Not that I'm aware of, sorry.

**Comment by rainersigwald** [comment] 2017-02-22 17:30
Closing this since the issue is in C++ targets.

**Closed by rainersigwald** 2017-02-22 17:30 UTC
