### ISSUE TITLE
Update used in item group in a target doesn't match the file path

### ISSUE THREAD

**Issue by tmat** [Microsoft/msbuild#3825] opened 2018-10-03 21:52 UTC
### Steps to reproduce

```xml
<Project>
  <Target Name="Build">
    <ItemGroup>
      <I Include="A" X="1"/>
      <I Include="B" X="2"/>
      
      <I Update="A" X=""/>
    </ItemGroup>

    <Message Text="[@(I->'%(X)')]"/>
  </Target>
</Project>
```
### Expected  behavior

`[;2]`

### Actual behavior

`[;]`

**Comment by tmat** [comment] 2018-10-03 21:53
FYI @jasonmalinowski

**Comment by rainersigwald** [comment] 2018-10-03 21:54
Duplicate of #2835

**Closed by rainersigwald** 2018-10-03 21:54 UTC

**Comment by rainersigwald** [comment] 2018-10-03 21:56
Update is completely ignored inside targets. To do conditional updates you must use conditions

```xml
<I Condition="'%(Include)' == 'A'" X="" />
```

Details in the bug I marked this as a duplicate of.
