### ISSUE TITLE
Memory overhead of MSBuildAllProjects property in msbuild evaluation model

### ISSUE THREAD

**Issue by lifengl** [Microsoft/msbuild#3004] opened 2018-02-17 01:50 UTC
### Steps to reproduce

Internal solution with a large number of projects inside, mostly small .Net Core projects.  VS runs out of memory after loading the solution.

MSBuild evaluation model is one of the top contributor, uses 25% of the managed heap.  About half of it are used to store large strings (mostly between 1k to 10k, but some over 10k), and it turns out almost all the large strings are values of MSBuildAllProjects property. 

It turns out all imported .props/.targets concat its full path to the property.  In .Net Core, it uses a large amount of .props/.targets file, and makes this issue worse.  The property seems to be used to track dependencies.

However, it is easy for MSBuild to compute this value based on the import closure in memory, so why just makes it a built-in property instead of asking everyone to do the right thing.  Anyway, the current problem is that the memory overhead.  Can we find out a smart way to fix this problem?

**Comment by lifengl** [comment] 2018-02-17 01:51
Name                                                                                                  	Inc %	          Inc	   Inc Ct	Exc %	        Exc	 Exc Ct	     Fold	Fold Ct
Microsoft.Build!Microsoft.Build.Evaluation.Project                                                   	28.1	  339,988,704	3,931,804.750	 0.0	 37,928.055	862.005	        0	     0
+ Microsoft.Build!Microsoft.Build.Evaluation.Project+Data                                             	28.0	  339,090,400	3,905,625.750	 0.0	106,888.563	861.992	        0	     0
|+ mscorlib!List<Microsoft.Build.Evaluation.ProjectProperty>                                          	15.7	  190,223,296	896,655.500	 0.3	3,801,356.250	1,661.694	3,780,692.250	800.686
||+ Microsoft.Build!Microsoft.Build.Evaluation.ProjectProperty+ProjectPropertyXmlBackedWithPredecessor	13.8	  166,770,416	158,654.063	 0.2	2,584,567.750	107,690.102	        0	     0
|||+ mscorlib!String (Bytes > 1K)                                                                     	12.3	  149,074,112	31,419.730	12.3	149,074,112	31,419.730	        0	     0
|||+ mscorlib!String (Bytes > 10K)                                                                    	 1.2	   14,496,685	1,368.634	 1.2	 14,496,685	1,368.634	        0	     0
|||+ Microsoft.Build!Microsoft.Build.Construction.ProjectPropertyElement                              	 0.0	  543,095.375	18,021.219	 0.0	 23,927.461	747.733	        0	     0
|||+ mscorlib!String                                                                                  	 0.0	   71,937.672	  153.059	 0.0	 71,937.672	153.059	        0	     0

**Comment by nguerrera** [comment] 2018-02-17 05:32
See https://github.com/Microsoft/msbuild/issues/1299

**Comment by rainersigwald** [comment] 2018-02-20 15:52
Duplicate of #1299.

**Closed by rainersigwald** 2018-02-20 15:52 UTC
