### ISSUE TITLE
Inline code tasks do not support latest C# features

### ISSUE THREAD

**Issue by kzu** [Microsoft/msbuild#2311] opened 2017-07-17 17:34 UTC
Even if you use the latest & greatests Tasks.Core.dll, you still get an old-ish C# support for inline tasks. 

Repro:

```
<Project DefaultTargets="Build">

    <Target Name="Build">
        <Dump />
    </Target>

    <UsingTask TaskName="Dump" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildBinPath)\Microsoft.Build.Tasks.Core.dll">
        <Task>
            <Reference Include="Microsoft.Build" />
            <Reference Include="Microsoft.CSharp" />
            <Reference Include="System" />
            <Reference Include="System.Core" />
            <Using Namespace="System" />
            <Using Namespace="System.Linq" />
            <Using Namespace="Microsoft.Build.Framework" />
            <Using Namespace="Microsoft.Build.Utilities" />
            <Code Type="Fragment" Language="cs">
                <![CDATA[
            Log.LogMessage(MessageImportance.High, GetMessage("Foo={0}, Bar={1}", "foo", "bar"));

            string GetMessage(string message, params string[] args)
            {
                return "Message: " + string.Format(message, args);
            }
                ]]>
            </Code>
        </Task>
    </UsingTask>
</Project>
```

This fails, but the generated code builds just fine in MSBuild 15/VS2017: 

```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InlineCode
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Text;
    using System.Linq;
    using System.IO;
    using Microsoft.Build.Framework;
    using Microsoft.Build.Utilities;


    public class Dump : Microsoft.Build.Utilities.Task
    {

        private bool _Success = true;

        public virtual bool Success
        {
            get
            {
                return _Success;
            }
            set
            {
                _Success = value;
            }
        }

        public override bool Execute()
        {

            Log.LogMessage(MessageImportance.High, GetMessage("Foo={0}, Bar={1}", "foo", "bar"));

            string GetMessage(string message, params string[] args)
            {
                return "Message: " + string.Format(message, args);
            }

            return _Success;
        }
    }
}
```

**Comment by rainersigwald** [comment] 2017-07-17 17:47
This is an artifact of implementing `CodeTaskFactory` using the (now) deprecated CodeDOM, which uses an older C# compiler (and thus only supports older versions of the C# language). Changing that is tracked by #304.

Duplicate of #304.

**Closed by rainersigwald** 2017-07-17 17:47 UTC

**Comment by jeffkl** [comment] 2017-09-20 18:11
Try out https://www.nuget.org/packages/RoslynCodeTaskFactory which I just released
