### ISSUE TITLE
Consider adopting repo-wide formatting rules

### ISSUE THREAD

**Issue by Forgind** [microsoft/msbuild#5033] opened 2020-01-06 22:16 UTC
Examples:
Splitting ternary operators across multiple lines
Use of `var` versus type name
Indentation for comments or broken long lines of code
Helpful versus confusing versus unmaintainable comments
When to break a function into helper functions

**Comment by rainersigwald** [comment] 2020-01-06 22:31
Duplicate of #4092

**Closed by rainersigwald** 2020-01-06 22:31 UTC
Labels: Needs Design
