### ISSUE TITLE
MSBuild copying assembly from its own directory

### ISSUE THREAD

**Issue by TonyValenti** [microsoft/msbuild#2555] opened 2017-09-26 13:28 UTC
Hi All,
I think this is an MSBuild bug, but I'm not sure.
Here's my scenario:
Clio.Api.Repository references EntityFrameworkCore 1.1.3 and System.Collections.Immutable version 1.2.2
Clio.Api.Repository.Windows references Clio.Api.Repository and no other assemblies.
Both projects build to the same folder.
I specifically want to point out that EntityFrameworkCore references System.Collections.Immutable version _1.2.1_.

When I build Clio.Api.Repository, the output folder correctly has System.Collections.Immutable version 1.2.2.

When I build Clio.Api.Repository.Windows, the output folder incorrectly has System.Collections.Immutable version 1.2.1.  I had no clue where version 1.2.1 was coming from I didn't have it in my path, my nuget packages, or anywhere.

I turned on verbose debug logging and eventually discovered this:
2>  Dependency "System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
2>      Resolved file path is "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\System.Collections.Immutable.dll".

Why is MSBuild searching for assemblies in its own path when dealing with a dependent assembly?  What can I do to make it stop?

Here is my log:
[Quick Log.txt](https://github.com/Microsoft/msbuild/files/1333294/Quick.Log.txt)

Here is a sample project demonstrating the issue:
https://github.com/TonyValenti/MSBuildResolutionInconsistencies2

**Comment by rainersigwald** [comment] 2020-07-01 16:19
This is happening because Visual Studio adds a pointer to the MSBuild folder to AssemblyFolders. That allows referencing MSBuild assemblies without using the NuGet package.

That's certainly non-obvious, and most of us wish we had a smaller set of assembly-resolution candidate locations. But reducing the set would be a breaking change. #772 tracks creating a simple opt-out of this.

You can remove the `$(AssemblyFoldersConfigFileSearchPath)` entry from `$(AssemblySearchPaths)` manually to work around this problem.

**Comment by rainersigwald** [comment] 2020-07-01 16:19
Duplicate of #772

**Closed by rainersigwald** 2020-07-01 16:19 UTC
