### ISSUE TITLE
Implicit exist condition for imports

### ISSUE THREAD

**Issue by aL3891** [microsoft/msbuild#1452] opened 2016-12-07 21:19 UTC
Right now a lot of times you see something like this

    <Import Project="path\to\foo.targets" Condition="Exists('path\to\foo.targets')" />

But is there a reason not to always have an implicit check if an import exist instead of failing the build if it's not found? Perhaps there should be a log message or something, but not having that exist condition would make things a lot less verbose :)

**Comment by rainersigwald** [comment] 2016-12-07 23:31
I don't think such a check should be the default as you propose. In fact, I think many of the cases that do have this check are wrong, and should cause failures.

A danger of the if-exists check is that in many (most?) cases, the build that happens with chunks of its build logic missing is _wrong_, but there's no obvious way to know that. If you fail to import the props file that sets the `FIX_ALL_BUGS` preprocessor flag, the build might complete without errors but be producing the wrong thing.

I would be more amenable to reducing the verbose and error-prone nature of this check by adding an attribute along the lines of `IfExists="true"`, though. That might also be the best way to do this for #1400.

**Comment by aL3891** [comment] 2016-12-08 10:38
But there are already instances where imports are loaded dynamically with wildcards, is that so different? a nugget restore will place a bunch of targets on disk that are required for the build to work, but not there by default and not checked for,

Having a less verbose `ThrowIfMissing` attribute would be a step in the right direction though.

**Comment by quasarea** [comment] 2018-07-31 13:10
My workaround below:
`    <PropertyGroup>
        <JenskinsTarget>$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))</JenskinsTarget>
    </PropertyGroup>
    <Import Project="$(JenskinsTarget)" Condition="exists('$(JenskinsTarget)')" />`

**Comment by rainersigwald** [comment] 2019-11-04 21:18
Duplicate of #822

**Closed by rainersigwald** 2019-11-04 21:18 UTC
