### ISSUE TITLE
File tracker with clang > 5.0.0 - no write tlog content

### ISSUE THREAD

**Issue by stefan1000** [microsoft/msbuild#4250] opened 2019-03-20 08:31 UTC
Hi,

I'm playing a bit with clang in VS 2019 RC (MSBuild 16.0.450) using android targets as well as my own toolchain stuff. I was trying recent clang versions (6,7,9) but noticed that the file tracker is only working with clang up to version 5. When using newer versions the tracker 'write' file has no contents (resulting in missing up-to-date checks). Anyone knows if this can be fixed on the clang side or is it a file tracker issue ? 

Thanks.

**Comment by rainersigwald** [comment] 2019-03-20 14:30
It could be worked around in clang (by using different win32 APIs to do a file move), but is really a problem in FileTracker. @yuehuang010 has [an internal PR out that will fix this](https://dev.azure.com/devdiv/DevDiv/MSBuild/_git/VS/pullrequest/167576).

This is a duplicate of internal VS bug [806910](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/806910).

**Comment by stefan1000** [comment] 2019-03-28 08:17
Thanks, looking forward to see this (maybe) in 16.1

**Comment by livarcocc** [comment] 2019-05-09 22:27
Closing this issue as the internal PR was merged and the internal bug marked as resolved.

**Closed by livarcocc** 2019-05-09 22:27 UTC
Labels: Tracking
