### ISSUE TITLE
Treat specific warnings as errors

### ISSUE THREAD

**Issue by bitbonk** [microsoft/msbuild#4388] opened 2019-05-21 21:55 UTC
Please add an option to the csproj file that allows me to define only specific warnings to be treated as errors. 

My use case is that I would like to transform a larger code base to be nullable aware. Unfortunately this code base has a lot of other warnings when the solution is built. Those are uncritical and for now.

The solution should not compile as long as there are warning related to nullable types left. 

I suspect that in the months after C# 8 hits the street, a lot code bases will be made nullable aware and a lot of people will be in a similar situation as I am now.

**Comment by bitbonk** [comment] 2019-05-21 21:58
related (just the inverse is requested here): https://github.com/Microsoft/msbuild/issues/3062

**Comment by rainersigwald** [comment] 2019-05-21 22:17
This is possible as of #1928. Set the property `MSBuildWarningsAsErrors` to a semicolon-delimited list of error/warning codes.

**Comment by rainersigwald** [comment] 2019-05-21 22:18
Duplicate of #1886

**Closed by rainersigwald** 2019-05-21 22:18 UTC
