### ISSUE TITLE
Duplicate ProjectReference's breaks cross-targeting frameworks

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/msbuild#3018] opened 2018-02-22 00:58 UTC
_From @natemcmaster on November 8, 2017 1:28_

When there are duplicate ProjectReference's, MSBuild will use the wrong TargetFrameworks value when building P2P references. This used to work in 2.0.0 but started failing in nightly builds of 2.2.0.

**Repro:**
```
Microsoft.AspNetCore.Authentication.Test (netcoreapp2.0;net461) 
   ProjectReferences
   ---> Microsoft.AspNetCore.Authentication.Cookies  (netstandard2.0)
   ---> Microsoft.AspNetCore.Authentication.Facebook  (netstandard2.0)
   ---> Microsoft.AspNetCore.Authentication.Google  (netstandard2.0)
   ---> Microsoft.AspNetCore.Authentication.JwtBearer  (netstandard2.0)
   ---> Microsoft.AspNetCore.Authentication.MicrosoftAccount  (netstandard2.0)
   ---> Microsoft.AspNetCore.Authentication.OpenIdConnect  (netstandard2.0)
   ---> Microsoft.AspNetCore.Authentication.MicrosoftAccount  (netstandard2.0)  (DUPLICATE)
   ---> Microsoft.AspNetCore.Authentication.JwtBearer  (netstandard2.0) (DUPLICATE)
   ---> Microsoft.AspNetCore.Authentication.Twitter  (netstandard2.0)
```

1. Install nightly build of the CLI: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.2.0-preview1-007522/dotnet-sdk-2.2.0-preview1-007522-win-x64.zip
1. `git clone https://github.com/aspnet/Security`
2. `git checkout 72e1cb1385c982e6dba90c839d1a1455e2813e6c`
3. `cd Security/test/Microsoft.AspNetCore.Authentication.Test`
4. `dotnet restore`
5. `dotnet build --no-restore`

**Expected**
Microsoft.AspNetCore.Authentication.MicrosoftAccount and Microsoft.AspNetCore.Authentication.JwtBearer should be built using TargetFramework=netstandard2.0

Or, produce an error about duplicate ProjectReferences are ignored or produce some kind of warning.

**Actual**
MSBuild attempts to compile Microsoft.AspNetCore.Authentication.MicrosoftAccount and Microsoft.AspNetCore.Authentication.JwtBearer  with both net461 and netcoreapp2.0.

```
C:\Users\namc\.dotnet\x64\sdk\2.2.0-preview1-007460\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\dev\aspnet\Universe21\modules\Security\src\Microsoft.AspNetCore.Authentication.MicrosoftAccount\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project. [C:\dev\aspnet\Universe21\modules\Security\src\Microsoft.AspNetCore.Authentication.MicrosoftAccount\Microsoft.AspNetCore.Authentication.MicrosoftAccount.csproj]
C:\Users\namc\.dotnet\x64\sdk\2.2.0-preview1-007460\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\dev\aspnet\Universe21\modules\Security\src\Microsoft.AspNetCore.Authentication.JwtBearer\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project. [C:\dev\aspnet\Universe21\modules\Security\src\Microsoft.AspNetCore.Authentication.JwtBearer\Microsoft.AspNetCore.Authentication.JwtBearer.csproj]
C:\Users\namc\.dotnet\x64\sdk\2.2.0-preview1-007460\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\dev\aspnet\Universe21\modules\Security\src\Microsoft.AspNetCore.Authentication.MicrosoftAccount\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. [C:\dev\aspnet\Universe21\modules\Security\src\Microsoft.AspNetCore.Authentication.MicrosoftAccount\Microsoft.AspNetCore.Authentication.MicrosoftAccount.csproj]
C:\Users\namc\.dotnet\x64\sdk\2.2.0-preview1-007460\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\dev\aspnet\Universe21\modules\Security\src\Microsoft.AspNetCore.Authentication.JwtBearer\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. [C:\dev\aspnet\Universe21\modules\Security\src\Microsoft.AspNetCore.Authentication.JwtBearer\Microsoft.AspNetCore.Authentication.JwtBearer.csproj]
```

**Details**

[Microsoft.AspNetCore.Authentication.Test.csproj](https://github.com/aspnet/Security/blob/72e1cb1385c982e6dba90c839d1a1455e2813e6c/test/Microsoft.AspNetCore.Authentication.Test/Microsoft.AspNetCore.Authentication.Test.csproj)
[Microsoft.AspNetCore.Authentication.MicrosoftAccount.csproj](https://github.com/aspnet/Security/blob/72e1cb1385c982e6dba90c839d1a1455e2813e6c/src/Microsoft.AspNetCore.Authentication.MicrosoftAccount/Microsoft.AspNetCore.Authentication.MicrosoftAccount.csproj)
[Microsoft.AspNetCore.Authentication.JwtBearer.csproj](https://github.com/aspnet/Security/blob/72e1cb1385c982e6dba90c839d1a1455e2813e6c/src/Microsoft.AspNetCore.Authentication.JwtBearer/Microsoft.AspNetCore.Authentication.JwtBearer.csproj)

Build log: [msbuild.binlog.zip](https://github.com/dotnet/sdk/files/1452260/msbuild.binlog.zip)

_Copied from original issue: dotnet/sdk#1716_

**Comment by dsplaisted** [comment] 2018-02-22 00:59
We believe this regressed when we did the fix for duplicate evaluation of project references.

**Comment by rainersigwald** [comment] 2018-02-22 15:41
Duplicate of #2688.

Looking at these projects, it looks like the duplication is a project-authoring error. Is it something that you need to support, or would an error about the duplication be ok? (Not defending the current behavior, trying to figure out how well we need to fix it.)

**Closed by rainersigwald** 2018-02-22 15:41 UTC

**Comment by natemcmaster** [comment] 2018-02-22 16:02
Definitely a project authoring error which is easy to fix, but the error message produced is misleading. I was expecting a warning or an error indicating the real issue was duplicated project references.
