### ISSUE TITLE
MSBuild Failed to build Due to culture 'en-pk'

### ISSUE THREAD

**Issue by zeeshanumar** [microsoft/msbuild#4632] opened 2019-08-19 10:13 UTC
I was building a project in Vb.Net and encountered this error in VS 2015 (.NET 3.5):

`error MSB4217: Task host node exited prematurely. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.`

on Investigation i have found that it was being caused by culture name `en-pk`. 

```
UNHANDLED EXCEPTIONS FROM PROCESS 15136:
=====================
8/19/2019 3:01:06 PM
System.ArgumentException: Culture name 'en-pk' is not supported.
Parameter name: name
   at System.Globalization.CultureTableRecord..ctor(String cultureName, Boolean useUserOverride)
   at System.Globalization.CultureTableRecord.GetCultureTableRecord(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketReadTranslator.TranslateCulture(CultureInfo& value)
   at Microsoft.Build.BackEnd.TaskHostConfiguration.Translate(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.TaskHostConfiguration.FactoryForDeserialization(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc()
===================
```

After changing culture name to `en-us` the issue was fixed and build was successful.

I haven't got any proper message in Visual Studio console . Kindly add proper logging for this.

Thanks

**Comment by rainersigwald** [comment] 2019-08-19 15:19
This should be improved by microsoft/msbuild#3632, but ideally we wouldn't crash at all in this culture situation.

**Comment by rainersigwald** [comment] 2019-09-23 20:43
Team triage: @Forgind can you look at improving this from a build crash to an explicit build failure?

**Comment by Forgind** [comment] 2019-10-07 17:26
Looking at line 560 of NodeEndpointOutOfProcBase.cs (under src/Shared), I think the exception is being caught, but the current logging mechanism tries to use the current culture information in logging the error, creating another exception. The difficulty is that if you want to display a localized error message, you need to know the culture, and if the culture doesn't exist...the error propagates.

https://github.com/microsoft/msbuild/compare/master...Forgind:en-pk-bug
is not an ideal solution because it doesn't clearly identify the problem, but the best alternative I currently see is to have it default to en-us, printing an error message in English for everyone and ignoring localization.

**Comment by livarcocc** [comment] 2019-10-07 21:00
Falling back to English seems fine to me.

**Comment by Forgind** [comment] 2019-10-10 21:27
Hi @zeeshanumar,

We think we have a solution to the problem, but I'm having trouble verifying that it works, partially since I'm not a VB expert, and the simple program I wrote in VB targeting .NET 3.5 built. Would you mind sharing more details around what I should do to reproduce the problem? Thank you!

**Comment by zeeshanumar** [comment] 2019-10-11 06:34
Hi @Forgind,
You need to change you culture to en-pk to reproduce this issue. You can do it by changing you preferred language to English Pakistan. Let me know if you have trouble reproducing this issue after changing you culture to en-pk.
Thanks

**Comment by Forgind** [comment] 2019-10-14 21:22
I should have mentioned how I previously tried to reproduce the error—sorry about that. I changed the language to en-pk and created a "Hello World" project in VB, but that built successfully. I also tried building a more complicated project with multiple libraries in C#, but that also built successfully. Do you have any suggestions as to what I should change? Thank you!

**Comment by livarcocc** [comment] 2019-10-24 17:19
Closing this issue as we couldn't repro it.

@zeeshanumar if you can provide the additional information we request above, we can re-activate and continue to investigate.

**Closed by livarcocc** 2019-10-24 17:19 UTC
Labels: Area: Debuggability, Area: Engine
