### ISSUE TITLE
CSC : error CS0006: Metadata file 

### ISSUE THREAD

**Issue by SravanthiDondapati** [microsoft/msbuild#4436] opened 2019-06-13 09:06 UTC
### I have developed API using .Net Core 2.1 using Visual Studio 2017 and build is successful. But, when I try to build the solution using command line statements i.e.
**"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" /t:Restore "encompassapi.sln"
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" /target:Clean,Build /property:Configuration=Release,VisualStudioVersion=15.0 "encompassapi.sln"**
I get this error **"CSC : error CS0006: Metadata file"**

I have read many posts related to this error but could not fix the issue. Executing this command line is mandatory for me because this is part of DevOps pipeline using Jenkins. Please pour in some solution to fix this issue.

**Comment by livarcocc** [comment] 2019-06-13 17:31
I am not sure why this would be happening. Could you provide us with a binlog following the guidelines here: https://gist.github.com/dsplaisted/b256d7804672a6f6375476a5f5658b7b.

On a separate note, you could try to run this command as follows:

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" /restore /target:Clean,Build /property:Configuration=Release,VisualStudioVersion=15.0 "encompassapi.sln"
```

Lastly, why do you need to specify the full path to msbuild here?

**Comment by livarcocc** [comment] 2019-06-25 15:44
Closing for the lack of additional info we need and also because I could not reproduce this issue.

**Closed by livarcocc** 2019-06-25 15:44 UTC
