### ISSUE TITLE
Targets files don't have a file association/icon

### ISSUE THREAD

**Issue by onovotny** [microsoft/msbuild#4180] opened 2019-02-15 18:11 UTC
Looking at props/targets files, the former has a file association with VS, along with an icon, while targets is missing and lonely 😊
 
 
![image](https://user-images.githubusercontent.com/1427284/52875811-430c3280-3123-11e9-8a8c-89c49556b3b7.png)

The description is a TARGETS file, as it’s not a registered file type.
 
It’s a small thing, but can VS add something for this?

**Comment by rainersigwald** [comment] 2019-02-27 22:51
Sounds reasonable to me. I believe this is controlled by (internal link) [this setup manifest](https://dev.azure.com/devdiv/DevDiv/_git/VS?path=%2Fsrc%2FSetupPackages%2FCoreIde%2FCommunity%2Fres%2FFileAssociations%2Fext.vcxproj.swr&version=GTrelease%2Fvs%2F16.0-preview.4&line=44&lineStyle=plain&lineEnd=47&lineStartColumn=1&lineEndColumn=76).

**Comment by rainersigwald** [comment] 2019-09-19 14:19
Marking this as a duplicate even though the other bug is newer because @davkean is doing this.

**Comment by rainersigwald** [comment] 2019-09-19 14:20
Duplicate of https://github.com/dotnet/project-system/issues/5088

**Closed by rainersigwald** 2019-09-19 14:20 UTC

**Comment by davkean** [comment] 2019-10-16 05:19
@onovotny This has been done for 16.4:

![image](https://user-images.githubusercontent.com/1103906/66890112-a04ce080-f030-11e9-997b-5e25d0a00ccd.png)
