### ISSUE TITLE
CreateCSharpManifestResourceName failed to create a manifest resource name

### ISSUE THREAD

**Issue by lextm** [microsoft/msbuild#4749] opened 2019-09-19 17:06 UTC
### Steps to reproduce
Attached a rather simple project.
[WindowsFormsCore.zip](https://github.com/microsoft/msbuild/files/3632415/WindowsFormsCore.zip)

### Expected  behavior
Compile the project should be successful.

### Actual behavior
Compilation failed with,

C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(100,9): error MSB3041: Unable to create a manifest resource name for "Test\Form1.resx". Could not find a part of the path 'C:\Users\lextm\source\repos\WindowsFormsCore\WindowsFormsCore\Test\Test\Form1.cs'.

### Environment data
It started to happen in .NET Core 3.0 SDK Preview 9 (RC1 still has this issue).

.NET Core 3.0 SDK Preview 8 and earlier seem to be OK.

### Workaround
Move all files of Form1 to the root directory of that project, and the compilation error disappears. However, many existing projects should already have such folders to organize their forms/user controls, so applying this workaround will be painful.

**Comment by rainersigwald** [comment] 2019-09-19 17:07
Thanks for the report. This should be fixed in the latest rc2 builds and in the final release.

**Comment by rainersigwald** [comment] 2019-09-19 17:07
Duplicate of #4695

**Closed by rainersigwald** 2019-09-19 17:07 UTC

**Comment by lextm** [comment] 2019-09-19 17:10
@rainersigwald Great.
