### ISSUE TITLE
Calculating code metrics through MSBuild does not work

### ISSUE THREAD

**Issue by gremlm** [microsoft/msbuild#4608] opened 2019-08-12 22:25 UTC
For calculating code metrics I have included Microsoft.CodeAnalysis.Metrics 2.9.4 nuget package to my csproj project.
Before executing msbuild from the command line, I have called "nuget.exe restore", and it correctly found MSBuild and restore package:

> "MSBuild auto-detection: using msbuild version '16.200.19.32702' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin'.
> Restoring NuGet package Microsoft.CodeAnalysis.Metrics.2.9.4. ..."

Then, from command line I am calling msbuild with /t:Metrics option:

> "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\MSBuild.exe" /p:Configuration=Debug /t:Metrics My.sln "

which ended with following error:

> "Unhandled Exception: System.ArgumentException: Directory "C:\Program Files (x86)\Microsoft Visual Studio\2019\TestAgent\MSBuild\Current\Bin" does not exist
> Parameter name: msbuildPath
> at Microsoft.Build.Locator.MSBuildLocator.RegisterMSBuildPath(String msbuildPath)
> at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
> at Metrics.Program.d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)"

It looks like Metrics.exe was started from msbuild itself and can't find it location, but nuget.exe did?

**Comment by rainersigwald** [comment] 2019-08-12 22:36
MSBuildLocator was the right place to file this. If you'd like the Metrics folks to look into a workaround on their side, I believe the right repo is https://github.com/dotnet/roslyn-analyzers.

**Comment by rainersigwald** [comment] 2019-08-12 22:36
Duplicate of microsoft/MSBuildLocator#73

**Closed by rainersigwald** 2019-08-12 22:36 UTC
