### ISSUE TITLE
CopyLocal setting not used

### ISSUE THREAD

**Issue by AndyGerlicher** [microsoft/msbuild#461] opened 2016-02-02 22:17 UTC
This is related to #24.

Consider the following project setup.

Project A - References Project B
Project B - References Common.dll
Common.dll is in the GAC

When building ProjectA, [RAR](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/AssemblyDependency/ResolveAssemblyReference.cs) will resolve all assemblies and their dependencies and copy them to the output path when `CopyLocal` is found to be `True`. Before #24, the presence of any DLL in the GAC would set `CopyLocal` to `False` unless otherwise specified in the project file. After #24, it would only set it to `False` if the assembly was resolved _only_ from the GAC (no `HintPath`, etc.). If it was resolved locally  `CopyLocal` would be `True`. Among other reasons, this was intended to make builds more deterministic and less reliant on machine GAC state.

From Project A to B there is no issue. The `CopyLocal` setting (`Private` tag in A.csproj) is honored. However, when building Project A, Common.dll will be resolved as a dependency and treated as a DLL (project data from B.csproj not read). Therefore, setting the `CopyLocal` flag in B.csproj will have no affect on the [CopyLocal algorithm](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/AssemblyDependency/Reference.cs#L1158) when building Project A. This issue is not caused by #24, but with that change assemblies that would typically be in the GAC that you may not want in your build will be included in the output. The only workaround would be to turn off #24 or include C.dll as a reference of Project A and set `CopyLocal` to `false` there.

The fix seems to be to read metadata from B.csproj and honor the `CopyLocal` flag when building A. Since RAR is not implemented in this way currently, this change would likely be fairly involved and a high potential for regression.

**Comment by avezenkov** [comment] 2016-02-03 11:00
[Here](https://onedrive.live.com/redir?resid=BBE231AE0B2B8660!4015&authkey=!ALZtZGb10BBEmLA&ithint=file%2czip) is a demo project.

**Comment by pedrofernandesfilho** [comment] 2017-01-13 10:17
I had a production environment stopped because of it. :-(

**Comment by rainersigwald** [comment] 2019-11-18 21:43
Team triage: hasn't seen much traffic in almost 4 years, very high risk of regression. Closing as won't-fix.

**Closed by rainersigwald** 2019-11-18 21:43 UTC

**Comment by isc30** [comment] 2020-05-20 08:42
This is breaking the blazor boot when trying to exclude an assembly from the initial load by using `<Private>false</Private>` because it doesn't propagate to all sub-references.
