### ISSUE TITLE
build/pack does not including resources.dll files

### ISSUE THREAD

**Issue by jorisdebock** [Microsoft/msbuild#2078] opened 2017-05-09 09:05 UTC
I have a .netstandard1.0 class library with the following in the .csproj file. When I try to create a nuget package with either the pack command or the build command (GeneratePackageOnBuild=True). The generated nupkg file does not include the localized resource dlls.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.0</TargetFramework>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Description>description</Description>
    <Version>1.0.0</Version>
    <PackageId>test</PackageId>
    <Authors>authors</Authors>
    <Company>company</Company>
    <Product />
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Update="Translations.en.resx" />
  </ItemGroup>
</Project>
```

### Commands used
dotnet pack -c release
dotnet build -c release
dotnet msbuild /t:pack /p:configuration=release
dotnet msbuild /t:build /p:configuration=release

### Info
```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

Microsoft (R) Build Engine version 15.1.1012.6693
```
```
       CopyFilesToOutputDirectory:
         Copying file from "obj\release\netstandard1.0\Translations.dll" to "bin\release\netstandard1.0\Translations.dll".
         Translations -> ...\Translations\bin\release\netstandard1.0\Translations.dll
         Copying file from "obj\release\netstandard1.0\Translations.pdb" to "bin\release\netstandard1.0\Translations.pdb".
         Copying file from "obj\release\netstandard1.0\en\Translations.resources.dll" to "bin\release\netstandard1.0\en\Translations.resources.dll".
       GenerateNuspec:
         Successfully created package '...\Translations\bin\release\Translations.1.0.0.nupkg'.
```

## Expected behavior

lib\netstandard1.0\Translations.dll
lib\netstandard1.0\en\Translations.resources.dll

## Actual behavior

lib\netstandard1.0\Translations.dll

**Comment by rainersigwald** [comment] 2017-05-09 15:40
I believe this is a duplicate of https://github.com/NuGet/Home/issues/4698, which is supposed to be fixed for the upcoming 15.3 update.

**Closed by rainersigwald** 2017-05-09 15:40 UTC
