### ISSUE TITLE
Documentation: Exists silently un-escapes arguments

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#1184] opened 2016-10-12 00:50 UTC
`FunctionCallExpressionNode` represents the AST node for property functions inside msbuild conditions.

The [hardcoded special logic](https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/Conditionals/FunctionCallExpressionNode.cs#L36) for the `Exists` method calls into `ExpandArgumentForScalarParameter` which expands the argument [as if it were a task item](https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/Conditionals/FunctionCallExpressionNode.cs#L116).

[TaskItem](https://github.com/Microsoft/msbuild/blob/master/src/Build/Instance/ProjectItemInstance.cs#L726) represents items passed into tasks. A TaskItem unconditionally unescapes its strings. This kind of makes sense, since tasks should see unescaped data.

However, it seems a bit weird to interpret all arguments passed to the `Exists`property function as TaskItems.

One outcome out of this, is that in the following snippet:

``` xml
<PropertyGroup>
   <p1>123%40.cs</p1>
   <p2 Condition="Exists($(p1))">condition was true</p2>
</PropertyGroup>
```

The condition will apply to `123@.cs` and not to `123%40.cs` because [TaskItem unescapes it under the covers](https://github.com/Microsoft/msbuild/blob/master/src/Build/Instance/ProjectItemInstance.cs#L877). 

Is this a bug or a feature? If it's a feature, the code that implements it is doing so by using the hidden side-effect of TaskItems (an object meant to represent items sent to tasks) rather than by clearly expressing the intent to unescape arguments to `Exists`.

**Comment by AndyGerlicher** [comment] 2017-05-09 22:47
Team Triage:
Closing issue, behavior by design.

**Closed by AndyGerlicher** 2017-05-09 22:47 UTC
Labels: Feature - Escaping
