### ISSUE TITLE
		For .net core xunit projects, dotnet xunit failed with the error MSB1025: An internal failure occurred while running MSBuild

### ISSUE THREAD

**Issue by YunWeiaa** [Microsoft/msbuild#3346] opened 2018-05-25 02:57 UTC
# **Steps to reproduce**
1. Create a new .net core xunit project via CLI, 
2. dotnet restore, build and test 
3. dotnet xunit 
# **Expected behavior**
dotnet xunit succeeded with no errors or warnings
# **Actual behavior**
Dotnet xunit failed with following info:
![dotnetxunitfailed](https://user-images.githubusercontent.com/33921754/40523554-b9efceee-6008-11e8-8079-5dfe9fddf5e3.PNG)
# **Environment data**
install d15.8stg/27723.3000 (15.8 Preview 3) + CLI/SDK [2.1.400-preview-008934](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.1.4xx/dotnet-sdk-latest-win-x86.exe) (x86) on Win 7 x86
**dotnet --info**:
![dotnetinfo](https://user-images.githubusercontent.com/33921754/40523691-7864d536-6009-11e8-9a94-d76ae85be485.PNG)
Note: 
1. Not repro on **D15.8/27723.00** and **D15.8stg/27723.3000** (In VS)
2. Only Repro in the .NET Core SDK (under the master branch https://github.com/dotnet/cli/tree/master)

**Comment by rainersigwald** [comment] 2018-05-25 15:26
This is expected to be fixed by https://github.com/dotnet/cli/pull/9344. Please let us know if it happens in a build with that commit.

**Comment by rainersigwald** [comment] 2018-05-25 15:27
Duplicate of #3317

**Comment by YunWeiaa** [comment] 2018-06-01 10:06
Regression on **D15.8stg/27731.3003** (15.8 Preview 3) + CLI/SDK [**2.2.100-preview1-008957** ](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe)

**Comment by rainersigwald** [comment] 2018-06-01 14:42
https://github.com/dotnet/cli/pull/9398 should fix again.

**Comment by YunWeiaa** [comment] 2018-06-04 07:56
Repro on **D15.8stg/27802.3000** (15.8 Preview 3) + CLI/SDK [**2.2.100-preview1-008958**](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x86.exe)

**Closed** 2019-04-18 08:06 UTC
