### ISSUE TITLE
"SGEN:SGEN(0,0): Error : An attempt was made to load..." in release build only

### ISSUE THREAD

**Issue by ifle** [Microsoft/msbuild#2796] opened 2017-12-10 09:52 UTC
Something strange. I have following error on release build only. 
In the debug build all is ok. 
This is summary from Team Services build.
How can to determine what is wrong?

```
Ran for 7.7 minutes (Hosted VS2017), completed at Sun 12/10/2017 09:44 AM

Request Summary
Request 12	Completed
Summary
| Finalize build
0 error(s), 0 warning(s)
| Phase 1
2 error(s), 123 warning(s)
Phase 1 - 2 error(s), 123 warning(s)
SGEN:SGEN(0,0): Error : An attempt was made to load an assembly with an incorrect format: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\ref\netfx.force.conflicts.dll.
Process 'msbuild.exe' exited with code '1'.

```

**Comment by aolszowka** [comment] 2017-12-22 17:06
Maybe #2707 ?

**Comment by rainersigwald** [comment] 2017-12-22 17:19
I think so, @aolszowka -- thanks.

Duplicate of #2707.

@ifle If the workarounds in that issue don't help, can you post some more details in that issue, please?

**Closed by rainersigwald** 2017-12-22 17:19 UTC
