### ISSUE TITLE
Msbuild 15.0 cannot build Coded UI test project from normal command prompt.

### ISSUE THREAD

**Issue by acesiddhu** [Microsoft/msbuild#2117] opened 2017-05-22 08:53 UTC
With msbuild 15.0 we are seeing that coded ui test projects doesn’t build if we use a normal command prompt. This used to work with msbuild 14.0.

Here is a repro

1)	Unzip attached coded ui test zip on local machine
[CodedUITestProject2.zip](https://github.com/Microsoft/msbuild/files/1018201/CodedUITestProject2.zip)

2)	Run c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe " CodedUITestProject2.sln"  or codeduitestproject.csproj (use normal command prompt and not developer command prompt)

Ideally the project should have been build. We tried same steps with msbuild 14 and it works fine

After investigation we saw that the csproj takes a dependency for “VisualStudioVersion”. We see that this value is null when building with msbuild 15.0. Other point to note is that .sln defines “VisualStudioVersion = 15.0.26228.9”. shouldn’t this just work?

**Comment by stffabi** [comment] 2017-06-20 13:55
We are seeing exactly the same problem. Setting VisualStudioVersion property to `15.0` in the msbuild call seems to fix the problem. It seems like for normal csproj or vbproj projects the VisualStudioVersion get's set through the `Microsoft.Common.props`. This is normally imported as first project in csproj or vbproj files by:  `<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />`

Unfortunately our csproj which contains the codedui test code doesn't have this imported. Also creating a new coded ui projcts from the "Add Project Wizard" doesn't add this import.

Does someon know if this is a bug in the template für coded ui test projects? Importing the `Microsoft.Common.props` for coded ui test projects seems to fix the problem. But I have no clue if this breaks something else.

**Comment by stffabi** [comment] 2017-06-20 14:01
@rainersigwald do you know if it would be safe to import `Microsoft.Common.props` for coded ui projects?

**Comment by acesiddhu** [comment] 2017-06-26 13:18
@stffabi you can add the import. it wont have any issues.

**Comment by rainersigwald** [comment] 2017-07-07 16:20
This is a duplicate of #1678 but has more detailed information, so I'm going to leave both open for now.

**Comment by rainersigwald** [comment] 2017-07-19 16:26
Fixed by #2258.

**Closed by rainersigwald** 2017-07-19 16:26 UTC

**Comment by mgolois** [comment] 2017-08-08 19:06
When will this be released?

**Comment by rainersigwald** [comment] 2017-08-08 19:08
@mgolois It's in our `master` branch, which is targeted at the next "big" update of Visual Studio 2017. No release date has been announced for that yet.

**Comment by mgolois** [comment] 2017-08-08 19:37
so any temporary workaround other than using Developer Command Prompt for 2017?

**Comment by rainersigwald** [comment] 2017-08-08 19:45
## Workarounds

* Build inside a Developer Command Prompt for VS 2017.
* Import `Microsoft.Common.props` at the top of your projects https://github.com/Microsoft/msbuild/issues/2117#issuecomment-311056514.
* Set the `VisualStudioVersion` property in the MSBuild invocation https://github.com/Microsoft/msbuild/issues/2117#issuecomment-309761170.

**Comment by mgolois** [comment] 2017-08-08 19:48
@rainersigwald Thank you!

**Comment by mgolois** [comment] 2017-08-08 20:23
@rainersigwald ,  sorry, I was able to use the command Prompt VS2017 and the VisualStudioVersion property,
but I was unable to import Microsoft.Common.props 
I put this at the top of my proj file:
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

I got this error:

: error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\4.0\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by reemuluzumaki** [comment] 2017-08-10 15:59
I am running VS Studio 2015 with MS Build 14.0 . I am successfully building my CodedUI project through MSBuild, but when trying to add my test with TCM so that they can be accessed by MTM, it says 'no tests were found', However when I build the .dll using Visual Studio, TCM can find the Tests. Are there some flags in the build command that are missing?
