### ISSUE TITLE
Csc compilation error output is not written to MSBuild output

### ISSUE THREAD

**Issue by halter73** [Microsoft/msbuild#2872] opened 2018-01-17 23:38 UTC
### Steps to reproduce

1. Install the dotnet sdk and runtime on Linux.

2. Create a dotnet core application.

    I used the Kestrel.Transport.Libuv.Tests project from the [KestrelHttpServer repo](https://github.com/aspnet/KestrelHttpServer).

3. Introduce a compilation error in the application.

### Expected  behavior

The reason for the compilation failure should be written to stdout or stderr. Instead, this is only available through binary logs which I had to copy to a Windows machine to look at using the structured log viewer http://msbuildlog.com/.

Even then, the actual compilation errors weren't in an "Errors" section of the binary logs like I would expect, but it's under a section labled "Microsoft (R) Visual C# Compiler version 2.7.0.62419 (34563958)" which is just the first line of csc output.

![image](https://user-images.githubusercontent.com/54385/35073049-11cc4bf0-fb9c-11e7-9a4f-1795cead4285.png)

### Actual behavior

MSBuild simply shows that csc exited with a non-zero status code.

```
shalter@f4-linux-server:~/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests$ dotnet msbuild
Microsoft (R) Build Engine version 15.6.22.57775 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Protocols.Abstractions -> /home/shalter/aspnet/KestrelHttpServer/src/Protocols.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Protocols.Abstractions.dll
  Kestrel.Transport.Abstractions -> /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Transport.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
  Kestrel.Core -> /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Core/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll
  Kestrel.Core -> /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Core/bin/Debug/netcoreapp2.1/Microsoft.AspNetCore.Server.Kestrel.Core.dll
  Kestrel.Transport.Libuv -> /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Transport.Libuv/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll
/home/shalter/.dotnet/sdk/2.2.0-preview1-007866/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/shalter/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
/home/shalter/.dotnet/sdk/2.2.0-preview1-007866/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/shalter/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
shalter@f4-linux-server:~/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests$ 
```

### Environment data

`msbuild /version` output:

```
shalter@f4-linux-server:~/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests$ dotnet msbuild /version
Microsoft (R) Build Engine version 15.6.22.57775 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.6.22.57775
```

OS info:

I repro'd on Ubuntu 16.04.3 LTS and installed dotnet into my home directory using the `build.sh` script from one of the ASP.NET Core repos.

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

```
shalter@f4-linux-server:~/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests$ dotnet --version
2.2.0-preview1-007866
```

**Comment by halter73** [comment] 2018-01-18 00:47
So not every compilation error seems to reproduce this behavior, so here are some more details on the type of compilation error that does.

1. Take [commit f4d27e67bb](https://github.com/aspnet/KestrelHttpServer/commits/f4d27e67bbe770b0290f1a08c2e3401bae8686f0) from the Kestrel repo and build it once on linux using `build.sh /t:Compile`. This should complete successfully.
2. Navigate to the KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests directory and verify that `~/.dotnet/dotnet msbuild` also completes successfully.
3. Take the following diff and and apply it. E.g. `git apply mypatchfile.patch`
```diff
diff --git a/test/Kestrel.Transport.Libuv.Tests/LibuvOutputConsumerTests.cs b/test/Kestrel.Transport.Libuv.Tests/LibuvOutputConsumerTests.cs
index 06576890..81213042 100644
--- a/test/Kestrel.Transport.Libuv.Tests/LibuvOutputConsumerTests.cs
+++ b/test/Kestrel.Transport.Libuv.Tests/LibuvOutputConsumerTests.cs
@@ -412,8 +412,8 @@ public void Dispose()
             });
         }
 
-        [Theory]
-        [MemberData(nameof(PositiveMaxResponseBufferSizeData))]
+        //[Theory]
+        //[MemberData(nameof(PositiveMaxResponseBufferSizeData))]
         public async Task CancelsBeforeWriteRequestCompletes(int maxResponseBufferSize)
         {
             await Task.Run(async () =>
@@ -496,8 +496,8 @@ public void Dispose()
             });
         }
 
-        [Theory]
-        [MemberData(nameof(PositiveMaxResponseBufferSizeData))]
+        //[Theory]
+        //[MemberData(nameof(PositiveMaxResponseBufferSizeData))]
         public async Task WriteAsyncWithTokenAfterCallWithoutIsCancelled(int maxResponseBufferSize)
         {
             await Task.Run(async () =>
@@ -582,8 +582,8 @@ public void Dispose()
             });
         }
 
-        [Theory]
-        [MemberData(nameof(PositiveMaxResponseBufferSizeData))]
+        //[Theory]
+        //[MemberData(nameof(PositiveMaxResponseBufferSizeData))]
         public async Task WritesDontGetCompletedTooQuickly(int maxResponseBufferSize)
         {
             var completeQueue = new ConcurrentQueue<Action<int>>();
@@ -639,8 +639,8 @@ public void Dispose()
             }
         }
 
-        [Theory]
-        [MemberData(nameof(MaxResponseBufferSizeData))]
+        //[Theory]
+        //[MemberData(nameof(MaxResponseBufferSizeData))]
         public async Task WritesAreAggregated(long? maxResponseBufferSize)
         {
             var writeCalled = false;

```
4. Ensure you're still in the KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests directory and verify that `~/.dotnet/dotnet msbuild` now completes with the following nondescript error.

```
shalter@f4-linux-server:~/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests$ ~/.dotnet/dotnet msbuild
Microsoft (R) Build Engine version 15.6.22.57775 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Protocols.Abstractions -> /home/shalter/aspnet/KestrelHttpServer/src/Protocols.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Protocols.Abstractions.dll
  Kestrel.Transport.Abstractions -> /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Transport.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
  Kestrel.Core -> /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Core/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll
  Kestrel.Core -> /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Core/bin/Debug/netcoreapp2.1/Microsoft.AspNetCore.Server.Kestrel.Core.dll
  Kestrel.Transport.Libuv -> /home/shalter/aspnet/KestrelHttpServer/src/Kestrel.Transport.Libuv/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll
/home/shalter/.dotnet/sdk/2.2.0-preview1-007866/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/shalter/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
/home/shalter/.dotnet/sdk/2.2.0-preview1-007866/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/shalter/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
``` 

The output should actually look more like this (taken from macOS):
```
shalter@halter73-mbp Kestrel.Transport.Libuv.Tests (dev*$% u=)$ ~/.dotnet/dotnet msbuild
Microsoft (R) Build Engine version 15.6.22.57775 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Protocols.Abstractions -> /Users/shalter/source/aspnet/KestrelHttpServer/src/Protocols.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Protocols.Abstractions.dll
  Kestrel.Transport.Abstractions -> /Users/shalter/source/aspnet/KestrelHttpServer/src/Kestrel.Transport.Abstractions/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
  Kestrel.Core -> /Users/shalter/source/aspnet/KestrelHttpServer/src/Kestrel.Core/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll
  Kestrel.Core -> /Users/shalter/source/aspnet/KestrelHttpServer/src/Kestrel.Core/bin/Debug/netcoreapp2.1/Microsoft.AspNetCore.Server.Kestrel.Core.dll
  Kestrel.Transport.Libuv -> /Users/shalter/source/aspnet/KestrelHttpServer/src/Kestrel.Transport.Libuv/bin/Debug/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll
LibuvOutputConsumerTests.cs(417,27): error xUnit1013: Public method 'CancelsBeforeWriteRequestCompletes' on test class 'LibuvOutputConsumerTests' should be marked as a Theory. [/Users/shalter/source/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
LibuvOutputConsumerTests.cs(501,27): error xUnit1013: Public method 'WriteAsyncWithTokenAfterCallWithoutIsCancelled' on test class 'LibuvOutputConsumerTests' should be marked as a Theory. [/Users/shalter/source/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
LibuvOutputConsumerTests.cs(587,27): error xUnit1013: Public method 'WritesDontGetCompletedTooQuickly' on test class 'LibuvOutputConsumerTests' should be marked as a Theory. [/Users/shalter/source/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
LibuvOutputConsumerTests.cs(644,27): error xUnit1013: Public method 'WritesAreAggregated' on test class 'LibuvOutputConsumerTests' should be marked as a Theory. [/Users/shalter/source/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
LibuvOutputConsumerTests.cs(417,27): error xUnit1013: Public method 'CancelsBeforeWriteRequestCompletes' on test class 'LibuvOutputConsumerTests' should be marked as a Theory. [/Users/shalter/source/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
LibuvOutputConsumerTests.cs(501,27): error xUnit1013: Public method 'WriteAsyncWithTokenAfterCallWithoutIsCancelled' on test class 'LibuvOutputConsumerTests' should be marked as a Theory. [/Users/shalter/source/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
LibuvOutputConsumerTests.cs(587,27): error xUnit1013: Public method 'WritesDontGetCompletedTooQuickly' on test class 'LibuvOutputConsumerTests' should be marked as a Theory. [/Users/shalter/source/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
LibuvOutputConsumerTests.cs(644,27): error xUnit1013: Public method 'WritesAreAggregated' on test class 'LibuvOutputConsumerTests' should be marked as a Theory. [/Users/shalter/source/aspnet/KestrelHttpServer/test/Kestrel.Transport.Libuv.Tests/Kestrel.Transport.Libuv.Tests.csproj]
```

**Comment by kasper3** [comment] 2018-01-18 21:33
Are there smaller steps to repro this? Like create a console app `donte new console -n test` and run `dotnet msbuild test/test.csproj` and find no error in output?

**Comment by halter73** [comment] 2018-01-18 22:56
I'm sure there are smaller steps to repro, but I haven't found them. If I do find a simpler repro, I'll post it here.

**Comment by halter73** [comment] 2018-02-10 01:07
@kasper3 I now have a simpler repro. I found this bug occurs on macOS as well, but I haven't seen this issue yet on Windows.

Clone https://github.com/halter73/signalr-verification/tree/halter73/msbuild/2872 and checkout the halter73/msbuild/2872 branch. Then simply run "dotnet build".

On Linux and macOS, you'll see output like the following:

```
shalter@f4-linux-server:~/signalr-verification/signalr-verification$ dotnet build
Microsoft (R) Build Engine version 15.7.10.24921 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 35.09 ms for /home/shalter/signalr-verification/signalr-verification/signalr-verification.csproj.
  Restore completed in 96.72 ms for /home/shalter/signalr-verification/signalr-verification/signalr-verification.csproj.
/home/shalter/signalr-verification/dotnet/sdk/2.1.300-preview1-008117/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/shalter/signalr-verification/signalr-verification/signalr-verification.csproj]

Build FAILED.

/home/shalter/signalr-verification/dotnet/sdk/2.1.300-preview1-008117/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/shalter/signalr-verification/signalr-verification/signalr-verification.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.57
```

Windows exhibits the expected behavior and outputs the cause of the build error:

```
G:\dev\halter73\signalr-verification [halter73/msbuild/2872 ≡]> dotnet build
Microsoft (R) Build Engine version 15.7.10.24921 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for G:\dev\halter73\signalr-verification\signalr-verification.csproj...
  Restoring packages for G:\dev\halter73\signalr-verification\signalr-verification.csproj...
  Restore completed in 1.18 sec for G:\dev\halter73\signalr-verification\signalr-verification.csproj.
  Generating MSBuild file G:\dev\halter73\signalr-verification\obj\signalr-verification.csproj.nuget.g.props.
  Generating MSBuild file G:\dev\halter73\signalr-verification\obj\signalr-verification.csproj.nuget.g.targets.
  Restore completed in 1.33 sec for G:\dev\halter73\signalr-verification\signalr-verification.csproj.
Program.cs(18,13): error CS0103: The name 'foo' does not exist in the current context [G:\dev\halter73\signalr-verification\signalr-verification.csproj]
Program.cs(18,13): error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement [G:\dev\halter73\signalr-verification\signalr-verification.csproj]

Build FAILED.

Program.cs(18,13): error CS0103: The name 'foo' does not exist in the current context [G:\dev\halter73\signalr-verification\signalr-verification.csproj]
Program.cs(18,13): error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement [G:\dev\halter73\signalr-verification\signalr-verification.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.79
```

Notably, if you take the previous commit (halter73/msbuild/2872~1) which also doesn't build due to a missing semicolon instead of a nonexistent name, the cause of the build error *is* output as expected on Linux and macOS.

```
shalter@f4-linux-server:~/signalr-verification/signalr-verification$ git reset --hard HEAD~
HEAD is now at 7e6378a Introduce build error displayed by msbuild
shalter@f4-linux-server:~/signalr-verification/signalr-verification$ dotnet build
Microsoft (R) Build Engine version 15.7.10.24921 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 35.58 ms for /home/shalter/signalr-verification/signalr-verification/signalr-verification.csproj.
  Restore completed in 83.96 ms for /home/shalter/signalr-verification/signalr-verification/signalr-verification.csproj.
Microsoft (R) Visual C# Compiler version 2.8.0.62608 (b2a417c1)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(18,16) : error CS1002: ; expected [/home/shalter/signalr-verification/signalr-verification/signalr-verification.csproj]

Build FAILED.

Microsoft (R) Visual C# Compiler version 2.8.0.62608 (b2a417c1)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(18,16) : error CS1002: ; expected [/home/shalter/signalr-verification/signalr-verification/signalr-verification.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.40
```

The error is still only available through binary logs which I copied to a Windows machine to look at using the structured log viewer http://msbuildlog.com/.

Like before, the actual compilation errors weren't in an "Errors" section of the binary logs like I would expect, but it's under a section labled "Microsoft (R) Visual C# Compiler version 2.7.0.62419 (34563958)" which is just the first line of csc output. Clicking the "Errors" section just shows Microsoft.CSharp.Core.targets in the right panel.

```
shalter@halter73-mbp signalr-verification (halter73/msbuild/2872)$ dotnet build /bl
Microsoft (R) Build Engine version 15.7.10.24921 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/Users/shalter/Downloads/dotnet-sdk-2.1.300-preview1-008117-osx-x64/sdk/2.1.300-preview1-008117/MSBuild.dll /bl /clp:Summary /distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/Users/shalter/Downloads/dotnet-sdk-2.1.300-preview1-008117-osx-x64/sdk/2.1.300-preview1-008117/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/Users/shalter/Downloads/dotnet-sdk-2.1.300-preview1-008117-osx-x64/sdk/2.1.300-preview1-008117/dotnet.dll /m /restore /t:Build /v:m ./signalr-verification.csproj
  Restore completed in 111.25 ms for /Users/shalter/source/halter73/signalr-verification/signalr-verification.csproj.
  Restore completed in 42.93 ms for /Users/shalter/source/halter73/signalr-verification/signalr-verification.csproj.
/Users/shalter/Downloads/dotnet-sdk-2.1.300-preview1-008117-osx-x64/sdk/2.1.300-preview1-008117/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/Users/shalter/source/halter73/signalr-verification/signalr-verification.csproj]

Build FAILED.

/Users/shalter/Downloads/dotnet-sdk-2.1.300-preview1-008117-osx-x64/sdk/2.1.300-preview1-008117/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/Users/shalter/source/halter73/signalr-verification/signalr-verification.csproj]
    0 Warning(s)
    1 Error(s)
```

![screen shot 2018-02-09 at 5 05 45 pm](https://user-images.githubusercontent.com/54385/36056727-b0594a12-0dbb-11e8-9b4b-83cbcddc1e5f.png)

![screen shot 2018-02-09 at 5 05 28 pm](https://user-images.githubusercontent.com/54385/36056714-98eaf27c-0dbb-11e8-9923-a5d271492bc5.png)

**Comment by halter73** [comment] 2018-02-10 01:13
### Environment Data

The below info was taken from the Linux, macOS and Windows sdks used to produce the output in above comment. Interestingly enough version 2.2.0-preview1-008003 of the .NET SDK on my Mac does *not* exhibit this bug unlike version 2.1.300-preview1-008117 which does.

```
$ dotnet --info
.NET Command Line Tools (2.1.300-preview1-008117)

Product Information:
 Version:            2.1.300-preview1-008117
 Commit SHA-1 hash:  60614db20c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/shalter/signalr-verification/dotnet/sdk/2.1.300-preview1-008117/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26208-06
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

```
$ dotnet --info
.NET Command Line Tools (2.1.300-preview1-008117)

Product Information:
 Version:            2.1.300-preview1-008117
 Commit SHA-1 hash:  60614db20c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/shalter/Downloads/dotnet-sdk-2.1.300-preview1-008117-osx-x64/sdk/2.1.300-preview1-008117/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26208-06
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

```
> dotnet --info
.NET Command Line Tools (2.1.300-preview1-008117)

Product Information:
 Version:            2.1.300-preview1-008117
 Commit SHA-1 hash:  60614db20c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\shalter\Downloads\dotnet-sdk-2.1.300-preview1-008117-win-x64\sdk\2.1.300-preview1-008117\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26208-06
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

**Comment by rainersigwald** [comment] 2018-02-13 00:23
Disabling the compiler server causes it to behave correctly:

```sh-session
raines@raines-z220u:~/src/signalr-verification$ ~/Downloads/dotnet-sdk/dotnet --version
2.1.300-preview1-008117
raines@raines-z220u:~/src/signalr-verification$ ~/Downloads/dotnet-sdk/dotnet build
Microsoft (R) Build Engine version 15.7.10.24921 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 55.53 ms for /home/raines/src/signalr-verification/signalr-verification.csproj.
  Restore completed in 15.17 ms for /home/raines/src/signalr-verification/signalr-verification.csproj.
/home/raines/Downloads/dotnet-sdk/sdk/2.1.300-preview1-008117/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/raines/src/signalr-verification/signalr-verification.csproj]

Build FAILED.

/home/raines/Downloads/dotnet-sdk/sdk/2.1.300-preview1-008117/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/raines/src/signalr-verification/signalr-verification.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.12
raines@raines-z220u:~/src/signalr-verification$ ~/Downloads/dotnet-sdk/dotnet build /p:UseSharedCompilation=false
Microsoft (R) Build Engine version 15.7.10.24921 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 56 ms for /home/raines/src/signalr-verification/signalr-verification.csproj.
  Restore completed in 14.99 ms for /home/raines/src/signalr-verification/signalr-verification.csproj.
Program.cs(18,13): error CS0103: The name 'foo' does not exist in the current context [/home/raines/src/signalr-verification/signalr-verification.csproj]
Program.cs(18,13): error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement [/home/raines/src/signalr-verification/signalr-verification.csproj]

Build FAILED.

Program.cs(18,13): error CS0103: The name 'foo' does not exist in the current context [/home/raines/src/signalr-verification/signalr-verification.csproj]
Program.cs(18,13): error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement [/home/raines/src/signalr-verification/signalr-verification.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:02.57
```

That makes me suspect that it's the Csc task that's doing something different in different circumstances here.

**Comment by rainersigwald** [comment] 2018-02-13 19:22
@halter73 Thanks for the reduced repro! That helped track it down. I think this is best tracked as https://github.com/dotnet/roslyn/issues/24736 but I don't have permissions to reactivate it over there so I'll leave it open here until someone does so, so it doesn't get lost.

**Comment by rainersigwald** [comment] 2018-02-16 19:54
Duplicate of https://github.com/dotnet/roslyn/issues/24736

**Closed by rainersigwald** 2018-02-16 19:54 UTC
