### ISSUE TITLE
MSBuild.exe is still running after a build in visual Studio 15.7.2

### ISSUE THREAD

**Issue by dojo90** [microsoft/msbuild#3342] opened 2018-05-24 06:53 UTC
### Steps to reproduce
Project file
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project TreatAsLocalProperty="NodeReuse" ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBUILDDISABLENODEREUSE>True</MSBUILDDISABLENODEREUSE>
    <NodeReuse>False</NodeReuse>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <ProductVersion>3.10</ProductVersion>
    <ProjectGuid>6468764d-0126-47a0-b4f6-8fd64a9a6023</ProjectGuid>
    <SchemaVersion>2.0</SchemaVersion>
    <OutputName>VorlageSetup</OutputName>
    <OutputType>Package</OutputType>
    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' AND '$(MSBuildExtensionsPath32)' != '' ">$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>
    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>
    <DefineConstants>Debug;</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Product.wxs" />
  </ItemGroup>
  <ItemGroup>
    <WixExtension Include="WixUtilExtension">
      <HintPath>$(WixExtDir)\WixUtilExtension.dll</HintPath>
      <Name>WixUtilExtension</Name>
    </WixExtension>
    <WixExtension Include="WixNetFxExtension">
      <HintPath>$(WixExtDir)\WixNetFxExtension.dll</HintPath>
      <Name>WixNetFxExtension</Name>
    </WixExtension>
  </ItemGroup>
  <ItemGroup>
    <Content Include="HtPlcFrameworkGui.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyProject\MyProject.csproj">
      <Name>MyProject</Name>
      <Project>{4b29025d-9d0e-4fea-b204-25687cef94b2}</Project>
      <Private>True</Private>
      <DoNotHarvest>True</DoNotHarvest>
      <RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
      <RefTargetDir>INSTALLFOLDER</RefTargetDir>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(WixTargetsPath)" />
  <PropertyGroup>  
  </PropertyGroup>
  <PropertyGroup>
    <LibrariesDir>$(IntermediateOutputPath)\libraries\</LibrariesDir>
    <DefineConstants>LibraryFiles=$(IntermediateOutputPath)\libraries</DefineConstants>
  </PropertyGroup>
  <PropertyGroup>
    <PostBuildEvent />
  </PropertyGroup>
  <PropertyGroup>
    <PreBuildEvent />
  </PropertyGroup>
  <!--
	To modify your build process, add your task inside one of the targets below and uncomment it.
	Other similar extension points exist, see Wix.targets.
	-->
  <Target Name="BeforeBuild">
    <Message Text="Deleting old installer files..." Importance="high" />
    <CreateItem Include="$(TargetDir)*.msi">
      <Output TaskParameter="Include" ItemName="MsiFiles" />
    </CreateItem>
    <Delete Files="@(MsiFiles)" />
    <Message Text="Gathering libraries..." Importance="high" />
    <CreateItem Include="..\MyProject\bin\$(Configuration)\*.dll">
      <Output TaskParameter="Include" ItemName="LibraryFiles" />
    </CreateItem>
    <CreateItem Include="..\MyProject\bin\$(Configuration)\Config\*.*">
      <Output TaskParameter="Include" ItemName="ConfigFiles" />
    </CreateItem>
    <CreateItem Include="..\MyProject\bin\$(Configuration)\x64\*.dll">
      <Output TaskParameter="Include" ItemName="LibraryX64Files" />
    </CreateItem>
    <CreateItem Include="..\MyProject\bin\$(Configuration)\x86\*.dll">
      <Output TaskParameter="Include" ItemName="LibraryX86Files" />
    </CreateItem>
    <MakeDir Directories="$(LibrariesDir)" />
    <MakeDir Directories="$(LibrariesDir)Config" />
    <MakeDir Directories="$(LibrariesDir)x64" />
    <MakeDir Directories="$(LibrariesDir)x86" />
    <Copy SourceFiles="@(LibraryFiles)"    DestinationFolder="$(LibrariesDir)" />
    <Copy SourceFiles="@(ConfigFiles)"     DestinationFolder="$(LibrariesDir)Config" />
    <Copy SourceFiles="@(LibraryX64Files)" DestinationFolder="$(LibrariesDir)x64" />
    <Copy SourceFiles="@(LibraryX86Files)" DestinationFolder="$(LibrariesDir)x86" />
    <Message Text="Heating libraries..." Importance="high" />
    <HeatDirectory DirectoryRefId="INSTALLLOCATION" OutputFile="$(IntermediateOutputPath)\Library.wxs" Directory="$(LibrariesDir)" ComponentGroupName="LibraryFiles" ToolPath="$(WixToolPath)" PreprocessorVariable="var.LibraryFiles" AutogenerateGuids="true" SuppressRootDirectory="true" />
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)\Library.wxs" />
    </ItemGroup>
  </Target>
  <Target Name="AfterBuild">
    <Exec Command="gitsemver filename -f $(TargetPath)" />
  </Target>
</Project>
```
Command line
```
msbuild /nodeReuse:false /p:Configuration=Installer
```
### Expected  behavior

MSBuild should close after build

### Actual behavior

MSBuild is still running building from **VisualStudio**. If running from command line, everything works as expected!

### Environment data
`msbuild /version` output:
15.7.179.6572

OS info:

- VisualStudio 15.7.2
- .NET Framework 4.7.02556

**Comment by rainersigwald** [comment] 2018-05-24 14:38
Setting `MSBUILDDISABLENODEREUSE` inside a project doesn't have any effect--it must be set as an environment variable before the entry-point project starts executing. To affect Visual Studio, that means it must be set in the environment before launching `devenv.exe`.

Note that since Visual Studio has started doing more builds out-of-process (as a robustness and responsiveness improvement), this could significantly hurt your VS experience.

Why are you trying to set this?

**Comment by dojo90** [comment] 2018-05-28 05:27
Hey @rainersigwald,
*I have noticed that setting it in a project doesn't take effect (how embarrassing)!*

Unfortunately setting it in the project file does also not take the effect. The MSBuild.exe is still running afterwards.

> Why are you trying to set this?

I pre-build the complete "install structure" in the "obj" folder. 

```XML
<Target Name="BeforeBuild">
    <Message Text="Deleting old installer files..." Importance="high" />
    <CreateItem Include="$(TargetDir)*.msi">
      <Output TaskParameter="Include" ItemName="MsiFiles" />
    </CreateItem>
    <Delete Files="@(MsiFiles)" />
    <Message Text="Gathering libraries..." Importance="high" />
    <CreateItem Include="..\MyProject\bin\$(Configuration)\*.dll">
      <Output TaskParameter="Include" ItemName="LibraryFiles" />
    </CreateItem>
    <CreateItem Include="..\MyProject\bin\$(Configuration)\Config\*.*">
      <Output TaskParameter="Include" ItemName="ConfigFiles" />
    </CreateItem>
    <CreateItem Include="..\MyProject\bin\$(Configuration)\x64\*.dll">
      <Output TaskParameter="Include" ItemName="LibraryX64Files" />
    </CreateItem>
    <CreateItem Include="..\MyProject\bin\$(Configuration)\x86\*.dll">
      <Output TaskParameter="Include" ItemName="LibraryX86Files" />
    </CreateItem>
    <MakeDir Directories="$(LibrariesDir)" />
    <MakeDir Directories="$(LibrariesDir)Config" />
    <MakeDir Directories="$(LibrariesDir)x64" />
    <MakeDir Directories="$(LibrariesDir)x86" />
    <Copy SourceFiles="@(LibraryFiles)"    DestinationFolder="$(LibrariesDir)" />
    <Copy SourceFiles="@(ConfigFiles)"     DestinationFolder="$(LibrariesDir)Config" />
    <Copy SourceFiles="@(LibraryX64Files)" DestinationFolder="$(LibrariesDir)x64" />
    <Copy SourceFiles="@(LibraryX86Files)" DestinationFolder="$(LibrariesDir)x86" />
    <Message Text="Heating libraries..." Importance="high" />
    <HeatDirectory DirectoryRefId="INSTALLLOCATION" OutputFile="$(IntermediateOutputPath)\Library.wxs" Directory="$(LibrariesDir)" ComponentGroupName="LibraryFiles" ToolPath="$(WixToolPath)" PreprocessorVariable="var.LibraryFiles" AutogenerateGuids="true" SuppressRootDirectory="true" />
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)\Library.wxs" />
    </ItemGroup>
  </Target>
```

When I try to setup/customize the setup and build/rebuild the setup.msi several times, all files in the "obj" folder are still locked. When changing some parameters, the "old" files/folder structures are still kept and the setup.msi file is producing the wrong output on installing.

---
My current solution is building the solution from console (there is it working as expected! The MSBuild.exe is closed afterwards)

*My workmate does not have this problem using the same solution. So maybe there is something wrong with my VisualStudio installation.*

**Comment by geeeyetee** [comment] 2018-06-07 18:04
I have had the same problem in Visual Studio 2017. I work around it by adding `Condition="$(DesignTimeBuild) != true And $(BuildingProject) == true"` to my custom targets. See:
[Determining whether a target is run in a design-time build](https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md#determining-whether-a-target-is-run-in-a-design-time-build)

**Comment by dojo90** [comment] 2018-06-08 05:37
@geeeyetee thanks for reply.

What should I do then, if I know it is build by VS?

**Comment by geeeyetee** [comment] 2018-06-08 15:06
Not sure I understand your the question, but maybe this will help clarify: The condition evaluates to true when you initiate a build in Visual Studio, but to false during the design-time builds that Visual Studio performs in the background. In my project, this has prevented the locking of files in obj\ by persistent instances of MSBuild.exe.

**Comment by delfuria** [comment] 2019-06-28 09:40
Hi, any news about this issue ?
It's very annoying and It's still present in 15.9.13 version !!!
Thanks

**Comment by Jmales** [comment] 2019-09-10 09:21
I'm having this issue as well, but only with the new CSProj format `<Project Sdk="Microsoft.NET.Sdk">` 
In my case I have a target which generates some .cs files. And because of this issue, while VS is opened, the files are infinitely being generated and deleted.

@geeeyetee 's workaround solved my problem though ;)

**Comment by rainersigwald** [comment] 2019-09-16 15:53
Closing this as I think everything is by design:

1. Node reuse can't be configured within a project.
1. Design time builds are expected to run often in Visual Studio--see more information I posted on a linked issue: https://github.com/dotnet/sdk/issues/3627#issuecomment-530047390

As always, we can reopen if necessary.

**Closed by rainersigwald** 2019-09-16 15:53 UTC
