### ISSUE TITLE
.NET Core MSBuild not recognised Project target on unix when Project in solution folder.

### ISSUE THREAD

**Issue by mfilippov** [Microsoft/msbuild#2416] opened 2017-08-10 13:40 UTC
If I run ```dotnet MSBuild.dll /t:Project1 Demo.sln``` for build Project1 only from solution Demo.sln MSBuild cannot find target Project1 if Project1.cspoj to be in a solution folder.

**Comment by rainersigwald** [comment] 2017-08-10 16:02
I set up a simple repro and was able to work around with this diff (change the project definitions with slashes in them to be `/` instead of `\`):

```diff
diff --git a/SolutionFolder.sln b/SolutionFolder.sln
index 8695da5..77fc78b 100644
--- a/SolutionFolder.sln
+++ b/SolutionFolder.sln
@@ -3,7 +3,7 @@ Microsoft Visual Studio Solution File, Format Version 12.00
 # Visual Studio 15
 VisualStudioVersion = 15.0.26730.0
 MinimumVisualStudioVersion = 10.0.40219.1
-Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SolutionFolder", "SolutionFolder\SolutionFolder.csproj", "{BB20EEDF-53F4-4E0D-B68A-53DB54AB4EC0}"
+Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SolutionFolder", "SolutionFolder/SolutionFolder.csproj", "{BB20EEDF-53F4-4E0D-B68A-53DB54AB4EC0}"
 EndProject
 Global
 	GlobalSection(SolutionConfigurationPlatforms) = preSolution
```

That's already tracked:
Duplicate of #2022.

**Closed by rainersigwald** 2017-08-10 16:02 UTC

**Comment by rainersigwald** [comment] 2017-08-10 16:14
Duplicate of #2022.
