### ISSUE TITLE
BuildInParallel=true MSBuild task doesn't halt when inner project has an error in an AfterTarget

### ISSUE THREAD

**Issue by dagood** [Microsoft/msbuild#3623] opened 2018-08-16 22:16 UTC
### Steps to reproduce

1. Clone https://github.com/dagood/repro-msbuild-task-not-stopping
2. Run `repro.ps1` (it sets up a SDK and runs `dotnet msbuild /v:N /bl`)

### Expected  behavior

Build fails, showing this: (Removing `BuildInParallel="true"` from the MSBuild task makes this happen.)

```
Build FAILED.

       "...\build.proj" (default target) (1) ->
       "...\b\b.pkgproj" (default target) (3) ->
       (After target) ->
         ...\b\b.pkgproj(9,5): error : HI

    0 Warning(s)
    1 Error(s)
```

### Actual behavior

Build "succeeds", but shows:

```
Build succeeded.

       "...\build.proj" (default target) (1) ->
       "...\b\b.pkgproj" (default target) (3) ->
       (After target) ->
         ...\b\b.pkgproj(9,5): error : HI

    0 Warning(s)
    1 Error(s)
```

### Environment data
`.\corefx\Tools\dotnetcli\dotnet msbuild /version` output:

```
Microsoft (R) Build Engine version 15.5.153.27799 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.5.153.27799
```

`.\corefx\Tools\dotnetcli\dotnet --info` output:

```
.NET Command Line Tools (15.5.0-preview-007044)

Product Information:
 Version:            15.5.0-preview-007044
 Commit SHA-1 hash:  278cbf6c44

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\15.5.0-preview-007044\

Host (useful for support):
  Version: 2.1.3-servicing-26708-02
  Commit:  cc9cf3686d
```

**Comment by rainersigwald** [comment] 2018-08-16 22:27
Duplicate of #3345

**Comment by rainersigwald** [comment] 2018-08-16 22:30
This happens when the `AfterTargets` hooks the entry-point target of the project. In your repro there's no real way out, but often in real projects you can hook a different place--the linked bug mentions hooking `AfterBuild` instead of `Build`. I can take a look at your real project to see if there's a similar workaround if you'd like.

**Closed by rainersigwald** 2018-08-16 22:30 UTC

**Comment by dagood** [comment] 2018-08-16 22:32
Interesting, thanks. Yeah, there's a lot of stuff here that turns out not to be needed to repro, and the explanation there makes sense. I opened this for https://github.com/dotnet/corefx/issues/31728. @ericstj
