### ISSUE TITLE
Out of proc builds with BuildManager, not supported on OSX 

### ISSUE THREAD

**Issue by radical** [microsoft/msbuild#1240] opened 2016-10-24 21:34 UTC
This can be seen with the `Microsoft.Build.UnitTests.BackEnd.BuildManager_Tests.SimpleBuildOutOfProcess` test. The logs show, that is fails at:

`System.EntryPointNotFoundException: CreateProcess
  at (wrapper managed-to-native) Microsoft.Build.BackEnd.NativeMethods:CreateProcess (string,string,Microsoft.Build.BackEnd.NativeMethods/SECURITY_ATTRIBUTES&,Microsoft.Build.BackEnd.NativeMethods/SECURITY_ATTRIBUTES&,bool,uint,intptr,string,Microsoft.Build.BackEnd.NativeMethods/STARTUP_INFO&,Microsoft.Build.Back
End.NativeMethods/PROCESS_INFORMATION&)
  at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode (System.String msbuildLocation, System.String commandLineArgs) [0x0010b] in /Users/ankit/dev/msbuild/src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:527
  at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNode (System.String msbuildLocation, System.String commandLineArgs, System.Int32 nodeId, Microsoft.Build.BackEnd.INodePacketFactory factory, System.Int64 hostHandshake, System.Int64 clientHandshake, Microsoft.Build.BackEnd.NodeProviderOutOfProcBase+NodeCon
textTerminateDelegate terminateNode) [0x00229] in /Users/ankit/dev/msbuild/src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProcBase.cs:270
  at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNode (System.Int32 nodeId, Microsoft.Build.BackEnd.INodePacketFactory factory, Microsoft.Build.BackEnd.NodeConfiguration configuration) [0x000c0] in /Users/ankit/dev/msbuild/src/XMakeBuildEngine/BackEnd/Components/Communications/NodeProviderOutOfProc.cs:128
  at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode (Microsoft.Build.BackEnd.INodeProvider nodeProvider, Microsoft.Build.BackEnd.NodeConfiguration nodeConfiguration) [0x00075] in /Users/ankit/dev/msbuild/src/XMakeBuildEngine/BackEnd/Components/Communications/NodeManager.cs:361
  at Microsoft.Build.BackEnd.NodeManager.CreateNode (Microsoft.Build.BackEnd.NodeConfiguration configuration, Microsoft.Build.Execution.NodeAffinity nodeAffinity) [0x00052] in /Users/ankit/dev/msbuild/src/XMakeBuildEngine/BackEnd/Components/Communications/NodeManager.cs:117
  at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions (System.Collections.Generic.IEnumerable`1[T] responses) [0x000c3] in /Users/ankit/dev/msbuild/src/XMakeBuildEngine/BackEnd/BuildManager/BuildManager.cs:1523
  at Microsoft.Build.Execution.BuildManager.HandleNewRequest (System.Int32 node, Microsoft.Build.BackEnd.BuildRequestBlocker blocker) [0x0009f] in /Users/ankit/dev/msbuild/src/XMakeBuildEngine/BackEnd/BuildManager/BuildManager.cs:1345
  at Microsoft.Build.Execution.BuildManager.IssueRequestToScheduler (Microsoft.Build.Execution.BuildSubmission submission, System.Boolean allowMainThreadBuild, Microsoft.Build.BackEnd.BuildRequestBlocker blocker) [0x00069] in /Users/ankit/dev/msbuild/src/XMakeBuildEngine/BackEnd/BuildManager/BuildManager.cs:1119`

This test is being run with `Environment.SetEnvironmentVariable("MSBUILDNOINPROCNODE", "1")` for a out of proc build.

**Comment by rainersigwald** [comment] 2019-11-04 21:39
This is essentially a duplicate of #3588

**Closed by rainersigwald** 2019-11-04 21:39 UTC
Labels: Disabled-Tests, testing
