### ISSUE TITLE
Nested comments in ItemGroups are removed

### ISSUE THREAD

**Issue by 333fred** [Microsoft/msbuild#1627] opened 2017-01-30 04:21 UTC
Repro steps:

1. Create a new .NET Core project
2. Add an empty folder to the project. This adds an ItemGroup to the project file like this:
```xml
  <ItemGroup>
    <Folder Include="asdf\" />
  </ItemGroup>
```
3. Add a comment inside the group.
```xml
  <ItemGroup>
    <!-- Test Comment -->
    <Folder Include="asdf\" />
  </ItemGroup>
```
4. Either delete the folder, or add a class file to the folder so the item group is removed. The comment is removed as well.

**Comment by 333fred** [comment] 2017-01-30 04:21
FYI @wjk.

**Comment by davkean** [comment] 2017-01-30 04:31
@wjk Does this correctly describe your issue?

**Comment by wjk** [comment] 2017-01-30 05:03
No, it does not. My issue is that _any_ comments or blank lines, no matter where they are located in the file, are removed whenever Visual Studio writes the file out to disk.

**Comment by davkean** [comment] 2017-01-30 05:05
Do you have this option turned on? 
![image](https://cloud.githubusercontent.com/assets/1103906/22412753/e2557154-e705-11e6-96e6-9aaf4ff18103.png)

Or do you get a prompt when this behavior occurs?

**Comment by davkean** [comment] 2017-01-30 05:06
Trying to figure out if you're running into: https://github.com/dotnet/roslyn-project-system/issues/1348

**Comment by wjk** [comment] 2017-01-30 05:08
That checkbox is currently turned off in my copy of VS, but regardless I have never seen any reload prompts.

**Comment by davkean** [comment] 2017-01-30 05:12
Hmm, okay, then I don't what the cause is - your running the latest VS build right?

**Comment by davkean** [comment] 2017-01-30 05:12
ie https://blogs.msdn.microsoft.com/visualstudio/2017/01/27/update-to-visual-studio-2017-release-candidate/.

**Comment by davkean** [comment] 2017-01-30 05:13
@333fred Why do you think the original is a MSBuild bug?

**Comment by wjk** [comment] 2017-01-30 05:21
As far as I can tell, I am. I have version 15.0.26127.0.

**Comment by 333fred** [comment] 2017-01-30 08:06
Because we don't control how comments are preserved: CPS and the Project System are using the `ProjectRootElement.Reload()` API.

**Comment by davkean** [comment] 2017-01-30 08:22
The repro you have above shouldn't be going through a Reload path, it should be a direct manipulation of the in-memory project file.

**Comment by rainersigwald** [comment] 2017-01-30 17:31
@wjk's issue sounds like something is loading the project without passing the new `PreserveFormatting` flag.

The main issue here sounds like we're removing the `ItemGroup` when it's empty (reasonable) without considering comments (broken if `PreserveFormatting`, arguably).

**Comment by cdmihai** [comment] 2017-01-30 18:01
I verified and this bit of code leads to the removal of the comment even when preserve formatting is set to true:

```c#
            var projectPath = @"D:\projects\tests\projects\play\build.proj";
            var pre = ProjectRootElement.Open(projectPath, ProjectCollection.GlobalProjectCollection, preserveFormatting: true);

            var p = new Project(pre);
            var i = p.Items.First();

            p.RemoveItem(i);

            var s = p.Xml.RawXml;
```

where the project file is:
```xml
<?xml version="1.0" encoding="utf-16"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<!--comment-->
		<I Include="a"/>
	</ItemGroup>
</Project>
```

@333fred / @davkean 
Can you please confirm this is the msbuild code path you are using?

**Comment by 333fred** [comment] 2017-01-30 18:02
Yep, we're using `RawXml`.

**Comment by cdmihai** [comment] 2017-01-30 18:33
The bit that's actually removing the entire ItemGroup in my repro is `Project.RemoveItem`, not `RawXml`. So, in this issue's specific scenario, is VS calling `Project.RemoveItem` on the only remaining item inside an ItemGroup? If yes, then `Project.RemoveItem` is the cause of this issue. If not, there's another cause we need to look into.

**Comment by 333fred** [comment] 2017-01-30 18:35
@lifengl @jviau, is CPS removing the item node here?

**Comment by jviau** [comment] 2017-01-30 19:43
@333fred yes CPS will remove the item group here. We remove item groups when it no longer has any children. And since CPS keeps different item types within their own item groups, the transition from Folder to anything else will remove it as well.

**Comment by davkean** [comment] 2017-01-30 21:47
Removing the item or removing the group?

**Comment by jviau** [comment] 2017-01-30 21:49
In this case including something under the Folder removes the item group, because Folder is removed and that item group is now empty, so we remove it as well.

**Comment by davkean** [comment] 2017-01-30 21:50
So this would be a CPS issue?

**Comment by jviau** [comment] 2017-01-30 21:55
I don't think we can change this. It matches default MSBuild behavior as @cdmihai pointed out. Can we even tell there is a comment in there at all? We don't have access to the XML document. 

If we don't remove it you are going to start seeing a lot of empty `<ItemGroup />` elements in the project.

**Comment by rainersigwald** [comment] 2017-01-30 22:02
And honestly, I'm not sure what the correct behavior is. If I was using automagic refactorers on C# to delete the declaration of `x` here:

```c#
var x = y; // Because of the phase of the moon
```

I'd be pretty surprised if the result was a line with just the comment.

Likewise, I find it entirely believable that a user removing this item:

```xml
<ItemGroup>
 <!-- Works around bug in package X -->
 <Content Include="X.file" />
</ItemGroup>
```

Would want the whole thing gone in the end. I think our current behavior is ok (not the best imaginable but reasonable).

**Comment by davkean** [comment] 2017-01-30 22:16
Now move that comment just above the ItemGroup - notice it doesn't get removed? Trivia is hard...

**Comment by rainersigwald** [comment] 2018-11-19 23:39
Reviewing this, I don't see a concrete idea that would make everything better. Closing this, but I'm open to reopening if there is one.

**Closed by rainersigwald** 2018-11-19 23:39 UTC
