### ISSUE TITLE
TargetFrameworks (multi-target project) - missing items in AllEvaluatedItems

### ISSUE THREAD

**Issue by pkruk2** [Microsoft/msbuild#3202] opened 2018-04-17 14:37 UTC
### Steps to reproduce

1. Create project which targets two frameworks (the project should contain a source file):
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net46</TargetFrameworks>
  </PropertyGroup>
</Project>

```
2. Open the project using Microsoft.Build.Evaluation.Project
`var project = new Project("path_to_csproj")`

3. Inspect AllEvaluatedItems contents
`project.AllEvaluatedItems`

### Expected  behavior

AllEvaluatedItems should contain information about source files contained in the project. For example if I have a file "Class1.cs" in project, there should be item Compile Class1.cs. 
This is how it works for project with single target framework ("<TargetFramework>")

### Attachments

[MsbuildTargetFrameworks.zip](https://github.com/Microsoft/msbuild/files/1920258/MsbuildTargetFrameworks.zip)

Attaching a simple solution with 3 projects:
1. MultiTargetFrameworks 
2. SingleTargetFramework
3. ConsoleApp1

You can compile it and run ConsoleApp1, passing it 1 argument - path to project file. It will open the project and print to console content of AllEvaluatedItems.
There are also files output_multi.txt and output.single.txt there with output saved from my run.

### Versions

I have tested this using latest stable Microsoft.Build nuget package version 15.6.85 on Windows 7.

**Comment by rainersigwald** [comment] 2018-04-17 14:48
The structure of multitargeted projects is that building the project with no specified TargetFramework just launches builds of itself, specifying each TargetFramework. Since it takes time to search the disk in order to populate the default globs for Compile and so on, those are not included in the "outer" project--only the "inner" projects with TF specified.

This is important, because it's possible to have differing items in different TFs--consider PackageReferences or source files that apply only to the .NET Core build, and not to a .NET 4.6 build.

To get the information you want, you will have to do more work: load the project and inspect its `TargetFrameworks` property. If it's defined, load the project with the global property `TargetFramework` set to one of the ones specified in the outer build.

After you've gotten the inner builds of interest, you'll have to decide what you want to do with the result: build up a union? An intersection? That's specific to your application. Visual Studio, for example, uses a union when displaying source files--if it's in any TF, display it in the project tree. But for NuGet package references it displays them by TF:

![image](https://user-images.githubusercontent.com/3347530/38877485-65b96814-4224-11e8-86b2-d2adf2ede3c4.png)

**Comment by rainersigwald** [comment] 2018-04-17 14:50
As an aside, when using the API you should reference the new Microsoft.Build.Locator package. That avoids many problems related to getting builds that match what Visual Studio would have done on the same machine. The docs aren't live yet but MicrosoftDocs/visualstudio-docs#761 has information on using it.

**Comment by pkruk2** [comment] 2018-04-17 15:14
Thanks for quick answer! Makes sense.

**Comment by rainersigwald** [comment] 2018-04-17 15:26
Thanks for asking. I'm going to close this since the behavior is "by design".

**Closed by rainersigwald** 2018-04-17 15:26 UTC

**Comment by pkruk2** [comment] 2018-05-16 16:37
@rainersigwald I a have question for your remark:

> As an aside, when using the API you should reference the new Microsoft.Build.Locator package. That avoids many problems related to getting builds that match what Visual Studio would have done on the same machine. The docs aren't live yet but MicrosoftDocs/visualstudio-docs#761 has information on using it.

Microsoft.Build.Evaluation.Project is in microsoft.build.* assembly. How will Microsoft.Build.Locator help me?

To use Microsoft.Build.Locator I can't have microsoft.build assemblies in my project's output dir, as it tries to resolve them on runtime using msbuild installed on machine. It also support VS2017+ only.

To compile code that uses Microsoft.Build.Evaluation.Project I must have microsoft.build references. The easiest way is to use microsoft.build nuget package. Is this not recommended way?

**Comment by rainersigwald** [comment] 2018-05-16 18:05
You should use the Microsoft.Build NuGet packages to compile against, but use the metadata `ExcludeAssets="runtime"` on the `PackageReference` to prevent them from being copied to your output directory. Instead, let Microsoft.Build.Locator find MSBuild for you. The Locator package includes a target that tries to guide you down that road.

**Comment by pkruk2** [comment] 2018-05-17 08:28
But it only works if you have VS2017 or Build Tools 2017 installed on machine which executes program, right?

**Comment by rainersigwald** [comment] 2018-05-17 14:06
That's correct.
