### ISSUE TITLE
Configure CI build for xplat

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#40] opened 2015-03-26 20:38 UTC
CI build on xplat branch should:
1. Run unit tests.
2. Run on Linux.

Right now it's the same as on master which builds (using retail msbuild) and then rebuilds (using OSS msbuild).

**Comment by jasonwilliams200OK** [comment] 2015-03-27 08:37
@AndyGerlicher, will xplat and master always remain two separate branches or will there be reconciliation at some point? What about the feature disparity?

**Comment by AndyGerlicher** [comment] 2015-03-27 18:25
For now we're not planning on merging platform specific changes back into master for shipping. And some features (like multi-proc) use Windows specific features (named pipes) that we don't have a plan to address right now. That's not to say we won't ever, we're in the planning phases for the [MSBuild vNext](http://research.microsoft.com/en-us/projects/tse/default.aspx) project and cross platform / .NET Core won't be overlooked.

**Comment by mmitche** [comment] 2015-04-13 15:34
@AndyGerlicher the build.pl doesnt' seem to work:

/home/ubuntu-vm/msbuild/src/MSBuild.sln:  warning : /home/ubuntu-vm/msbuild/src/XMakeTasks/Microsoft.Build.Tasks.csproj: Expected a property at position 3 in condition "!$(Configuration.EndsWith('MONO'))". Missing closing parantheses'.

Am I missing some instructions?

**Comment by jasonwilliams200OK** [comment] 2015-05-17 09:37
Will it be configured on TravisCI? 
There are many projects already hosted on TravisCI from Microsoft org on GitHub: 
https://travis-ci.org/microsoft/
copy @akoeplinger

**Comment by mmitche** [comment] 2015-05-19 15:52
I already configured builds of the xplat branch for windows on the .NET Jenkins instance (see comment above regarding the build.pl issue)
http://dotnet-ci.cloudapp.net/job/microsoft_msbuild_xplat/

**Comment by akoeplinger** [comment] 2015-05-19 16:05
@mmitche build.pl works fine for me on Ubuntu.

**Comment by mmitche** [comment] 2015-05-19 16:46
@akoeplinger okay it's been a while since I checked it out, so I'll take a look now.

**Comment by mmitche** [comment] 2015-05-19 17:47
@akoeplinger Still getting the same issue.  Do you have a special version of mono installed?

**Comment by akoeplinger** [comment] 2015-05-19 17:51
@mmitche I'm running Mono 4.0.1 (the latest released version).

**Comment by mmitche** [comment] 2015-05-19 18:18
@akoeplinger Okay it builds okay with 4.0.1 (but not with 3.2).  Just verifying, do you get failures when you specify -all or -tests?

**Comment by akoeplinger** [comment] 2015-05-19 18:24
@mmitche -verify works on Mono 4.1 which is currently in development (unfortunately there's a regression in 4.0 that affects Roslyn, so MSBuild fails to build itself). -tests shows a bunch of failured unit tests, I believe I've seen work happening to fix those.

**Comment by jasonwilliams200OK** [comment] 2015-08-28 15:44
@mmitche, now that Mono 4.2 is released (http://www.mono-project.com/docs/about-mono/releases/4.2.0/), would it make sense to install latest mono in CI for all related projects, including MSBuild?

**Comment by mmitche** [comment] 2015-08-28 15:50
@jaredpar How does mono 4.2 + roslyn work out (with MSBuild and otherwise)

**Comment by jaredpar** [comment] 2015-08-28 15:58
@mmitche we haven't tested it yet.  We're in the middle of a big switch right now (project.json and NuGet v3).  Once that switch is made we're going to come back to looking at Mono 4.2.0.

**Comment by jasonwilliams200OK** [comment] 2015-08-28 15:58
@jaredpar, also as witnessed here: https://github.com/dotnet/roslyn/issues/2844#issuecomment-129221304, now that all your changes are merged, Mono release works with Roslyn OOTB. With that being said, will it make sense to update this part of Roslyn's xplat doc: https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/cross-platform.md#build-from-source?

**Comment by jaredpar** [comment] 2015-08-28 16:01
@jasonwilliams200OK only once we've verified that Mono 4.2.0 works with our setup.  This is very much on our radar.  But as said in the other comment we're currently in the process of moving to project.json + NuGet v3.  That's turned out to be a rather tall task for us and it's hard to do these in parallel because they are very much intertwined.

**Comment by jasonwilliams200OK** [comment] 2015-08-28 16:07
I commented about the same instant as you. :smile: 
Thanks for the update! :+1:

**Closed** 2015-09-29 22:42 UTC
Labels: xplat
