### ISSUE TITLE
Microsoft.Build.Runtime is not a complete build environment

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#1096] opened 2016-09-27 16:43 UTC
Attempting to do in-proc project evaluation with a .NET Core console app. When evaluating a project that imports Microsoft.CSharp.targets, the evaluation fails:

Error
```
Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "/private/tmp/msbuild-eval/pub/Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  /private/tmp/msbuild-eval/pub/Microsoft.CSharp.CurrentVersion.targets
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
```

The project
```xml
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v1.0</TargetFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
    <EmbeddedResource Include="**\*.resx" Exclude="$(GlobalExclude)" />
    <None Include="project.json" />
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Using Microsoft.Build.Runtime 15.1.262-preview5.

My simple tool: https://gist.github.com/natemcmaster/10af76b63627df8a1f106d3c24ea2ff0

**Comment by rainersigwald** [comment] 2016-09-27 16:51
This is semi-expected. That file lives in the Roslyn repo, not here.

But it is indeed super confusing that our Runtime package isn't complete enough. We've discussed producing a package out of the dotnet/sdk repo to aggregate our Runtime package + other necessary things (this will eventually include the NuGet targets and DLLs too). @jeffkl did we get commitment on that plan?

**Comment by jeffkl** [comment] 2016-09-27 16:52
As @rainersigwald said, at the moment, this is by design.  The MSBuild team does not own `Microsoft.CSharp.Core.targets`.  We'll need another team to provide a package that contains this file as well as the compilers like `csc.exe`.  Those packages will depend on Microsoft.Build.Runtime or your app's project.json will need to include both.

Some of these packages might exist and I'm trying to track them down.  I start a thread today to get some answers.

**Comment by jeffkl** [comment] 2016-09-27 16:57
@natemcmaster can you try adding the package `Microsoft.Net.Compilers.NetCore` to your project.json?

https://dotnet.myget.org/feed/roslyn-master-nightly/package/nuget/Microsoft.Net.Compilers.netcore

**Comment by natemcmaster** [comment] 2016-09-27 17:13
@jeffkl I'll try and get back to you later today. Traveling today, so will have limited access to internet.

**Comment by natemcmaster** [comment] 2016-09-28 23:47
I added the package, but it doesn't appear to contain Microsoft.CSharp.Core.targets

```
└── 2.0.0-beta6-60928-14
    ├── microsoft.net.compilers.netcore.2.0.0-beta6-60928-14.nupkg
    ├── microsoft.net.compilers.netcore.2.0.0-beta6-60928-14.nupkg.sha512
    ├── microsoft.net.compilers.netcore.nuspec
    ├── ref
    │   ├── dotnet
    │   │   └── _._
    │   └── netcoreapp1.0
    │       └── _._
    └── runtimes
        └── any
            └── native
                ├── csc.exe
                └── vbc.exe
```

**Comment by jeffkl** [comment] 2016-09-29 03:54
Sorry I missed a package.  You'll need that one and `"Microsoft.CodeAnalysis.Build.Tasks": "2.0.0-beta6-60923-02"`

`contentFiles\any\any\Microsoft.CSharp.Core.targets`

**Comment by natemcmaster** [comment] 2016-10-03 17:37
Yeah, that fixes the issue. Does this mean "Microsoft.CodeAnalysis.Build.Tasks" should be added to the list of dependencies in Microsoft.Build.Runtime.nuspec?

**Comment by jeffkl** [comment] 2016-10-03 18:12
I think what it really means is we need some team to produce a new package like `Microsoft.CSharp.BuildApp` that would depend on our package plus the compilers package, plus anything else need to have an app build CSharp.  We're trying to engage the Roslyn team to see if they want to own this package.

**Comment by natemcmaster** [comment] 2016-10-05 18:00
Just my two cents: the issue of who owns the Microsoft.CSharp.Core.targets should be transparent to consumers. 

IMO Microsoft.CSharp.targets shouldn't be in Microsoft.Build.Runtime unless Microsoft.CSharp.Core.targets is also included or Microsoft.CodeAnalysis.Build.Tasks is listed as dependency. Maybe a Microsoft.Build.Runtime.CSharp package could work?

**Comment by jeffkl** [comment] 2016-10-11 21:39
@natemcmaster Yeah or opinion is that there needs to be a meta package that has all the right dependencies.  The big question is who should create this package?

**Comment by Sarabeth-Jaffe-Microsoft** [comment] 2016-10-18 22:07
Closing this for now. Routing to internal team.

**Closed by Sarabeth-Jaffe-Microsoft** 2016-10-18 22:07 UTC
