### ISSUE TITLE
Could not write lines to file AssemblyAttributes.cs

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#2188] opened 2017-06-07 17:55 UTC
One of the builds for dotnet/sdk failed with

``
/mnt/j/workspace/dotnet_sdk/release_2.0.0/debug_ubuntu16.04_prtest/.dotnet_cli/sdk/2.0.0-preview2-006353/Microsoft.Common.CurrentVersion.targets(3208,5): error MSB3491: Could not write lines to file "/tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs". Access to the path '/tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs' is denied. [/mnt/j/workspace/dotnet_sdk/release_2.0.0/debug_ubuntu16.04_prtest/src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj]
``

The link to the build log is here: https://ci.dot.net/job/dotnet_sdk/job/release_2.0.0/job/debug_ubuntu16.04_prtest/131/console

This seems like a race condition between two builds generating the AssemblyAttributes.cs file at the same time.

**Comment by jeffkl** [comment] 2017-06-07 18:16
Dupe of https://github.com/Microsoft/msbuild/issues/1479

**Closed by jeffkl** 2017-06-07 18:16 UTC
