### ISSUE TITLE
Documentation: MSBuild property functions escape contents

### ISSUE THREAD

**Issue by cdmihai** [Microsoft/msbuild#2081] opened 2017-05-09 17:22 UTC
```xml
<Project>
        <PropertyGroup>
            <A>foo</A>
            <B>/foo;/a/b/foo;/a/foo/b</B>
            <C>$(B.Replace('$(A)', '$(A)/signed'))</C>
        </PropertyGroup>

        <ItemGroup>
            <I Include="$(C)"/>
        </ItemGroup>

        <Target Name="Main">

           <Message Text="%(I.Identity)"/>

        </Target>
</Project>
```

Produces the following output:
```
Project "d:\projects\tests\projects\play\build.proj" on node 1 (default targets).
Main:
  /foo/signed;/a/b/foo/signed;/a/foo/signed/b
Done Building Project "d:\projects\tests\projects\play\build.proj" (default targets).

Build succeeded.
```

After any property function evaluates, its contents is escaped: https://github.com/Microsoft/msbuild/blob/master/src/Build/Evaluation/Expander.cs#L3172 (in Microsoft.Build.Evaluation.Expander.Function.Execute). Except `MSBuild.Escape` and `MSBuild.Unescape`

An unfavorable consequence to this is that user data gets escaped, and its meaning potentially altered. One way to avert this is to `Unescape` the property function:

```xml
<Project>
        <PropertyGroup>
            <A>foo</A>
            <B>/foo;/a/b/foo;/a/foo/b</B>
            <C>$(B.Replace('$(A)', '$(A)/signed'))</C>
            <D>$([MSBUILD]::Unescape($(C)))</D>
        </PropertyGroup>

        <ItemGroup>
            <I Include="$(D)"/>
        </ItemGroup>

        <Target Name="Main">

           <Message Text="%(I.Identity)"/>

        </Target>
</Project>
```

Produces

```
Project "d:\projects\tests\projects\play\build.proj" on node 1 (default targets).
Main:
  /foo/signed
  /a/b/foo/signed
  /a/foo/signed/b
Done Building Project "d:\projects\tests\projects\play\build.proj" (default targets).

Build succeeded.
```

**Comment by AndyGerlicher** [comment] 2017-05-09 22:47
Team Triage:
Closing issue, behavior by design.

**Closed by AndyGerlicher** 2017-05-09 22:47 UTC
Labels: Feature - Escaping
