### ISSUE TITLE
Need a way to force localized MSBuild versions to English

### ISSUE THREAD

**Issue by KirillOsenkov** [microsoft/msbuild#3782] opened 2018-09-22 00:10 UTC
I see some machines use a localized Visual Studio and MSBuild (e.g. Russian or German). There needs to be a way (command-line switch? property? environment variable?) to force the log messages to English. When investigating (e.g. binlogs) we should be able to ask the customers to produce an English log (esp. that localized logs are pretty useless for diagnostics as you can't search for the messages).

**Comment by dasMulli** [comment] 2018-09-23 05:59
For comparison, the CLI respects the following environment variables (https://github.com/dotnet/cli/pull/7021):
* DOTNET_CLI_UI_LANGUAGE
* VSLANG
* PreferredUILang

Roslyn has a `-preferreduilang` command line switch.

**Comment by nguerrera** [comment] 2019-05-17 23:11
Dupe of https://github.com/microsoft/msbuild/issues/1596 ?

**Comment by rainersigwald** [comment] 2019-05-18 02:47
Duplicate of #1596

**Closed by rainersigwald** 2019-05-18 02:47 UTC
