### ISSUE TITLE
Rewriting of msbuild files

### ISSUE THREAD

**Issue by gregoryyoung** [Microsoft/msbuild#29] opened 2015-03-20 13:11 UTC
I have run into this problem many times. I am not sure if its in the shared libs from msbuild or in visual studio. But when you for instance use wildcards and then write back a project file the wildcard gets replaced with a list of files (currently matching the wildcards) when you open and save with Visual Studio.

Not sure where this code may be, if someone can point me to it I would be happy to investigate, create some unit tests, and likely send a PR

Cheers,

Greg

**Comment by monoman** [comment] 2015-03-20 13:23
AFAIK it is Visual Studio that rewrites project files on load... Nothing we
can do from here :(

Rafael Teixeira
O..:.)oooo

**Comment by shalupov** [comment] 2015-03-20 13:23
Related uservoice thread: https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4512873-vs-ide-should-support-file-patterns-in-project-fil

**Comment by gregoryyoung** [comment] 2015-03-20 13:24
I figured the code that did it could quite likely actually be in the
msbuild shared libraries that I believe VS actually uses?

Its also totally possible it just uses that model and transforms from one
to another.

On Fri, Mar 20, 2015 at 3:23 PM, Leonid Shalupov <notifications@github.com>
wrote:

> Related uservoice thread:
> https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4512873-vs-ide-should-support-file-patterns-in-project-fil
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/msbuild/issues/29#issuecomment-84016737>.
>



-- 
Studying for the Turing test

**Comment by sarajoiner** [comment] 2015-03-20 20:04
Most of the time, Visual Studio just uses the MSBuild APIs when interacting with MSBuild project files.  (Or e.g. shims created for the purpose of exposing the MSBuild APIs as COM-visible to native code project systems, which generally just pass through to the underlying MSBuild API). 

The code that controls this will likely be somewhere in the Evaluation model (Microsoft.Build.Evaluation namespace, mostly in XMakeBuildEngine\Definition and \Evaluation).  Construction model is the other one that hosts use a lot for project manipulation, but since it's a very thin wrapper over the XML it doesn't try to do anything clever. 

I'd probably start looking at the Project.Add* and Remove* helper methods (XMakeBuildEngine\Definition\Project.cs), since IIRC those do clever things to try and convert "add this logical item" to "this is the XML manipulation necessary". 

(I have this very dim recollection that we have some wildcard checks in place to handle them gracefully on add, but not on remove, and that the latter was generally the root of the explosion problem, but I may be misremembering. :) )

**Comment by danmosemsft** [comment] 2015-03-21 00:31
I wrote that code originally. It's likely by design, but of course feel free to change it as this was 10 years ago. 

If I remember what it is supposed to do when there is an add, is to not modify the project if the add would be included by the wildcard anyway. So if you include src\*.cs quite often MSbuild wouldn't edit it. That should still happen, if it's not then it's a regression and then it would be irritating and worth a fix for sure.

If there is a remove, it never adds Exclude for it -- as that could become messy. Instead it blows the wildcard up, and pulls that entry out. I can't remember whether it optimizes for the case where the file is deleted on disk as well, and not changing the project in that situation. Maybe it does, since it doesn't get told.

**Comment by AndyGerlicher** [comment] 2015-03-31 22:56
MSBuild team triage: We would consider this change with proper unit test coverage. This isn't a priority for us at the moment.

**Comment by gregoryyoung** [comment] 2015-03-31 22:58
@danmosemsft thanks for the background on this makes sense on the save of a removed item as well.

**Comment by jeffkl** [comment] 2016-11-16 20:26
Visual Studio 2017 will be adding support for preserving wildcard items for .NET Core projects.  This means when your project has:

``` xml
<ItemGroup>
    <Compile Include="**\*.cs" />
</ItemGroup>
```

Visual Studio will leave the wildcard in your project when saving.

I'm going to close this for now since the functionality is in Visual Studio.  We'll work with them about lighting up wildcard include support for full framework projects.

**Closed by jeffkl** 2016-11-16 20:26 UTC
Labels: up-for-grabs
