### ISSUE TITLE
IVsProjectBuildSystem.EndBatchEdit() call locking dll post package install 

### ISSUE THREAD

**Issue by mishra14** [Microsoft/msbuild#2337] opened 2017-07-20 23:10 UTC
Ported from : https://github.com/dotnet/project-system/issues/2643 based on email suggestion by @davkean 

------------------------------------------------------------------------------------------------------
Original issue: https://github.com/NuGet/Home/issues/5609

## Repro steps (besides the one in the original bug)

1. File New Project -> Windows Classic Desktop -> Class Library (.NET Framework)

2. Install Newtonsoft.Json through NuGet PM UI

## Problem

After the process of installation, NuGet invokes `IVsProjectBuildSystem.EndBatchEdit()` [here](https://github.com/NuGet/NuGet.Client/blob/a87d32b15786d47809449c69b69b1f38b3c8f1a4/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/VsMSBuildProjectSystem.cs#L607). Immediately after the package dll (lib\net45\newtonsoft.json.dll) gets locked.
This causes a problem in cases when a template (as in one from the original bug's repro steps) tries to uninstall a newly installed package. The result is that the lock on the file prevents it from being deleted or overwritten by another project's installation.

## Information 

VS: d15rel 26718.0
This seems to be a regression in the End-to-End behavior since 15.2

**Comment by mishra14** [comment] 2017-07-20 23:10
cc: @jainashish @rainersigwald

**Comment by rainersigwald** [comment] 2017-07-25 20:47
I can't reproduce this with these instructions or the original NuGet/Home#5609 instructions, on 26724.1.d15rel.

I think @mishra14 was trying to get a repro.

**Comment by rainersigwald** [comment] 2017-07-25 22:29
After looking with @mishra14, we believe this is a duplicate of dotnet/sdk#1453 for reasons described in https://github.com/NuGet/Home/issues/5609#issuecomment-317889441.

**Closed by rainersigwald** 2017-07-25 22:29 UTC
