### ISSUE TITLE
error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

### ISSUE THREAD

**Issue by lgmguto** [Microsoft/msbuild#2532] opened 2017-09-16 18:58 UTC
I'm trying to build a solution using msbuild command line and I keep getting this error:

`error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.`

The version of msbuild is the latest from microsoft visual studio 2017 tools. I'm using Windows Server 2012 R2 and the project uses .NET Core 2.0.

This is the command that I'm using:

`msbuild.exe /p:Configuration=Release /t:restore C:\Projects\MyProject.sln`

**Comment by fanicia** [comment] 2017-10-11 12:33
I fixed this by creating a path variable "MSBuildSDKsPath" with the value 
"C:\Program Files\dotnet\sdk\2.0.0\Sdks"

I don't know why msbuild can't find this path by default, but this fixed the issue for us

**Comment by DNF-SaS** [comment] 2017-10-13 12:24
Same here on Win7

**Comment by DustinCampbell** [comment] 2017-11-09 23:11
Anyone who's still having trouble here, could you try unsetting `MSBuildSDKsPath` and see if the issue still repros. If it does, could you set `COREHOST_TRACE=1`, reproduce the issue, and then paste the trace output here?

**Comment by mayconpires** [comment] 2017-11-10 03:53
@fanicia  thank you!!!

**Comment by DustinCampbell** [comment] 2017-11-10 04:42
@mayconpires : Any chance you could try setting `COREHOST_TRACE=1` per my comment above to give us some data about why this is happening?

**Comment by fanicia** [comment] 2017-11-10 07:54
@DustinCampbell i just tried unchecking the variable on one of our CI servers.... and now it works without it ??? 

I have changed a bunch of stuff on there since i wrote the comment though, so idk :P

**Comment by GreenMooseWork** [comment] 2017-11-10 08:09
I still have the issue for v`15.4.8.50001` but setting `COREHOST_TRACE=1` does not make any difference in the console output.

**Comment by fanicia** [comment] 2017-11-10 13:11
To clarify. I was also in the case where i was able to build with `dotnet build`, but `msbuild /t:rebuild` didn't work

**Comment by nguerrera** [comment] 2017-11-10 20:23
> I still have the issue for v15.4.8.50001 but setting COREHOST_TRACE=1 does not make any difference in the console output for msbuild.exe.

This suggests to me that your msbuild.exe copy does not have the following:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver

**Comment by nguerrera** [comment] 2017-11-10 20:25
Is everyone reporting this using "Build Tools for Visual Studio 2017" https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017

rather than full VS?

**Comment by nguerrera** [comment] 2017-11-10 20:32
Make sure to install the .NET Core workload:

![image](https://user-images.githubusercontent.com/75470/32677399-1b27b982-c613-11e7-8c15-efff41b8f330.png)

**Comment by nguerrera** [comment] 2017-11-10 20:37
Workload selection applies to both full VS and Build Tools

**Comment by nguerrera** [comment] 2017-11-10 20:51
Still confirming the setup authoring, but I suspect:

1. If you have Build tools SKU: you may not get any SDKs to resolve without the .NET Core tools selected.
2. If you have full VS: you can get v1.1 Microsoft.NET.Sdk, but v2.x nor Microsoft.NET.Sdk.Web at all.

**Comment by fanicia** [comment] 2017-11-10 21:03
@nguerrera I am using the buildtools, not the full VS. Meaning the .Net Core cross-platform development you have highligted

**Comment by nguerrera** [comment] 2017-11-10 21:13
> Meaning the .Net Core cross-platform development you have highligted

... are installed?

**Comment by fanicia** [comment] 2017-11-10 21:30
^yes

**Comment by nguerrera** [comment] 2017-11-10 21:32
You said it started working after changes to build machine. Is it possible the workload installation s one of those changes?

**Comment by fanicia** [comment] 2017-11-10 21:58
i dont think so. i was having trouble adding a required nuget package to the solution... will be able to give more info when im in office next week

**Comment by GreenMooseWork** [comment] 2017-11-13 09:47
@nguerrera Thanks. That was indeed our problem on server2, it was missing the .net core workload. After including it, it works fine!

**Comment by paul1956** [comment] 2017-11-29 06:31
I am using VS 2017 15.4.5 and unless I SetEnvironmentVariable's I get errors in a Test Project and the documents don't load. If I set it I still get errors loading the projects but they do load. When I build with Visual Studio I get no errors.
```
        Const SolutionPartialPath As String = "roslyn-master\src\Samples\Samples.sln"
        Const BasicCodeAnalysisPartialPath As String = "Roslyn-master\src\Compilers\VisualBasic\Portable"
        <TestMethod()> Public Sub ElementTypeUnitTestAsync()
            Dim registryKey As String
            If Environment.Is64BitProcess Then
                registryKey = "SOFTWARE\Microsoft\VisualStudio\SxS\VS7"
            Else
                registryKey = "SOFTWARE\Wow6432Node\Microsoft\VisualStudio\SxS\VS7"
            End If
            Using subKey As RegistryKey = Registry.LocalMachine.OpenSubKey(registryKey)
                Dim visualStudioPath As String = TryCast(subKey.GetValue("15.0"), String)
                If Not String.IsNullOrEmpty(visualStudioPath) Then
                    Environment.SetEnvironmentVariable("VSINSTALLDIR", visualStudioPath)
                    Environment.SetEnvironmentVariable("VisualStudioVersion", "15.0")
                    Environment.SetEnvironmentVariable("MSBuildSDKsPath", "C:\Program Files\dotnet\sdk\2.0.3\Sdks")
                End If
            End Using

            Dim myDoc As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments
            Dim SampleSolutionPath As String = Path.Combine(myDoc, SolutionPartialPath)

            Dim MS_Workspace As MSBuildWorkspace = MSBuildWorkspace.Create()
            AddHandler MS_Workspace.WorkspaceFailed, Sub(sender As Object, e As WorkspaceDiagnosticEventArgs)
                                                         Debug.WriteLine(e.Diagnostic.ToString())
                                                     End Sub
            Dim NewSolution As Solution = MS_Workspace.OpenSolutionAsync(SampleSolutionPath).Result

            For Each Project In NewSolution.Projects
                Debug.WriteLine($"Project = {Project.Name}")
                If Project.Name = "BasicCodeAnalysis" Then
                    WalkProject(Project)
                    Exit For
                End If
            Next
        End Sub
```
Some of the errors
```
C:\Users\PaulM\.nuget\packages\microsoft.net.compilers\2.3.1\tools\Microsoft.VisualBasic.Core.targets: (73, 5): The "Vbc" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.
[Failure] Msbuild failed when processing the file '...roslyn-master\src\Samples\UnitTestProject1\UnitTestProject1.vbproj' with message: The imported project "...VSIXProject2\CodeRefactoring1.Test\bin\Debug\Roslyn\Microsoft.VisualBasic.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  ...VSIXProject2\CodeRefactoring1.Test\bin\Debug\Microsoft.VisualBasic.CurrentVersion.targets
```

**Comment by venkateswaris** [comment] 2018-01-15 11:06
Hi @nguerrera 

I have visual studio Build tools installed. I am trying to  install .NET Core workload using choco. But that is failing. Is there any official page where i can download .NET Core workload?

**Comment by rainersigwald** [comment] 2018-01-16 18:35
@venkateswaris The official way to install the .NET Core workload is either through the Build Tools installer UI or its command line options. Documentation for the command line is [here](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio) and a list of workloads for the Build Tools installer is [here](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools). In your case you probably want to ensure that the `Microsoft.VisualStudio.Workload.NetCoreBuildTools` workload is installed.

**Comment by bigswede74** [comment] 2018-02-12 21:52
I'm still getting this error with all three if the fixes mentioned above.

1. Path Variable MSBuildSDKsPath
2. Build Tools for Visual Studio 2017 
3. Full Visual Studio 2017 installed with .NET Core Build Tools

[13:47:48][Step 4/9] Executing task: BuildSource
[13:47:49][Step 4/9] Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
[13:47:49][Step 4/9] Copyright (C) Microsoft Corporation. All rights reserved.
[13:47:49][Step 4/9] 
[13:47:49][Step 4/9] C:\BuildAgent\work\MyProj.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
[13:47:49][Step 4/9] An error occurred when executing task 'BuildSource'.
[13:47:49][Step 4/9] Error: One or more errors occurred.
[13:47:49][Step 4/9] 	.NET Core CLI: Process returned an error (exit code 1).
[13:47:49][Step 4/9] Process exited with code 1

**Comment by nguerrera** [comment] 2018-02-12 21:53
> 1. Path Variable MSBuildSDKsPath

@bigswede74 What is PATH and what is MSBuildSdksPath

Do you have C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver ?

**Comment by bigswede74** [comment] 2018-02-12 21:58
@nguerrera I have added the PATH MSBuildSdksPath=C:\Program Files\dotnet\sdk\2.1.4\Sdks.

I do have the SdkResolver on the file system at the location above.

**Comment by nguerrera** [comment] 2018-02-12 22:11
> @nguerrera I have added the PATH MSBuildSdksPath=C:\Program Files\dotnet\sdk\2.1.4\Sdks.

You should not need MSBuildSdksPath to be set at all.

Is C:\Program Files\dotnet\ in your PATH environment variable?

**Comment by bigswede74** [comment] 2018-02-12 22:25
@nguerrera yes I have the path variable.

**Comment by nguerrera** [comment] 2018-02-12 22:35
Try this on Visual Studio command prompt:

set COREHOST_TRACE=1
msbuild C:\BuildAgent\work\MyProj.csproj 2> resolver.log

Share resolver.log

**Comment by bigswede74** [comment] 2018-02-12 22:44
@nguerrera the resolver file is attached.

[resolver.log](https://github.com/Microsoft/msbuild/files/1717968/resolver.log)

**Comment by vcaraulean** [comment] 2018-02-20 23:00
Just a FYI, it might help somebody else.
Our setup:
 - new csproj targeting net46
 - TeamCity
 - Build failing with `error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found`

What helped:
 - Instal `.NET Core build tools`, as suggested by @nguerrera 
 - ***Restart TeamCity agent***

Without restarting the agent it will still fail...

**Comment by brunis** [comment] 2018-04-03 13:24
@nguerrera I'd prefer not to have to install .NET Core + SDK's + Runtimes just to build a .NET 4.6 class library.

**Comment by pjmagee** [comment] 2018-04-13 10:36
The only solution that worked for this was this comment: https://github.com/dotnet/docfx/issues/1752#issuecomment-323385945

**Comment by Amit-Kumar-Sonkar** [comment] 2018-07-06 13:56
**well nice job** . nguerrera .. i tried it building sln from **MSBuild.exe**
accrodingly what u have said for **installing must**..

![buildtools](https://user-images.githubusercontent.com/40666445/42382619-7dda669c-8152-11e8-9c07-c61966e82976.png)


 indeed i checked it wasn't installed
after installed and launched it worked from Developer Command 2017...

**Comment by bigswede74** [comment] 2018-07-09 16:31
I have updated the .NET Core Build Tools and still get the following error when trying to compile.

error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.

**Comment by RSuter** [comment] 2018-08-31 17:07
If this is still an issue, this may help: https://blog.rsuter.com/missing-sdk-when-using-the-microsoft-build-package-in-net-core/

**Comment by brunis** [comment] 2018-10-17 08:47
> 
> 
> I fixed this by creating a path variable "MSBuildSDKsPath" with the value
> "C:\Program Files\dotnet\sdk\2.0.0\Sdks"
> 
> I don't know why msbuild can't find this path by default, but this fixed the issue for us

How did you get that wrong path?  they are in C:\Program Files\dotnet\sdk\

**Comment by Sigvaard** [comment] 2018-11-09 19:48
I tried building my .NET Core project programmatically using `Microsoft.Build`, I got this error, after setting appropriate environment variables I got stackoverflow exception.

I tried using ` BuildManager.DefaultBuildManager`, `Project` and `ProjectInstance`.

**Comment by RSuter** [comment] 2018-11-09 20:06
When running as par ofmsbuild you need to set nobuild to false

**Comment by rainersigwald** [comment] 2018-11-19 23:34
@Sigvaard you'll probably have an easier time if you use MSBuildLocator. See https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2017.

**Comment by rainersigwald** [comment] 2018-11-19 23:35
I'm going to close this since it encompasses multiple situations; if you run into a problem with this symptom, please file a new bug with repro steps.

**Closed by rainersigwald** 2018-11-19 23:35 UTC

**Comment by Sigvaard** [comment] 2018-11-20 10:35
@rainersigwald 	I'm targeting .NET Core, MSBuildLocator targets .NET Framework 4.6 and I can't use it in my project.

**Comment by rainersigwald** [comment] 2018-11-20 14:53
@Sigvaard You'll want to follow Microsoft/MSBuildLocator#30 and Microsoft/MSBuildLocator#51 then.

**Comment by bigswede74** [comment] 2019-02-08 22:37
Why has this issue been closed, none of the fixes listed here have worked. I have tried all of them and yet I still see the error.

**Comment by nguerrera** [comment] 2019-02-08 23:13
@bigswede74 for the reason @raines stated, the same error can occur in many different circumstances. Please open a new issue and describe your full setup and repro steps. Thank you.

**Comment by dark2201** [comment] 2019-03-25 09:07
For some reason .NET Core 3 preview's MSBuild.dll breaks it again and I have to set the path (`MSBUILD_EXE_PATH`) to 2.2. (I'm using @RSuter fix). I'm using MSBuild API to load the projects and it fails if `MSBUILD_EXE_PATH` is set to 3.0 MSBuild.dll

**Comment by rainersigwald** [comment] 2019-03-25 18:45
@dark2201 Can you please open a new issue, describing the conditions you're in and the exact error? Please tag me when you do.

**Comment by mickaelistria** [comment] 2019-03-28 16:05
I ran OmniSharp with `COREHOST_TRACE=1` as suggested by @DustinCampbell and could see the following messsage
```
Searching SDK directory in [/usr/local/bin]
--- Resolving SDK version from SDK dir [/usr/local/bin/sdk]
Checking if resolved SDK dir [/usr/local/bin/sdk/-1.-1.-1] exists
It was not possible to find any SDK version
```
FWIW, on my machine, dotnet in installed in `/usr/lib64/dotnet` and has a link in `/usr/bin`.
I looked inside the `/usr/local/bin` directory and found a dead symbolic link `/opt/dotnet`. I removed the symbolic link, and MSBuild now properly resolves the SDK.

**Comment by cyberkito** [comment] 2019-08-23 10:57
I used my local installation 

> 
> 
> > 1. Path Variable MSBuildSDKsPath
> 
> @bigswede74 What is PATH and what is MSBuildSdksPath?
> 
> Do you have C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\SdkResolvers\Microsoft.DotNet.MSBuildSdkResolver ?

I used my local VS 2017 installation and copied resolver to build server to right location and problem was fixed.

**Comment by uciprian** [comment] 2019-09-16 16:58
Tried first MSBuildSdksPath no success
Updated the build tools 2017 to latest version did not work also
Copying my local VS 2017 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\SdkResolvers to build server solved for me the issue also!

Ideally an update for build tools for visual studio 2017 package should fix this

**Comment by rainersigwald** [comment] 2019-09-16 17:02
@uciprian do you have the ".NET Core Build Tools" workload enabled for your build tools installation?

**Comment by devel0** [comment] 2019-09-17 17:12
I stumbled into this problem today, building an app that use roslyn, [here](https://github.com/devel0/repros/tree/9dfd0018b73a1ee3276b796ceefdd75422d1a3e1/netcore/roslyn-01) there is a repro repository with a Dockerfile based upon mcr.microsoft.com/dotnet/core/sdk:3.0.100-rc1-bionic image.

The program tries to analyze a simple console test source and generate warning at [this line](https://github.com/devel0/repros/blob/master/netcore/roslyn-01/analyzer/Program.cs#L27), following is the execution of the docker image that can be built and run using [this script](https://github.com/devel0/repros/blob/master/netcore/roslyn-01/run.sh) contained in the repository

```
Successfully tagged repros/netcore-roslyn-01:latest
------------ENTRYPOINT
3.0.100-rc1-014190 [/usr/share/dotnet/sdk]
dotnet executable = [/usr/bin/dotnet]
PATH              = [/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]
DOTNET_ROOT       = [/usr/share/dotnet]
MSBuildSDKsPath   = [/usr/share/dotnet/sdk/3.0.100-rc1-014190/Sdks]
---> OpenProject
Msbuild failed when processing the file '/src/test/test.csproj' with message: The imported project "/app/Current/Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  /usr/share/dotnet/sdk/3.0.100-rc1-014190/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props
---> GetCompilation
has documents = False
```

**Comment by epgeroy** [comment] 2019-10-09 06:09
> I ran OmniSharp with `COREHOST_TRACE=1` as suggested by @DustinCampbell and could see the following messsage
> 
> ```
> Searching SDK directory in [/usr/local/bin]
> --- Resolving SDK version from SDK dir [/usr/local/bin/sdk]
> Checking if resolved SDK dir [/usr/local/bin/sdk/-1.-1.-1] exists
> It was not possible to find any SDK version
> ```
> 
> FWIW, on my machine, dotnet in installed in `/usr/lib64/dotnet` and has a link in `/usr/bin`.
> I looked inside the `/usr/local/bin` directory and found a dead symbolic link `/opt/dotnet`. I removed the symbolic link, and MSBuild now properly resolves the SDK.

I did all kind of stuff, this is the only thing that worked form me

**Comment by saeedtabrizi** [comment] 2019-12-06 07:15
> I ran OmniSharp with `COREHOST_TRACE=1` as suggested by @DustinCampbell and could see the following messsage
> 
> ```
> Searching SDK directory in [/usr/local/bin]
> --- Resolving SDK version from SDK dir [/usr/local/bin/sdk]
> Checking if resolved SDK dir [/usr/local/bin/sdk/-1.-1.-1] exists
> It was not possible to find any SDK version
> ```
> 
> FWIW, on my machine, dotnet in installed in `/usr/lib64/dotnet` and has a link in `/usr/bin`.
> I looked inside the `/usr/local/bin` directory and found a dead symbolic link `/opt/dotnet`. I removed the symbolic link, and MSBuild now properly resolves the SDK.

This Works Like a charm . Thanks

**Comment by cwhsu1984** [comment] 2020-03-01 13:20
add environment variables MSBuildSDKsPath with value "C:\Program Files\dotnet\sdk\2.0.0\Sdks" does not work for me.

copy SdkResolvers from local to build server works for me

**Comment by mkonars** [comment] 2020-03-03 08:48
For me it worked by running `dotnet build` instead of using `msbuild`

**Comment by atniomn** [comment] 2020-07-22 23:36
@venkateswaris 

If you install via choco, you need to include workloads you would normally include via the GUI: 

https://github.com/dotnet/msbuild/issues/2532#issuecomment-343578403

For me, I used this choco command:

```
choco install visualstudio2019buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional --passive --locale en-US"
```

**Comment by igitur** [comment] 2022-03-20 14:52
> Anyone who's still having trouble here, could you try unsetting `MSBuildSDKsPath` and see if the issue still repros. 

This solved it for me, because previously I had a mixture of standard dotnet SDK installs (via Visual Studio), but also via scoop package manager. I had since removed scoop's version, but the environment variable was still pointing to the scoop directory. Just deleting the `MSBuildSDKsPath` environment variable thus solved it for me.

It would have been nice if the tool output this:
` error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found IN THIS FREEKING DIRECTORY: C:\asdf\asdf\asdf\`

**Comment by adelriosantiago** [comment] 2022-09-06 22:44
Before adding the `MSBuildSDKsPath` env variable you might first want to see if the _dotnet.exe_ is working. You can navigate to where _dotnet.exe_ is (in my case it was "C:\Program Files\dotnet") and then execute the command you want to run. I was able to run `dotnet tool install -g csharpier` correctly after this. Adding the env variable didn't help.

**Comment by loop-evgeny** [comment] 2024-06-13 14:26
In my case this error was caused by a nearly empty SDK directory under `%ProgramFiles%\dotnet\sdk`: https://github.com/dotnet/sdk/issues/41022
