### ISSUE TITLE
.NET Core: tasks built against v14 contracts don't load on v15

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#1010] opened 2016-09-09 20:31 UTC
**Problem**
Trying to build a task using the Microsoft.Build.Utilities.Core, 14.0.0.0 contracts that will run on MSBuild 14 or 15. This works on .NET Framework version of MSBuild. The .NET Core version throws when loading the task.

**Repro**
Create a task compiled to netstandard1.3 using https://www.nuget.org/packages/Microsoft.Build.Utilities.Core/14.3.0-prerelease02
Import task via `<UsingTask>`

**Error**

> Microsoft.AspNetCore.Server.IISIntegration.Tasks.targets(27,9): error MSB4062: The "Microsoft.AspNetCore.Server.IISIntegration.Tasks.TransformWebConfig" task could not be loaded from the assembly build\netstandard1.5\Microsoft.AspNetCore.Server.IISIntegration.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Setup Info**
Using version of MSBuild in .NET Core SDK 1.0.0-preview3-003585

**Comment by jeffkl** [comment] 2016-09-09 20:49
Are you running this under MSBuild.exe?  We rely on assembly redirects in our [app.config](https://github.com/Microsoft/msbuild/blob/master/src/XMakeCommandLine/app.config).  Or is this in your own app?

**Comment by natemcmaster** [comment] 2016-09-09 20:54
I'm using `dotnet.exe build3`.

**Comment by jeffkl** [comment] 2016-09-09 21:00
Can you manually create a dotnet.exe.config next to dotnet.exe that contains this:

``` xml
<configuration>
    <runtime>
      <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.Build.Framework" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
          <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.Build" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
          <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.Build.Conversion.Core" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
          <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.Build.Tasks.Core" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
          <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.Build.Utilities.Core" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
          <bindingRedirect oldVersion="0.0.0.0-99.9.9.9" newVersion="15.1.0.0" />
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.Activities.Build" culture="neutral" publicKeyToken="31bf3856ad364e35" />
          <bindingRedirect oldVersion="4.0.0.0" newVersion="15.0.0.0" />
        </dependentAssembly>
        <dependentAssembly>
          <assemblyIdentity name="XamlBuildTask" culture="neutral" publicKeyToken="31bf3856ad364e35" />
          <bindingRedirect oldVersion="4.0.0.0" newVersion="15.0.0.0" />
        </dependentAssembly>
      </assemblyBinding>
    </runtime>
  </configuration>

```

And tell me if that works?

We definitely need this on our radar @AndyGerlicher and @rainersigwald

**Comment by natemcmaster** [comment] 2016-09-09 21:14
Here is minimal repro:
 
[tasks.zip](https://github.com/Microsoft/msbuild/files/464843/tasks.zip)

**Comment by rainersigwald** [comment] 2016-09-09 21:45
I am under the impression that .NET Core happily ignores version numbers. @natemcmaster do you have copies of the 15.1 assemblies next to your application to get loaded?

**Comment by natemcmaster** [comment] 2016-09-09 21:53
Btw, here's the stack trace:
<details>
```
"C:\Users\namc\dev\tasks\hello.proj" (default target) (1) ->
(Build target) ->
  C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018: The "SayHello" task failed unexpectedly.\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018: File name: 'Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileLoadException: Native image cannot be loaded multiple times\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)\rC:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at Microsoft.Build.Shared.CoreClrAssemblyLoader.LoadAndCache(String fullPath)\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at Microsoft.Build.Shared.CoreClrAssemblyLoader.AppContextLoad(AssemblyName assemblyName)\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at Microsoft.Build.Shared.CoreClrAssemblyLoader.Load(AssemblyName assemblyName)\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at My.Tasks.SayHello.Execute()\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r
C:\Users\namc\dev\tasks\hello.proj(4,7): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
```
</details>

@rainersigwald my task doesn't have Microsoft.Build binaries alongside the task library. I would assume custom tasks don't need to ship the Microsoft.Build.*.dll binaries. 

But hypothetically, even if tasks provide the Microsoft.Build.* contracts alongside my custom task, wouldn't this cause a problem with type unification?

**Comment by rainersigwald** [comment] 2016-09-09 21:58
Ahh, so the problem is we need to do manual type unification for our own assemblies?

@tmeschter does this sound familiar to you?

**Comment by tmeschter** [comment] 2016-09-09 22:13
This sounds like it *might* be handled by the fix I made for #750: 7d312b5d. With that change we default to asking the default `AssemblyLoadContext` to handle the load, and only look for it ourselves if that fails. That should allow everyone to end up with the same Microsoft.Build.Framework, assuming it can be loaded by the default context.

**Comment by tmeschter** [comment] 2016-09-09 22:18
@natemcmaster I think you're basically stuck until dotnet.exe picks up my fix.

**Comment by natemcmaster** [comment] 2016-09-09 23:18
Ok, will check again when the next update lands.

**Comment by natemcmaster** [comment] 2016-10-05 20:47
I just tried again with the version of MSBuild in CLI 1.0.0-preview3-003748 and I'm still getting the error.

> C:\Users\namc\dev\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration.Tasks\build\netstandard1.0\Microsoft.AspNetCore.Server.IISIntegration.Tasks.targets(29,9): error MSB4062: The "Microsoft.AspNetCore.Server.IISIntegration.Tasks.TransformWebConfig" task could not be loaded from the assembly C:\Users\namc\dev\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration.Tasks\build\netstandard1.0\Microsoft.AspNetCore.Server.IISIntegration.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Could not find or load a specific file.

**Comment by AndyGerlicher** [comment] 2016-10-05 23:10
@tmeschter the new change to assembly loading, would it resolve this? (special casing our assemblies)

**Comment by tmeschter** [comment] 2016-10-06 15:56
@AndyGerlicher I expect so, since we'll be explicitly redirecting all references to MSBuild assemblies to the ones installed with the app, regardless of version.

@natemcmaster Sorry for the bug tail on this. The behavior of the default assembly loader in .NET Core continues to defy all my expectations. :-(

**Comment by natemcmaster** [comment] 2016-10-06 16:10
@tmeschter I'm happy to help. I also had trouble with netcore assembly loading too until I read its implementation. There are almost zero docs on this subject

**Comment by muratg** [comment] 2016-10-11 16:12
**ping**

**Comment by tmeschter** [comment] 2016-10-11 16:18
The fix for this went in as commit 64fcffdfc80b512122d401061a55cdc9f74bea7c. We're now waiting for the dotnet CLI to pick up the latest MSBuild binaries.

**Comment by tmeschter** [comment] 2016-10-12 20:12
@natemcmaster I tried your repro just now. It installed the latest CLI (1.0.0-preview3-003830) and ran without issues.

**Closed by tmeschter** 2016-10-12 20:12 UTC

**Comment by Glebby** [comment] 2017-03-24 11:06
I am having the same issue trying to publish suing msbuild using msbuild supplied with VS 2017:


"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\msbuild.exe" sqlwallet.csproj /t:Publish /p:PublishProfile="SQLwalletApp - Web Deploy" /verbosity:detailed /p:Configuration=Debug /p:Password=***

The error is:

"C:\Projects\SQLwallet\SQLwallet\sqlwallet.csproj" (Publish target) (1) ->
(_TransformWebConfig target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\build\netstan
dard1.0\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(54,5): error MSB4062: The "TransformWebConfig" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\..\..\tools\net46\\Microsoft.NET.Sdk.Publish.Tasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft VisualStudio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\tools\net46\Microsoft.NET.Sdk.Publish.Tasks.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.[C:\Projects\SQLwallet\SQLwallet\sqlwallet.csproj]

The assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\tools\net46\Microsoft.NET.Sdk.Publish.Tasks.dll  is here.

Please advise.

**Comment by natemcmaster** [comment] 2017-03-24 14:47
@glebby the error you are seeing is different. Can you open an issue on https://github.com/dotnet/sdk instead?
