### ISSUE TITLE
MSbuild on .NET Core can't parse properties with commas in the values

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/msbuild#2999] opened 2018-02-15 21:43 UTC
### Steps to reproduce

This is on Ubuntu.

```
dan@danmose2:~/dotnetU$ dotnet msbuild /p:a="b,c"
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1006: Property is not valid.
Switch: c
```

### Expected  behavior

It accepts `/p:a="b,c"` as defining a property named `a` with value `b,c`.

### Actual behavior

It errors as above .  On Windows it works fine. 

On Unix if I remove the comma and use a space it is fine:
```

For switch syntax, type "MSBuild /help"
dan@danmose2:~/dotnetU$ dotnet msbuild /p:a="b c"
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  dotnetU -> /home/dan/dotnetU/bin/Debug/netcoreapp2.0/dotnetU.dll```
```
### Environment data
`msbuild /version` output:

```
dan@danmose2:~/dotnetU$ dotnet msbuild /version
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.5.179.9764dan@danmose2:~/dotnetU$
```

OS info:

```
dan@danmose2:~/dotnetU$ uname -a
Linux danmose2 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
dan@danmose2:~/dotnetU$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
dan@danmose2:~/dotnetU$
```

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
```
dan@danmose2:~/dotnetU$ dotnet --version
2.1.3
```

cc @erozenfeld

**Comment by danmosemsft** [comment] 2018-02-15 21:44
Eugene hit this when trying to pass a parameter /p:ILLinkArgs="-h LdtokenTypeMethods,InstanceConstructors"

**Comment by kasper3** [comment] 2018-02-15 22:11
Similar issue is https://github.com/Microsoft/msbuild/issues/471

The workaround is to escape the surrounding quotes `dotnet msbuild /p:a=\"b,c\"`

BTW, `dotnet msbuild /p:a="b,c"` fails for me on Windows as well..

**Comment by rainersigwald** [comment] 2018-02-15 23:08
Command line parsing is sadly different between .NET Core and full framework MSBuild, but there's another wrinkle in this case: shell escaping rules are very different on different platforms.

```sh-session
raines@raines-z220u:~$ cat show-command-line.sh 
#!/bin/sh
xargs -0 printf '%s\n' < /proc/$$/cmdline
raines@raines-z220u:~$ ./show-command-line.sh -foo "x" y="w,z" escaped=\"quotes\" 'singlequoted="doublquotes"'
/bin/sh
./show-command-line.sh
-foo
x
y=w,z
escaped="quotes"
singlequoted="doublquotes"
```

Since the invoked process can't see the quotes, I don't think we can do better there.

**Comment by danmosemsft** [comment] 2018-02-15 23:19
It's odd then that the same problem for some reason occurs on Windows.

In your example case, you can still assume `[^=]+=.+`  indicates a property and value.  The quotes have done their job, and then been stripped:

```
dan@danmose2:~/dotnetU$ ./showcmd.sh /p:aaa=b,c  d  /foo
/bin/sh
./showcmd.sh
/p:aaa=b,c
d
/foo
dan@danmose2:~/dotnetU$ ./showcmd.sh /p:aaa="b,c  d" /foo
/bin/sh
./showcmd.sh
/p:aaa=b,c  d
/foo
```

**Comment by rainersigwald** [comment] 2018-02-15 23:25
Yeah, the problem is that the comma is syntactically relevant in a `/p:` parameter

```
  /property:<n>=<v>  Set or override these project-level properties. <n> is
                     the property name, and <v> is the property value. Use a
                     semicolon or a comma to separate multiple properties, or
                     specify each property separately. (Short form: /p)
                     Example:
                       /property:WarningLevel=2;OutDir=bin\Debug\
```

So we're parsing the string in a reasonable way, but then splitting on the comma and complaining that you didn't provide a value for the `c` property. In other words we're treating `/p:a="b,c"` as equivalent to `/p:a=b /p:c` and complaining about the latter.

Also and unimportant: if you specify ` ```sh-session ` you get [syntax highlighting for unix shell sessions](https://github.com/github/linguist/blob/04e795640717460da5df9d1efab88a5f4e0ca09f/lib/linguist/languages.yml#L4291-L4302) that helps see what's command and what's output.

**Comment by danmosemsft** [comment] 2018-02-15 23:51
Ha, I never realized a comma was valid there. 

So with quotes gone, you have to decide whether `/p:a=b,c=d` was originally `/p:"a=b,c=d"` (one property `a` with value `b,c=d`) or was originally `/p:a="b",c="d"` - or no quotes at all (meaning two properties). If the ambiguity only exists if you have two `=` values it's probably pretty safe to pick the first one, and the second one always has a workaround (use `/p:a=b /p:c=d`)

Neither are this case though -- there is only one `=` so presumably you can unambiguosly treat everything after that as the property value.

Note I discovered a workaround; MSBuild escaping works here. Comma is %2c so
```
dan@danmose2:~/dotnetU$ dotnet msbuild  /p:"aaa=bbb,ccc" /v:diag | grep "ccc"
Switch: ccc
dan@danmose2:~/dotnetU$ dotnet msbuild  /p:"aaa=bbb%2cccc" /v:diag | grep "ccc"
/usr/share/dotnet/sdk/2.1.3/MSBuild.dll /Logger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/2.1.3/dotnet.dll /m /p:aaa=bbb%2cccc /v:m /v:diag ./dotnetU.csproj
                   aaa = bbb,ccc
```

**Comment by rainersigwald** [comment] 2018-02-16 15:31
I didn't either; I was getting geared up to say that this is obviously somehow different from #471 since a semicolon is significant there. Glad I double checked!

Escaping the comma/semicolon is a beautiful workaround. I'm going to pull it into #471 and mark this as a duplicate.

Duplicate of #471.

**Closed by rainersigwald** 2018-02-16 15:31 UTC

**Comment by kasper3** [comment] 2018-02-18 18:16
Another fix is https://github.com/dotnet/buildtools/pull/1917. With "$@" in Unix shell, it preserves spaces as well as quotes, comma etc.

**Comment by rainersigwald** [comment] 2018-02-20 16:16
@kasper3 I don't think that helps for comma/semicolon, because the problem isn't escaping the argument so that MSBuild gets it as a single string, but what we do with it after we have it.

**Comment by vikasillumina** [comment] 2018-08-31 06:11
@danmosemsft Your this comment:
`Note I discovered a workaround; MSBuild escaping works here. Comma is %2c `
saved me time!!

**Comment by Piedone** [comment] 2021-02-06 23:29
Could you follow up under https://github.com/NuGet/docs.microsoft.com-nuget/issues/1948, please, with the definite syntax to pass multiple values to `/p` on Windows with `dotnet build`?
