### ISSUE TITLE
msbuild is using newlines not supported by notepad when opening and saving a project file.

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#1568] opened 2017-01-13 21:45 UTC
When I open a csproj file that shows correctly in notepad using the API below and then saving it, it appears all in a single line in notepad afterwards.

Seems like msbuild is using replacing the line endings in the file with the wrong ones.

```
ProjectRootElement.Open(
                MSBuildProjectTemplatePath,
                new ProjectCollection(),
                preserveFormatting: true);

migrationSettings.MSBuildProjectTemplate.Save(outputProject);
```

**Comment by rainersigwald** [comment] 2017-01-13 21:46
Does the csproj file have a multi-line XML comment in it?

**Comment by livarcocc** [comment] 2017-01-13 21:48
no, this is the original csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by blackdwarf** [comment] 2017-01-20 16:33
@rainersigwald is there a chance to land this for CLI 1.0.0 release? The change in the APIs I mean?

**Comment by rainersigwald** [comment] 2017-01-20 16:45
@blackdwarf Not by the bar we got from management two days ago.

**Comment by blackdwarf** [comment] 2017-01-20 16:59
@rainersigwald that's ok. Will get it in after 1.0.0.

**Comment by rainersigwald** [comment] 2017-01-20 19:32
Dupe of https://github.com/Microsoft/msbuild/issues/1401 (which has explanation about the how and why).

**Closed by rainersigwald** 2017-01-20 19:32 UTC
