### ISSUE TITLE
"Private" items are showing in intellisense

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2125] opened 2017-05-23 06:14 UTC
We removed these at one point, and they are back again:

![image](https://cloud.githubusercontent.com/assets/1103906/26340646/e7c225a8-3fd2-11e7-9988-c1d5082a15cb.png)

What happened?

**Comment by rainersigwald** [comment] 2017-05-23 16:05
I don't remember removing these (they're there in VS 15.0), but it's a good idea. The comment about them says they were only there for schema validation, which isn't done any more: https://github.com/Microsoft/msbuild/blob/e3a3d6998162665ab760518d0d0f2e338394b041/src/MSBuild/Microsoft.Build.CommonTypes.xsd#L4490-L4548.

**Comment by AndyGerlicher** [comment] 2017-05-23 22:31
Team Triage:
None of us remember ever doing this. Not sure how it's a regression. It's something that we can do (again?) though.

**Comment by davkean** [comment] 2017-05-23 22:34
It was removed here: https://github.com/Microsoft/msbuild/pull/1595/files.

**Comment by davkean** [comment] 2017-05-23 22:39
What, looks like there's two versions of this file? https://github.com/Microsoft/msbuild/blob/8411705f4459fbf6eb48c7f0cda0744b820d2aba/src/MSBuild/Microsoft.Build.CommonTypes.xsd? How does this work, I see some of our changes that we made in the PR so somehow both are used?

**Comment by rainersigwald** [comment] 2017-05-24 18:47
Ok, I understand what's going on now. There were two related sections filled with underscore names. #1595 removed all of the _Properties_, but not the Items. We should do items too.

**Comment by rainersigwald** [comment] 2017-05-24 23:07
Reopening since this has to migrate to the internal repo, where localization for our XSDs happens.

**Comment by rainersigwald** [comment] 2017-06-07 15:30
This was checked into the internal VS branch d15prerel with https://devdiv.visualstudio.com/DevDiv/MSBuild/_git/VS/pullrequest/71319. The fix should start appearing in internal preview builds shortly.

**Closed by rainersigwald** 2017-06-07 15:30 UTC
