### ISSUE TITLE
[Question] CreateHardLinksForCopyLocalIfPossible and building inside Visual Studio

### ISSUE THREAD

**Issue by omariom** [Microsoft/msbuild#2717] opened 2017-11-13 14:18 UTC
`CreateHardLinksForCopyLocalIfPossible` has the following definition in `Microsoft.Common.CurrentVersion.targets`:

```xml
<!-- By default we're not using Hard Links to copy to the output directory, and never when building in VS -->
<CreateHardLinksForCopyLocalIfPossible Condition="'$(BuildingInsideVisualStudio)' == 'true' or '$(CreateHardLinksForCopyLocalIfPossible)' == ''">false</CreateHardLinksForCopyLocalIfPossible>
```

Why is it a bad idea to use `CreateHardLinksForCopyLocalIfPossible`  when building in VS?

**Comment by danmosemsft** [comment] 2017-12-07 22:43
I don't remember specifically but there likely was some circumstance where VS would take a lock on one file hardlinked to one the build is trying to modify or delete. 

If you modify that, you might find out.

**Comment by aolszowka** [comment] 2019-03-20 14:42
While this is older there is similar discussion on #3788 cross linking to bubble that up.

**Comment by rainersigwald** [comment] 2019-03-20 14:54
Duplicate of #3788

**Closed by rainersigwald** 2019-03-20 14:54 UTC
