### ISSUE TITLE
WinForm app doesn't build anymore with .NET Core 3.0 Preview 9

### ISSUE THREAD

**Issue by FabianMaurerRedheads** [microsoft/msbuild#4701] opened 2019-09-06 13:03 UTC
### Steps to reproduce

Preview9 breaks the build for me.
I get a lot of errors like
```
Error MSB3041: Unable to create a manifest resource name for "Converter\ConvertForm.resx". Could not find a part of the path 'C:\Users\USERNAME\Documents\Programming\JiraWorkbench\JiraWorkbench\JiraWorkbench.GUI\Converter\Converter\ConvertForm.cs'. (1, 1)
Error MSB3041: Unable to create a manifest resource name for "Repository\JiraForm.resx". Could not find a part of the path 'C:\Users\USERNAME\Documents\Programming\JiraWorkbench\JiraWorkbench\JiraWorkbench.GUI\Repository\Repository\JiraForm.cs'. (1, 1)

```
The Problem here seems to be that "\Converter\Converter\" is wrong, it needs to be just "\Converter\"

For more details and detailed log, please see https://github.com/dotnet/core/issues/3319

### Environment data
Using "Win10 Pro 1903" and "VS2019 16.3.0 Preview 3.0"

**Comment by rainersigwald** [comment] 2019-09-06 14:47
Thanks for the report. We're tracking this as microsoft/msbuild#4695, which has a workaround: set the property

```xml
<EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
```

In your project (or in a [`Directory.Build.props`](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-and-directorybuildtargets) for all of your projects).

**Comment by rainersigwald** [comment] 2019-09-06 14:47
Duplicate of #4695

**Closed by rainersigwald** 2019-09-06 14:47 UTC
