### ISSUE TITLE
Each MSBuild task should exist in its own AssemblyLoadContext

### ISSUE THREAD

**Issue by AArnott** [microsoft/msbuild#1754] opened 2017-02-27 02:18 UTC
Each MSBuild Task should load in its own AssemblyLoadContext. At least 3rd party tasks. This prevents build failures due to two independently developed tasks sharing a dependency but with different versions.

Also, the default AssemblyLoadContext should be very nearly empty, so that each Task can define its own dependencies instead of inheriting them from the default context. For example, Roslyn assemblies should *not* be in the default AssemblyLoadContext so that MSBuild tasks can use Roslyn assemblies of the version it was compiled against.

@tmat summarized this well after [a discussion we had in another issue](https://github.com/Microsoft/msbuild/issues/1737#issuecomment-282571709).

CC: @nguerrera

**Comment by jeffschwMSFT** [comment] 2018-08-01 20:51
cc @swaroop-sridhar

**Comment by ericstj** [comment] 2019-03-18 17:24
FYI we just hit this again here: https://github.com/dotnet/corefx/pull/36103

In that case the task was trying to use a newer NuGet than MSBuild had in its deps file.  /cc @safern @tmat

**Comment by SimonCropp** [comment] 2019-05-12 22:14
@AArnott i assume this shouldnt be a problem for strong named task assemblies? since they should be able to be loaded side-by-side?

**Comment by AArnott** [comment] 2019-05-13 12:19
@SimonCropp It is indeed a problem for strong-named assemblies. In fact all my task assemblies are always strong-named. The problem isn't just the task assembly itself, it's its whole dependency tree. And while all its dependency may be strong-name signed, the dependencies should still match exactly what the task is expecting. Some dependencies have a common assembly version across several actual versions, such that the first one would load in the CLR and the rest of the tasks that need that same dependency (but a different version) would reuse the same version as the first task asked for. That's a problem.

**Comment by jzabroski** [comment] 2019-11-05 01:16
Your ultimate test case is "turtles all the way down":

Create a `TaskRunner.exe` which loads an `interface ITask { Execute(string[] args); }` based on an `interface ITaskDefinition<T> where T : new, ITask  { Guid Key { get; set; } }`

This would allow you to correctly handle the scenario of:
1. Installing a .NET Core CLI Tool as a local tool from an MSBuild Pre-Build step
2. Running that .NET Core CLI Tool as a local tool from an MSBuild Post-Build step
  a. With support for two scenarios:
     1. Being able to reference an older version of a system dependency, such as [`System.ComponentModel.Annotations`](https://www.nuget.org/packages/System.ComponentModel.Annotations/#show-dependency-groups).  Consider my scenario, where a concrete `ITask` instance references via its implementation details the ability to provide user-friendly names for enumeration values.  **I LOVE THIS EXAMPLE** because I firmly believe Microsoft has wildly over-complicated this, and this NAILS the complexity issue.
🎉 🎂 🎁 

This is exactly the problem we run into every day.  I get more support requests in FluentMigrator for this issue than all other issues combined.

I'll try to push a sample project which demonstrates this issue.

**Comment by SimonCropp** [comment] 2019-11-05 01:24
in fody this is handled by spinning up a custom appdomain in .net and a custom load context in netcore. this domain/context is then cached per solution so that subsequent builds dont need to spin up a new domain/context. this avoids the problem with  AppDomainIsolatedTask. it forces a new appdomain for every run of the task, even if all the assemblies are the same. that and  AppDomainIsolatedTask  is not supported in netcore

i suspect the majority of msbuild tasks (that have dependencies) have the same "single appdomain" bug and they have never noticed.

i would very much like to remove this complexity from Fody.

**Comment by jzabroski** [comment] 2019-11-05 01:46
@SimonCropp Can you point me to the code you use in Fody?  I searched https://github.com/Fody/Fody/search?q=AppDomain&unscoped_q=AppDomain and I see:

1. https://github.com/Fody/Fody/blob/9236ca84a1f660b067545bf3df5882fd0c0b7a9c/FodyCommon/IsolatedAssemblyLoadContext.cs
2. https://github.com/Fody/Fody/blob/23b9e722dbd79990f3012c841f98d135f1c34e41/Fody/DomainAssemblyResolver.cs
3.  https://github.com/Fody/Fody/blob/9236ca84a1f660b067545bf3df5882fd0c0b7a9c/FodyIsolated/InnerWeaver.cs

I believe, based on your comments, you are only referring to IsolatedAssemblyLoadContext, but not to the resolution handlers you write in InnerWeaver and DomainAssemblyResolver.  I don't think putting each MSBuild task in its own AssemblyLoadContext will necessarily solve all your problems, because I think you'll end up with "private diamond dependencies" where people cannot independently separate interfaces from implementation.

BenchmarkDotNet does similar nastiness, here, in the following sequence:

1. [`BenchmarkRunnerDirty.RunWithDirtyAssemblyResolveHelper`](https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Running/BenchmarkRunnerDirty.cs)
2. [`DirtyAssemblyResolveHelper.HelpTheFrameworkToResolveTheAssembly`](https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Helpers/DirtyAssemblyResolveHelper.cs)
3. [`BenchmarkSwitcher.Run`](https://github.com/dotnet/BenchmarkDotNet/blob/2ba30330ec5ec8a9abe284c927277a6fe0fc5a0c/src/BenchmarkDotNet/Running/BenchmarkSwitcher.cs)
    - Contains this lovely comment:
      > ```c#
      > // VS generates bad assembly binding redirects for ValueTuple for Full .NET Framework
      > // we need to keep the logic that uses it in a separate method and create DirtyAssemblyResolveHelper first
      > // so it can ignore the version mismatch ;)
      > ```

**Comment by SimonCropp** [comment] 2019-11-05 01:52
@jzabroski fory has two contexts

### the root task

https://github.com/Fody/Fody/tree/master/Fody

contains no 3rd party dependencies and is loaded into the shared msbuild appdomain

loads "isolated" here https://github.com/Fody/Fody/blob/master/Fody/Processor.cs#L128

contexts are cached per sln in a dictionary https://github.com/Fody/Fody/blob/master/Fody/Processor.cs#L27

### an isolated part 

https://github.com/Fody/Fody/tree/master/FodyIsolated

can ref and load any 3rd part assemblies

note that fody is also a plugin based model. so the above give isolation for any weavers as well https://github.com/Fody/Home/blob/master/pages/addins.md

**Comment by neuecc** [comment] 2020-01-06 14:25
I've encountered (maybe) related issues.

when using `MessagePack.MSBuild.Tasks` and `MagicOnion.MSBuild.Tasks` which are custom task both using `Microsoft.CodeAnalysis.CSharp`

```xml
  <Target Name="GenerateMessagePack" AfterTargets="Compile">
    <MessagePackGenerator Input=".\ChatApp.Shared.csproj" Output="..\ChatApp.Unity\Assets\Scripts\Generated\MessagePack.Generated.cs" />
  </Target>
  <Target Name="GenerateMagicOnion" AfterTargets="Compile">
    <MagicOnionGenerator Input=".\ChatApp.Shared.csproj" Output="..\ChatApp.Unity\Assets\Scripts\Generated\MagicOnion.Generated.cs" />
  </Target>
```

`dotnet build` shows following error.
```
Could not load file or assembly 'Microsoft.CodeAnalysis.CSharp, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. 
```

because `MessagePack.MSBuild.Tasks` depends `Microsoft.CodeAnalysis.CSharp 3.1.0` but `MagicOnion.MSBuild.Tasks` depends `3.4.0`.

for workaround, I've adjusted to use same version, it works.
But this versioning hell is painful.

**Comment by rainersigwald** [comment] 2020-01-06 16:28
@neuecc Yeah, that problem should be resolved by this change. If you put a sample project up somewhere, I can confirm by testing #4916 against it before merging.

**Comment by neuecc** [comment] 2020-01-07 08:03
@rainersigwald thanks, I've pushed sample repo here https://github.com/neuecc/MSBuildAssemblyLoadIssue

**Comment by rainersigwald** [comment] 2020-01-08 20:01
@neuecc Thanks!

**Closed** 2020-01-09 23:52 UTC

**Comment by jzabroski** [comment] 2024-10-02 01:04
> (That's with MSBuild from my PR)

@rainersigwald I'm a little lost as to what the fix for this was?  I am running into an issue using FluentMigrator.MSBuild 6.1.0 (I am the author of this package, and the csproj file is based on the MSBuild guidance here: https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022#optional-support-multitargeting).  I get `error : While executing migrations the following error was encountered: Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

I think the fix was to simply let MSBuild provide the _main `Microsoft.Build*` assemblies_? In which case, what should I do to get System.ComponentModel.Annotations to resolve?  I'm currently selecting netstandard2.0 as the target framework.  It seems like I have to select net8.0?

**Comment by rainersigwald** [comment] 2024-10-02 13:40
@jzabroski please start a new issue for that.
