### ISSUE TITLE
Intermittent CI Failure: TimeoutFailsEvenWhenExitCodeIsIgnored

### ISSUE THREAD

**Issue by BenVillalobos** [microsoft/msbuild#5510] opened 2020-07-13 19:11 UTC
Build #20200710.12 had test failures
5 errors / 0 warnings

Microsoft.Build.UnitTests.Exec_Tests.TimeoutFailsEvenWhenExitCodeIsIgnored
Assert.Equal() Failure\nExpected: 143\nActual:   259

**Comment by rainersigwald** [comment] 2020-07-15 15:42
Duplicate of #5506

**Closed by rainersigwald** 2020-07-15 15:42 UTC
Labels: Area: Our Own Build
