### ISSUE TITLE
Build hangs with large number of files in wwwroot

### ISSUE THREAD

**Issue by mattwoberts** [Microsoft/msbuild#2509] opened 2017-09-11 11:38 UTC
Using:

      Microsoft (R) Build Engine version 15.3.0.0 (d15.3/17f02c2 Thu Jul 20 17:04:26 EDT 2017) for Mono

On Mac OS Sierra, I'm trying to `msbuild webapp.csproj` - this is a .net core 2.0 web app. This works without issue. However, if I add my avatar folder, which contains 5000 images, into my wwwroot folder (`wwwroot/images/Avatars`), and then try to build again, it hangs. This seems to be a file globbing issue. 

If I then add:

    <EnableDefaultItems>False</EnableDefaultItems>

To my .csproj, it again compiles, but then I'm missing the default items, and also I do want my avatar images to be added as content.

**Comment by cdmihai** [comment] 2017-09-21 22:44
Closing as duplicate of #2392

**Closed by cdmihai** 2017-09-21 22:44 UTC
