### ISSUE TITLE
Embedded resources with extension other than *.resx are named incorrectly if a source code file with the same name is present(.NET Core 3.0 release)

### ISSUE THREAD

**Issue by aerworker** [microsoft/msbuild#4761] opened 2019-09-25 16:24 UTC
[ConsoleApp1.zip](https://github.com/microsoft/msbuild/files/3653491/ConsoleApp1.zip)
### Steps to reproduce

Build and run attached application.
```
dotnet build ConsoleApp1.csproj
bin\Debug\netcoreapp3.0\ConsoleApp1.exe
```
Note that SomeFile3.cs is depended upon SomeFile3.SomeExtension.
Project file
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SomeFile1.SomeExtension" />
    <None Remove="SomeFile2.SomeExtension" />
    <None Remove="SomeFile3.SomeExtension" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SomeFile1.SomeExtension" />
    <EmbeddedResource Include="SomeFile2.SomeExtension" />
    <EmbeddedResource Include="SomeFile3.SomeExtension" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="SomeFile3.cs">
      <DependentUpon>SomeFile3.SomeExtension</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
```
Directory contents:
```
/
-Program.cs
-SomeClass1.cs
-SomeClass1.resx
-SomeFile1.SomeExtension
-SomeFile2.cs
-SomeFile2.SomeExtension
-SomeFile3.cs
-SomeFile3.SomeExtension

```
### Expected  behavior
program output should include:
```
ConsoleApp1.SomeClass1.resources
ConsoleApp1.SomeFile1.SomeExtension
ConsoleApp1.SomeFile2.SomeExtension
ConsoleApp1.SomeFile3.SomeExtension
```
or at least 
```
ConsoleApp1.SomeClass1.resources
ConsoleApp1.SomeFile1.SomeExtension
ConsoleApp1.Class2.SomeExtension
ConsoleApp1.SomeFile3.SomeExtension
```

### Actual behavior
program output include:
```
ConsoleApp1.SomeClass1.resources
ConsoleApp1.SomeFile1.SomeExtension
ConsoleApp1.Class2
ConsoleApp1.Class3
```
### Environment data
`dotnet --version` output: 
3.0.100

**Comment by rainersigwald** [comment] 2019-09-25 16:31
Thank you for the report. Closing in favor of the copy we're actively investigating.

**Comment by rainersigwald** [comment] 2019-09-25 16:32
Duplicate of microsoft/msbuild#4740

**Closed by rainersigwald** 2019-09-25 16:32 UTC
