### ISSUE TITLE
NuGetSdkResolver fails to import the Sdk when running for the first time

### ISSUE THREAD

**Issue by MeikTranel** [Microsoft/msbuild#3592] opened 2018-08-08 09:21 UTC
### Steps to reproduce
Project file
```xml
<Project>
  <Sdk Import="My.Custom.Sdk" Version="0.1.2" />

</Project>
```

Command line
```
msbuild /bl
```
### Expected  behavior
Restore the right version of the required Sdk on build and proceed with the implicitly imported sdk inside the project

### Actual behavior
1. Execution: Restores the Sdk & fails the build:
```log
a.proj : error : C:\Program Files\dotnet\sdk\2.1.4\Sdks\My.Custom.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.
a.proj : error MSB4236: The SDK 'My.Custom.Sdk' specified could not be found.
```

2. Execution: Runs without errors

### Environment data
`msbuild /version` output:

Microsoft (R) Build Engine version 15.7.180.61344 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.7.180.61344

OS info:
Windows Server 2012 r2

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
direct MSBuild.exe call

**Comment by MeikTranel** [comment] 2018-08-10 15:42
We got some more information on this. We were able to fix it by using the exact same capitalization in the package id.
Now the question is: Aren't PackageReferences supposed to be resolved case insensitively?

**Comment by japj** [comment] 2019-04-01 11:05
I think this is a duplicate of https://github.com/NuGet/Home/issues/7817 (which is resolved)

**Comment by rainersigwald** [comment] 2019-04-01 14:03
Thanks for pointing that out, @japj!

**Comment by rainersigwald** [comment] 2019-04-01 14:03
Duplicate of #NuGet/Home#7817

**Closed by rainersigwald** 2019-04-01 14:03 UTC
