### ISSUE TITLE
MSBuild node crashes with MSB0001: Internal MSBuild Error: Items already exist 

### ISSUE THREAD

**Issue by AArnott** [Microsoft/msbuild#1853] opened 2017-03-11 15:51 UTC
MSBuild -version: 15.1.548.43366

```
git clone https://github.com/AArnott/CodeGeneration.Roslyn.git
cd CodeGeneration.Roslyn
git checkout bugrepro/msbuild/1853
cd src
msbuild /v:minimal /nologo /nr:false /m /t:restore
msbuild /v:minimal /nologo /nr:false /m


  CodeGeneration.Roslyn.Attributes -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Attributes\Debug\netstandard1.0\CodeGeneration.Roslyn.Attributes.dll
  CodeGeneration.Roslyn.Attributes -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Attributes\Debug\net40\CodeGeneration.Roslyn.Attributes.dll
  CodeGeneration.Roslyn.Attributes -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Attributes\Debug\net20\CodeGeneration.Roslyn.Attributes.dll
  CodeGeneration.Roslyn.Tests.RunBuild -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tests.RunBuild\Debug\net46\CodeGeneration.Roslyn.Tests.RunBuild.dll
  CodeGeneration.Roslyn -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn\Debug\netstandard1.3\CodeGeneration.Roslyn.dll
C:\Program Files (x86)\Microsoft Visual Studio\2017\d15rel\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\git\CodeGeneration.Roslyn\src\CodeGeneration.Roslyn.Tasks.Helper\CodeGeneration.Roslyn.Tasks.Helper.csproj]
  CodeGeneration.Roslyn.Tests.Generators -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tests.Generators\Debug\netstandard1.3\CodeGeneration.Roslyn.Tests.Generators.dll
  CodeGeneration.Roslyn.Tasks.Helper -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\net46\CodeGeneration.Roslyn.Tasks.Helper.dll
C:\Program Files (x86)\Microsoft Visual Studio\2017\d15rel\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\git\CodeGeneration.Roslyn\src\CodeGeneration.Roslyn.Tasks\CodeGeneration.Roslyn.Tasks.csproj]
  CodeGeneration.Roslyn.Tasks.Helper -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks.Helper\Debug\netcoreapp1.0\CodeGeneration.Roslyn.Tasks.Helper.dll
  CodeGeneration.Roslyn.Tasks -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks\Debug\net46\CodeGeneration.Roslyn.Tasks.dll
  CodeGeneration.Roslyn.Tasks -> C:\git\CodeGeneration.Roslyn\bin\CodeGeneration.Roslyn.Tasks\Debug\netcoreapp1.0\CodeGeneration.Roslyn.Tasks.dll
MSBUILD : error MSB4166: Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.
```

```
UNHANDLED EXCEPTIONS FROM PROCESS 35252:
=====================
3/11/2017 7:44:44 AM
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Items already exist for target ResolveReferences.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Execution.BuildResult.AddResultsForTarget(String target, TargetResult result)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48.MoveNext()
===================
3/11/2017 7:44:44 AM
Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Items already exist for target ResolveReferences.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Object[] args)
   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrow(Boolean condition, String unformattedMessage, Object arg0)
   at Microsoft.Build.Execution.BuildResult.AddResultsForTarget(String target, TargetResult result)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<RequestThreadProc>d__48.MoveNext()
===================
```

**Comment by danmosemsft** [comment] 2017-03-22 03:47
dupe of https://github.com/Microsoft/msbuild/issues/1808 ?

**Closed** 2017-05-22 17:40 UTC
