### ISSUE TITLE
 Could not load file or assembly Microsoft.Build, Version=15.1.0.0

### ISSUE THREAD

**Issue by jliglesias66** [Microsoft/msbuild#4336] opened 2019-04-26 09:21 UTC
### Steps to reproduce
Following the steps in this article https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2019
1.  Create C# project console in VS2017 with Framework 4.7.2 (I also have the VS2019 installed)
2.  Add PackageReferences (see down) in .csproj file
3.  Add next code
```c#
        static void Main(string[] args)
        {
            MSBuildLocator.RegisterDefaults();
            string projectPath = @"C:\Projects\TestProject.vbproj";
            var project = new Microsoft.Build.Evaluation.Project(projectPath);
        }
```
.csproj file
```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="16.0.461" ExcludeAssets="runtime"/>
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="16.0.461" ExcludeAssets="runtime"/>
    <PackageReference Include="Microsoft.Build.Locator" Version="1.2.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" Version="3.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="3.0.0" />
  </ItemGroup>
</Project>
```

The project compiles fine but in runtime it shows the following message: "The application is in break mode" exception "Could not load file or assembly Microsoft.Build, Version=15.1.0.0"...
What am I doing wrong?

**Comment by rainersigwald** [comment] 2019-04-26 14:14
Duplicate of Microsoft/MSBuildLocator#64

**Closed by rainersigwald** 2019-04-26 14:14 UTC
