### ISSUE TITLE
NodeProviderOutOfProc.ShutdownAllNodes throws unhandled null-reference if there's never been a build

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#2174] opened 2017-06-06 02:29 UTC
Debugging VS I found that NodeProviderOutOfProc.ShutdownAllNodes appears to null-ref if there's never been a build.

In particular, this method null-refs because ComponentHost.BuildParameters ((Microsoft.Build.Execution.BuildManager.BuildParameters) is "null":

``` C#
        /// <summary>
        /// Shuts down all of the managed nodes permanently.
        /// </summary>
        public void ShutdownAllNodes()
        {
            ShutdownAllNodes(NodeProviderOutOfProc.GetHostHandshake(ComponentHost.BuildParameters.EnableNodeReuse), NodeProviderOutOfProc.GetClientHandshake(), NodeContextTerminated);
        }
```

```
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Build
  StackTrace:
   at Microsoft.Build.BackEnd.NodeProviderOutOfProc.ShutdownAllNodes() in E:\A\_work\30\s\src\Build\BackEnd\Components\Communications\NodeProviderOutOfProc.cs:line 181
	Microsoft.Build.dll!Microsoft.Build.BackEnd.NodeProviderOutOfProc.ShutdownAllNodes() Line 180	C#
 	Microsoft.Build.dll!Microsoft.Build.BackEnd.NodeManager.ShutdownAllNodes() Line 185	C#
 	Microsoft.Build.dll!Microsoft.Build.Execution.BuildManager.ShutdownAllNodes() Line 728	C#
 	Microsoft.VisualStudio.CommonIDE.dll!Microsoft.VisualStudio.CommonIDE.BuildManager.BuildManagerAccessor.Shutdown()	Unknown
 	Microsoft.VisualStudio.CommonIDE.dll!Microsoft.VisualStudio.CommonIDE.BuildManager.BuildManagerPackage.ShutdownEventHandlers()	Unknown
 	Microsoft.VisualStudio.CommonIDE.dll!Microsoft.VisualStudio.CommonIDE.BuildManager.BuildManagerPackage.Dispose(bool disposing)	Unknown
 	Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.Close()	Unknown
```

Looking through the code, this appears to occur when there's never been a build before - which can happen when you load a project, but it fails to load - then you close VS.

**Comment by KirillOsenkov** [comment] 2018-01-17 22:22
I wonder if https://github.com/Microsoft/msbuild/issues/1467 is the same issue.

**Comment by rainersigwald** [comment] 2018-03-21 19:54
Duplicate of #1467

**Closed by rainersigwald** 2018-03-21 19:54 UTC
Labels: bug
