### ISSUE TITLE
ProjectReference dependency analysis should respect ReferenceOutputAssembly

### ISSUE THREAD

**Issue by GaryHughes** [Microsoft/msbuild#1962] opened 2017-04-11 00:50 UTC
If I have a solution that contains a console application with a .csproj file like the this:

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
</Project>
```

And I also have a library project that uses the console application to generate a heap of C# code that gets compiled into the library like this.

```csproj
<Project Sdk="Microsoft.NET.Sdk" InitialTargets="RunGenerator">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../generator/generator.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
  <Target Name="RunGenerator">
    <Exec Command="dotnet run -p &quot;../generator/generator.csproj&quot; input output" /> 
  </Target>
</Project>
```

The build fails because the dependency analysis says that a netstandard1.4 assembly cannot reference a netcoreapp1.1 assembly. 

It would be good if the ReferenceOutputAssembly value was considered and this build succeeded so the projects could be built in the expected order without resorting to workarounds.

The following workaround almost works except when building using a solution file because generator.csproj gets built more than once and these builds usually happen concurrently which fails due to files being locked etc.

```csproj
<Project Sdk="Microsoft.NET.Sdk" InitialTargets="RunGenerator">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>
  <Target Name="RunGenerator">
    <Exec Command="dotnet build &quot;../generator/generator.csproj&quot;" />
    <Exec Command="dotnet run -p &quot;../generator/generator.csproj&quot; input output" /> 
  </Target>
</Project>
```

**Comment by dasMulli** [comment] 2017-04-11 13:39
Related: https://github.com/dotnet/sdk/issues/939

**Comment by rainersigwald** [comment] 2017-04-11 16:25
Closing this as a duplicate of dotnet/sdk#939. The long-term fix may require changes in this repo, but let's track it in one place for now.

**Closed by rainersigwald** 2017-04-11 16:25 UTC
