### ISSUE TITLE
Please expose the current instance of the msbuild project object for tasks

### ISSUE THREAD

**Issue by kingerja** [microsoft/msbuild#1443] opened 2016-12-06 02:50 UTC
There are many times we want to evaluate a given projects context during the execution of one of it's task.
This allows us to have enforcement tools like projectcop that prevent devs from improper project authoring which can reduce all sorts of tricky hard to diagnose build synchronization issues and other nasty breaks.

However getting access to the running instance of the project object since it is not exposed is a complicated ordeal that makes things very difficult.  
Some times a task will need to run and load a project under a given context but to do this properly it would need to know what the globalproperties are for that build episode so it can evaluate that new project properly.  
Other reasons are to simply look at the current context is and execute business logic based off that.

Anyway not having this has been a huge frustration over the years.

**Comment by rainersigwald** [comment] 2016-12-06 04:08
This would badly break the best abstraction MSBuild provides to keep a build process from doing arbitrary, unreproducible self-transformations. A task is a pure function of its inputs (and the state of the file system, which admittedly stretches the definition of "purity" a bit). It should stay that way.

**Comment by kingerja** [comment] 2016-12-07 23:24
Hmm so we use these project diagnostic tools to reason about the build episode as a whole to identify and correct arbitrariness practices that creep into the build.  Such as synchronization issues that result in build breaks or worse the silent pass.

Would you be willing to compromise and have the project obj there but only accessible through reflection instead of the insane voodoo (will building multi proc) required to fetch it currently.

We could get away with out the project object if we were able to get the context required to evaluate the project in the same manner the build episode is such as by having access to the globalproperties that were used.

**Comment by jeffkl** [comment] 2016-12-12 16:28
I spoke with Josh and we're going to address this when we develop ProjectCop.  The issue is that ideally this sort of analysis would happen as part of a build (Task) but those constructs don't have access to the whole build episode.  The analysis engine needs to know what properties were passed so it can get the full project closure.  So we'll need a good way for the analysis engine to get to that.

**Comment by rainersigwald** [comment] 2019-10-21 20:56
Team triage: uncommon request with reasons against. Closing won't-fix.

**Closed by rainersigwald** 2019-10-21 20:56 UTC
