### ISSUE TITLE
Building a solution with project dependency give inconsistent behavior between VS and dotnet build

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#3323] opened 2018-05-17 16:46 UTC
_From @nascosto on May 17, 2018 15:9_

## Steps to reproduce
* Create a solution with two projects, one netstandard2.0 and one netcoreapp2.1.
* Add the netcoreapp2.1 project as a Project Dependency to the netstandard2.0 project in the solution. Do NOT add the netcoreapp2.1 as a Reference in the netstandard2.0 csproj (this would obviously be an error). I'm just trying to control build order of the projects.
* run dotnet build/msbuild on the solution

## Expected  behavior
Building the solution from Visual Studio and running dotnet build on the solution have the same behavior.

## Actual behavior
The solution builds successfully from Visual Studio, but using dotnet build it throws an error saying that the netcoreapp project cannot be referenced by a project that targets netstandard.

## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetC
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetC
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

_Copied from original issue: dotnet/cli#9304_

**Comment by livarcocc** [comment] 2018-05-17 16:46
This seems like an issue with the metaproj generated by msbuild. Moving the issue to msbuild. If that's not the case, please just re-activate this one.

**Comment by rainersigwald** [comment] 2018-05-17 17:03
Duplicate of #1915. You can use https://github.com/Microsoft/msbuild/issues/2661#issuecomment-338808156 as a workaround until we can derive a full fix.

**Closed by rainersigwald** 2018-05-17 17:03 UTC
