### ISSUE TITLE
Difference when building VS project in VS and msbuild

### ISSUE THREAD

**Issue by fengzhi09** [microsoft/msbuild#1539] opened 2017-01-11 02:37 UTC
I have a solution contains a,b,c 3 projects. c is rely on b and a. b is rely on a.  
I have set a,b properties copy local false.  
I start to rebuild c in vs ,result is exact what i want.  
but when i build with msbuild command, like this:  
_`msbuild c.csproj /target:Rebuild /nologo /property:Configuration=Release;OutDir="output" /clp:NoSummary /verbosity:minimal`_ 
In OutDir , a,b comes . it's strange.

**Comment by rainersigwald** [comment] 2020-02-10 21:50
Duplicate of #1054

**Closed by rainersigwald** 2020-02-10 21:50 UTC
