### ISSUE TITLE
Embedded Resources failure with .NET Core 3.0 RC1

### ISSUE THREAD

**Issue by matkoch** [microsoft/msbuild#4742] opened 2019-09-17 23:24 UTC
Sample repo is here: https://github.com/matkoch/msbuild-embedded-resource-bug

Relevant csproj definitions are here: https://github.com/matkoch/msbuild-embedded-resource-bug/blob/master/ConsoleApp3/ConsoleApp3.csproj#L9-L12

> Microsoft.CSharp.CurrentVersion.targets(100, 9): [MSB3041] Unable to create a manifest resource name for "templates/Build.cs". Could not find a part of the path '/Users/matt/code/ConsoleApp3/ConsoleApp3/templates/templates/Build.cs'.

Note that `templates` directory gets added twice to the path. This worked with 3.0.100-preview8-013656 at least.

**Comment by rainersigwald** [comment] 2019-09-18 14:27
This should be fixed after rc1.

**Comment by rainersigwald** [comment] 2019-09-18 14:29
Duplicate of #4695

**Closed by rainersigwald** 2019-09-18 14:29 UTC
