### ISSUE TITLE
Directory.Build.targets is not imported when specifying msbuild target

### ISSUE THREAD

**Issue by Kieranties** [Microsoft/msbuild#2343] opened 2017-07-21 10:16 UTC
## Setup

At the root of my repo I have a `Directory.Build.props` containing:
```xml
<Project>
    <PropertyGroup>
        <CustomMessage>Hello!</CustomMessage>
    </PropertyGroup>
</Project>
```

I also have a `Directory.Build.targets` containing:
```xml
<Project>
    <Target Name="SimpleMessage" BeforeTargets="Build">
        <Message Text="My Message is => $(CustomMessage)" Importance="high" />
    </Target>
</Project>
```

## Issue
When the target is invoked directly, using `dotnet build /t:SimpleMessage` or `dotnet msbuild /t:SimpleMessage` the target cannot be found
```
C:\Code\Example\src\Example\bin\Debug\net462\Example.csproj : error MSB4057: The target "SimpleMessage" does not exist in the project.
```
## Expected
I would expect the target to be discovered and invoked.

## Aside
When invoking `dotnet build` the `SimpleMessage` target is fired before a build:
```
My Message is => Hello!
Example -> C:\Code\Example\src\Example\bin\Debug\net462\Example.dll
```

If I move the target from the *.targets file to the *.props file, the direct invocation works.

After running `dotnet msbuild .\src\Example\Example.csproj /pp:out.xml` I can see in the out.xml that `Directory.Build.props` was imported but `Directory.Build.targets` was not

**Comment by ltobiasg** [comment] 2019-03-15 18:36
I had this same problem as well, as a workaround I included this:
  <Import Project="$(MSBuildBinPath)\Microsoft.Common.targets"/>

**Comment by rainersigwald** [comment] 2019-03-15 19:16
Can either of y'all share a repro? I just tried with on @Kieranties  and didn't see any problems:

```
S:\repro\Microsoft\msbuild\issues\2343>dotnet msbuild /t:SimpleMessage
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  My Message is => Hello!
```

> I had this same problem as well, as a workaround I included this:
> 
> ```
>   <Import Project="$(MSBuildBinPath)\Microsoft.Common.targets"/>  
> ```

This is generally not a good idea--that import should be handled for you by an Sdk import.

**Comment by Kieranties** [comment] 2019-03-15 20:23
I had this issue close to two years ago... It'll be good if it's been fixed through changes since then. I'll double check this weekend.

**Comment by ltobiasg** [comment] 2019-03-15 20:48
My setup is different, but the symptoms are the same. The Directory.Build.props file is being imported, but the Directory.Build.targets file is not. 

I am not referencing an SDK, but importing the Project Microsoft.Common.CurrentVersion.targets directly. Below is the content of my project file. The Publish target is being overwritten in the Directory.Build.targets file and to trigger I am calling `dotnet publish --no-build --no-restore`

The Directory.Build.props file is always being imported, but the .targets file wasn't importing unless I did an explicit import of Common.targets

```
<Project>
  <PropertyGroup>
    <!-- Required until this bug is fixed: https://github.com/dotnet/cli/issues/9477 -->
    <DefaultProjectTypeGuid>FAE04EC0-301F-11D3-BF4B-00C04F79EFBC</DefaultProjectTypeGuid>
    <!-- Required for ResolveReferences target -->
    <OutputPath>.</OutputPath>
  </PropertyGroup>
  <!-- This is required because Directory.Build.targets is not being imported from CurrentVersions    -->
  <Import Project="$(MSBuildBinPath)\Microsoft.Common.targets"/>  
  
  <Import Project="$(MSBuildExtensionsPath)\$(NETCoreSdkVersion)\Microsoft.Common.CurrentVersion.targets" />
  <!-- Required by target ResolveReferences -->
  <Target Name="CreateManifestResourceNames"/>
  <Target Name="CopyFilesToOutputDirectory" />
  <Target Name="CoreCompile"/>
  <Target Name="_ForceResolveReferences" DependsOnTargets="ResolveReferences" BeforeTargets="Publish" />
</Project>
```

**Comment by livarcocc** [comment] 2019-03-19 17:33
@itobiasg this seems expected to me. Directory.Build.targets is explicitly imported by Microsoft.Common.targets. If you don't have that in your project, then Directory.Build.targets will not be imported. In the case of SDK style projects, that target gets imported by the SDK which leads to Directory.Build.targets then being imported as well.

By the way, this is documented here: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017.

Given that, I am going to close this bug as by design (and fixed in the original filling of the bug).

**Closed by livarcocc** 2019-03-19 17:33 UTC

**Comment by Kieranties** [comment] 2019-03-19 19:04
Apologies that I took longer to reply.  I'm happy to confirm that I've been unable to replicate the issue now.
I checked with using sdk version 2.0.0 via global.json (msbuild 15.3.409.57025) and could not replicate the issue with there either.
