### ISSUE TITLE
GenerateBindingRedirects uses unnecessarily long intermediate file path, resulting in PathTooLongException

### ISSUE THREAD

**Issue by tmat** [Microsoft/msbuild#2255] opened 2017-06-29 01:25 UTC
This is the intermediate path construction:

```xml
<_GenerateBindingRedirectsIntermediateAppConfig>$(IntermediateOutputPath)$(MSBuildProjectFile).$(TargetFileName).config</_GenerateBindingRedirectsIntermediateAppConfig>
```

Resulting to paths like:

```
...\Debug\obj\Microsoft.VisualStudio.ProjectSystem.CSharp\net46\Microsoft.VisualStudio.ProjectSystem.CSharp.csproj.Microsoft.VisualStudio.ProjectSystem.CSharp.dll.config
```

This should be already unique since the build outputs ```$(TargetFileName)``` to the same intermediate directory:

```
$(IntermediateOutputPath)$(TargetFileName).config
```

**Comment by tmat** [comment] 2017-06-29 01:26
@nguerrera FYI

**Comment by rainersigwald** [comment] 2017-06-29 01:28
Duplicate of #1786.

**Closed by rainersigwald** 2017-06-29 01:28 UTC
