### ISSUE TITLE
Allow declaring properties using attributes rather than elements

### ISSUE THREAD

**Issue by kzu** [Microsoft/msbuild#1772] opened 2017-03-01 15:52 UTC
Item metadata in 15.0 can now use the much more concise attribute syntax like so:

`<Content Include="..." CopyToOutputDirectory="PreserveNewest" />`

Properties, however, are still stuck with verbose element syntax. 

It would be great if properties could be declared as attributes on a `PropertyGroup`, like so:

```xml
<PropertyGroup Condition="'$(Configuration)' == 'Debug'"
               OutputPath="bin\Debug"
               DebugType="full"
               DebugSymbols="true" />
```

This would bring parity in concise notation between items and properties.

**Comment by rainersigwald** [comment] 2017-03-01 15:57
I know I told you to file this, but I just realized it's a duplicate of #820. Sorry!

**Closed by rainersigwald** 2017-03-01 15:57 UTC
