### ISSUE TITLE
Create Map for string reflection in Expander.cs

### ISSUE THREAD

**Issue by Forgind** [microsoft/msbuild#4738] opened 2019-09-17 17:17 UTC
Currently works by a series of if/else if statements (linear search). Storing these data in a map from function name to function would make it more efficient to access any particular string name, and the corresponding function can be taken from it afterwards. It would be good to try a few types of maps (based on hashing, based on a tree, etc.) to find which is optimal.

Something like:
TreeMap<string, fun> map = new TreeMap<string, fun>();
map.Put("copy", string.Copy);
...
if (TryGetArg(args, out string arg0))
{
    func = map.Get(_methodMethodName);
    returnVal = func(arg0);
    return true;
}

This is a further optimization I recommended in #4731

**Comment by rainersigwald** [comment] 2019-09-17 17:52
Duplicate of #2217

**Closed by rainersigwald** 2019-09-17 17:52 UTC

**Comment by rainersigwald** [comment] 2019-09-17 17:53
This is a good idea but substantially more complicated than described because we need to dispatch based not just on extracted function name but also argument types. #2217 describes the problem in detail.

**Comment by Forgind** [comment] 2019-09-17 23:42
I admit mine was something of a toy example for exactly the reason you described, but it would not be unduly complicated to either split first by argument or take the function that comes out of the map, access its parameters and their types, and search for arguments accordingly. I also don't see how it's closely related to #2217, since that focuses more on fixing big problems in certain places rather than a small but global improvement.

**Comment by rainersigwald** [comment] 2019-09-18 14:43
Unless this starts showing up in profiles as a hot area, I'd prefer to avoid making the implementation more complex for theoretical gains, since the whole thing should be deleted with a systematic fix to #2217. Right now property-function calls are only an observable problem when calling methods that aren't in the "fast path" list; lookups in that list don't seem to be important.
