### ISSUE TITLE
XML documentation file is malformed when method has C# 7 tuples as parameters.

### ISSUE THREAD

**Issue by VictorGavrish** [microsoft/msbuild#1917] opened 2017-03-28 08:45 UTC
I have a [NuGet package](https://github.com/VictorGavrish/TupleExtensions) that leverages C# 7 tuples. However, the XML documentation doesn't work, because the documentation file produces wrong member names for methods that have tuple parameters.

For example, a method like this:

```csharp
public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<(TKey key, TValue value)> source)
```

...produces XML documentation like this:
```xml
<member name="M:TupleExtensions.TupleLinqExtension.ToDictionary``2(System.Collections.Generic.IEnumerable{System.})">
    ...
</member>
```

Which doesn't work when the NuGet package is imported into a project.

**Comment by dsplaisted** [comment] 2017-03-29 04:56
This may be a Roslyn issue, as it's the compiler that creates the xml documentation file.

**Comment by rainersigwald** [comment] 2020-02-18 22:55
Duplicate of https://github.com/dotnet/roslyn/issues/18274

**Closed by rainersigwald** 2020-02-18 22:55 UTC
