### ISSUE TITLE
Regression in property expansion

### ISSUE THREAD

**Issue by radical** [Microsoft/msbuild#1824] opened 2017-03-08 21:13 UTC
Consider this scenario:

1. You have `expansion-deps.projitems` which contains the `@(JdkIncludePath)` item group.
2. You have `expansion.props` which uses `@(JdkIncludePath)` to generate a `$(_JdkIncludePaths)` property
3. You have `expansion.projitems` which creates a *new* `@(_HostRuntime)` item group which uses
    `$(JdkIncludePath)` within the `%(_HostRuntime.CFlags)` item metadata
4. You print out `%(_HostRuntime.CFlags)`.

Incredibly, behavior differs between VS2015 and VS2017.

Note: Read `works-with-mono-4.x` as just labels for the two different cases. Reading the project files will make that clearer.

With VS2015 we get:

```
msbuild /v:minimal expansion.targets
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  CFlags: works-with-mono-4.6: -I/something -I/something-else
  CFlags: works-with-mono-4.8: -I/something -I/something-else
```

With VS2017rc4:

```
msbuild /v:minimal expansion.targets
Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.

  CFlags: works-with-mono-4.6:
  CFlags: works-with-mono-4.8: -I/something -I/something-else
```

The `%(_HostRuntime.CFlags)` value for `works-with-mono-4.8` *doesn't* use `$(_JdkIncludePaths)`. Instead, it uses `@(JdkIncludePath)`:

```xml
    <_HostRuntime Include="works-with-mono-4.8">
      <CFlags>@(JdkIncludePath->'-I%(Identity)', ' ')</CFlags>
    </_HostRuntime>
```

The project files are attached - [bxc-52673.zip](https://github.com/Microsoft/msbuild/files/828974/bxc-52673.zip).

**Comment by rainersigwald** [comment] 2017-03-08 21:56
What I find interesting about this is that the current behavior is what I would expect, since properties are expanded before items and a reference to an item in a property isn't well-formed. I have no idea what caused it to work in v14. 🤕

**Comment by borgdylan** [comment] 2017-03-09 13:19
I would go around it by evaluating the property inside the target it gets used in. Would that work @rainersigwald ?

**Comment by rainersigwald** [comment] 2017-03-09 15:06
Yes, if the property is set after item evaluation (by being done at execution time inside a target), it should work fine.

**Comment by rainersigwald** [comment] 2017-03-17 17:46
Closing this as a duplicate of #1359. Will update over there.

**Closed by rainersigwald** 2017-03-17 17:46 UTC
