### ISSUE TITLE
Turning on MSBuildTreatWarningsAsErrors breaks mbsuild 

### ISSUE THREAD

**Issue by TyOverby** [Microsoft/msbuild#2736] opened 2017-11-21 19:37 UTC
From this PR: https://devdiv.visualstudio.com/DevDiv/_git/MLS-Orchestrator/pullrequest/95212
we turned on 

```
    <MSBuildTreatWarningsAsErrors> true </MSBuildTreatWarningsAsErrors>
```
and now MSBuild crashes (only on the build server though)

```
2017-11-21T19:19:06.2462650Z [31mci-test-languageserver_1       |[0m MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2017-11-21T19:19:06.3123150Z [31mci-test-languageserver_1       |[0m System.ArgumentException: The key already existed in the dictionary.
2017-11-21T19:19:06.3154500Z [31mci-test-languageserver_1       |[0m    at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add(TKey key, TValue value)
2017-11-21T19:19:06.3428330Z [31mci-test-languageserver_1       |[0m    at Microsoft.Build.BackEnd.Logging.LoggingService.AddWarningsAsErrors(Int32 projectInstanceId, ISet`1 codes)
2017-11-21T19:19:06.3546630Z [31mci-test-languageserver_1       |[0m    at Microsoft.Build.BackEnd.RequestBuilder.ConfigureWarningsAsErrorsAndMessages()
2017-11-21T19:19:06.3666580Z [31mci-test-languageserver_1       |[0m    at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__57.MoveNext()
2017-11-21T19:19:06.3821860Z [31mci-test-languageserver_1       |[0m --- End of stack trace from previous location where exception was thrown ---
2017-11-21T19:19:06.4168330Z [31mci-test-languageserver_1       |[0m    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-11-21T19:19:06.4226170Z [31mci-test-languageserver_1       |[0m    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-11-21T19:19:06.4240770Z [31mci-test-languageserver_1       |[0m    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2017-11-21T19:19:06.4255200Z [31mci-test-languageserver_1       |[0m    at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__49.MoveNext()
```

**Comment by AndyGerlicher** [comment] 2017-11-21 22:24
Fixed in #2671, duplicate of #2667. Will ship with 15.5. Reactivate if you see in latest preview of 15.5.

**Closed by AndyGerlicher** 2017-11-21 22:24 UTC
