### ISSUE TITLE
SGen not working when `System.Buffers` is referenced?

### ISSUE THREAD

**Issue by yyjdelete** [Microsoft/msbuild#3585] opened 2018-08-07 02:27 UTC
### Steps to reproduce
Origial reported as dotnet/sdk#2456, and moved to #3583, but seems there is another issue in my orig project(net461 with portable Class Library).
Either include a project sample, attach a zipped project, or provide IDE / CLI steps to create the project and repro the behaviour. Example of a project sample:

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <GenerateSerializationAssemblies>on</GenerateSerializationAssemblies><!--1. Add this-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Buffers" Version="4.5.0" /><!--2. Add this-->
  </ItemGroup>

</Project>
```

Directory contents:(Only one file)
```cs
using System;

namespace zz
{
    public class Class1
    {
        public void XX()
        {
            var data = System.Buffers.ArrayPool<int>.Shared.Rent(0);
            System.Buffers.ArrayPool<int>.Shared.Return(data);
        }
    }
}
```

Command line
```
msbuild /bl
```
### Expected  behavior
Build success.

### Actual behavior
Build failed with: (with msbuild, or build in vs)
```
GenerateSerializationAssemblies:
  C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\sgen.exe /assembly:H:\dev\kkk\obj\Debug\net461\kkk.dll /proxytypes /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll,C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.buffers\4.5.0\ref\net45\System.Buffers.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Data.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Drawing.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.IO.Compression.FileSystem.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Numerics.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Runtime.Serialization.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.dll,C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xml.Linq.dll"
  错误: 试图加载的程序集的格式不正确: C:\Users\***\.nuget\packages\system.buffers\4.5.0\ref\net45\System.Buffers.dll。
    - 未能加载文件或程序集“file:///C:\Users\***\.nuget\packages\system.buffers\4.5.0\ref\net45\System.Buffers.dll”或它的某一个依赖项。不应出于执
  行的目的加载引用程序集。只能在仅限反射的加载程序上下文中加载引用程序集。 (异常来自 HRESULT:0x80131058)
    - 无法加载引用程序集来执行。
```
(Translated with google)
```
Error: The format of the assembly you are trying to load is incorrect: C:\Users\***\.nuget\packages\system.buffers\4.5.0\ref\net45\System.Buffers.dll.
     - Failed to load file or assembly "file:///C:\Users\***\.nuget\packages\system.buffers\4.5.0\ref\net45\System.Buffers.dll" or one of its A dependency. Should not be out of control
   The purpose of the line is to load the reference assembly. A referenced assembly can only be loaded in a reflection-only loader context. (Exception from HRESULT: 0x80131058)
     - Unable to load reference assembly to execute.
```

### Environment data
`msbuild /version` output:
```
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.8.165-preview+g1ae75f9ca5
版权所有(C) Microsoft Corporation。保留所有权利。

15.8.165.59162
```

OS info: Win10 x64 1803(17134.165)

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
`VS 15.8preview5`
`dotnet --info`:
```
dotnet --info
.NET Core SDK（反映任何 global.json）:
 Version:   2.1.400-preview-009171
 Commit:    6f5d38734b

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400-preview-009171\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.1.9 [C:\Program Files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400-preview-009171 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by rainersigwald** [comment] 2018-08-07 14:32
Duplicate of #2707

**Closed by rainersigwald** 2018-08-07 14:32 UTC
