### ISSUE TITLE
Custom build task is not called when building on solution level

### ISSUE THREAD

**Issue by shhsu** [Microsoft/msbuild#3564] opened 2018-07-30 22:35 UTC
### Steps to reproduce

Hi:

I have created a nuget package to redistribute IIS Web Manager (currently named Microsoft.IIS.WebManager.Middleware). It's a static website. There's a build task in the nuget package that would copy the website content to a project's wwwroot directory if this nuget package is imported. The example usage was (https://github.com/shhsu/IIS.WebManager/blob/shhsu/proj/src/Microsoft.IIS.WebManager.SelfHost/Microsoft.IIS.WebManager.SelfHost.csproj)

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="$(MSBuildProjectDirectory)\..\build\global.props" />
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <OutputPath>$(MSBuildProjectDirectory)\..\..\artifacts\WebManagerApp</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" version="2.1.0" />
    <PackageReference Include="Microsoft.IIS.WebManager.Middleware" Version="$(IISWebManagerVersion)" PrivateAssets="All" />
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="dotnet restore" />
  </Target>
</Project>
```

Directory contents:
See https://github.com/shhsu/IIS.WebManager/tree/shhsu/proj 

Command line
Edit the solution file `Microsoft.IIS.WebManager.sln` and re-enable building `Microsoft.IIS.WebManager.SelfHost` project (I disabled it because it didn't work as expected)
Call:
```
msbuild Microsoft.IIS.WebManager.sln
```
### Expected  behavior

The output directory `WebManagerApp` should contains a `wwwroot` directory.

### Actual behavior

The `wwwroot` directory does not exist.

NOTE: 
I was able to workaround the issue by disabling build of `Microsoft.IIS.WebManager.SelfHost` from solution.
And I would call 
```msbuild Microsoft.IIS.WebManager.sln```
and build `Microsoft.IIS.WebManager.Middleware` first, then I would build `Microsoft.IIS.WebManager.SelfHost` by itself
```
cd Microsoft.IIS.WebManager.SelfHost
dotnet restore
msbuild
```

This seem to generate the result as expected, `WebManagerApp` has the correct content in `wwwroot` directory

### Environment data
`msbuild /version` output: 15.7.177.53362

OS info:
Version	10.0.17134 Build 17134

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

**Comment by rainersigwald** [comment] 2018-07-31 19:26
Do I understand correctly that you're both building the NuGet package and referencing it inside the same build? That definitely won't work, because project imports can't be updated after it is loaded. That means:

1. The project is loaded (because the solution references it)
  a. At this time, there's no NuGet package to reference, so it's not imported.
1. The PreBuild target happens, running `dotnet restore`
  a. The _next_ time the project is loaded, it would see the now-restored package
1. The build finishes, using the project from 1, because that's the build that was started.
  a. This instance of the project doesn't have your custom target.

For your scenario, I think you'd like something like https://github.com/dotnet/sdk/issues/1151, but that doesn't currently exist.

**Comment by shhsu** [comment] 2018-07-31 19:38
I see. What you are describing is exactly my issue. You can close this issue as a duplicate then.

**Comment by rainersigwald** [comment] 2018-07-31 19:39
Duplicate of #dotnet/sdk#1151

**Closed by rainersigwald** 2018-07-31 19:39 UTC

**Comment by rainersigwald** [comment] 2018-07-31 19:40
Oh, and your workaround of building in phases sounds pretty reasonable to me, given the current state of things.
