### ISSUE TITLE
Build doesn't produce x86 symbols for /p:AppxBundlePlatforms="x86|x64"

### ISSUE THREAD

**Issue by GDreyV** [Microsoft/msbuild#3655] opened 2018-08-26 21:00 UTC
When running build with parameter /p:AppxBundlePlatforms="x86|x64" it doesn't produce x86 build symbols (appxsym). Well, really it produces but as build script calls _DeleteAppxOutputFolderIfNecessary they are removed right before building x64 version.
Here's repository to reproduce the issue: https://github.com/GDreyV/uwp-msbuild-test (it's just default empty uwp app)
Arguments used to build the app: https://github.com/GDreyV/uwp-msbuild-test/blob/master/build.cmd
Build logs: https://github.com/GDreyV/uwp-msbuild-test/blob/master/build-log.txt 
Here x86 symbols were produced: https://github.com/GDreyV/uwp-msbuild-test/blob/master/build-log.txt#L496
and here folder was cleaned up: https://github.com/GDreyV/uwp-msbuild-test/blob/master/build-log.txt#L989

**Comment by dafit07** [comment] 2018-09-20 12:57
I can confirm this issue. I have pretty much the same problem and did not manage to find a solution to this. 
Could you already find something?

**Comment by weipah** [comment] 2018-10-22 14:33
It would great if this issue would receive some attention to get fixed :/

**Comment by GDreyV** [comment] 2018-10-22 16:12
I think it's not in priority because Windows 10 x86 doesn't have much installations. Really I'm even not sure if such version still exists.

**Comment by weipah** [comment] 2018-10-24 09:08
@GDreyV but I think there are still some x86 intallations of Windows IoT core out there which run UWP apps. Also I think if someone breaks something it should be fixed, because that once worked :/

**Comment by presleymark** [comment] 2019-03-09 00:44
I have a similar issue in that building a uwp appxbundle deletes the appxsym for each bundle as it starts the build for the next platform.  In the end I am left with only symbols for the ARM platform because it was the last one built.

**Comment by presleymark** [comment] 2019-03-09 00:52
Looks like this is fixed in VS 2019...

https://developercommunity.visualstudio.com/content/problem/414551/target-deleteappxoutputfolderifnecessary-in-micros.html

**Comment by rainersigwald** [comment] 2019-03-11 16:32
Thanks for finding that @presleymark. Closing this as a duplicate of that (now-fixed) bug.

**Closed by rainersigwald** 2019-03-11 16:32 UTC
