### ISSUE TITLE
[regression] WriteCodeFragment fails if parameter includes brackets

### ISSUE THREAD

**Issue by natemcmaster** [microsoft/msbuild#1357] opened 2016-11-18 16:49 UTC
**Original customer report:** https://github.com/aspnet/Configuration/issues/555

WriteCodeFragment fails if the parameter includes matching brackets.

**Repro**
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Build">
        <ItemGroup>
            <Attr Include="TestAttribute">
                <_Parameter1>Some {value}</_Parameter1>
            </Attr>
        </ItemGroup>
        <WriteCodeFragment Language="C#" AssemblyAttributes="@(Attr)" OutputFile="attr.cs" />
    </Target>
</Project>
```

**Info:**
Using dotnet-CLI 1.0.0-preview3-004056 on Windows 10.
Doesn't repo MSBuild 14.0.

**Stack trace:**
```
  "C:\tmp\test.proj" (default target) (1) ->
       (Build target) ->
         C:\tmp\test.proj(8,9): error MSB4018: The "WriteCodeFragment" task failed unexpectedly.\r
       C:\tmp\test.proj(8,9): error MSB4018: System.FormatException: Input string was not in a correct format.\r
       C:\tmp\test.proj(8,9): error MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)\r
       C:\tmp\test.proj(8,9): error MSB4018:    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)\r
       C:\tmp\test.proj(8,9): error MSB4018:    at System.String.Format(String format, Object[] args)\r
       C:\tmp\test.proj(8,9): error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.GenerateCodeCoreClr(String& extension)\r
       C:\tmp\test.proj(8,9): error MSB4018:    at Microsoft.Build.Tasks.WriteCodeFragment.Execute()\r
       C:\tmp\test.proj(8,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r
       C:\tmp\test.proj(8,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()
```

**Comment by buvinghausen** [comment] 2017-09-25 20:03
Ran into this problem today...

**Comment by jods4** [comment] 2018-02-21 15:41
Using a fully updated VS 2017 version 15.5.7 and latest .NET Core SDK 2.1.4, I'm still running into this with my `<UserSecretId>` tag containing a GUID.

I can't believe this regression from MSBuild 15 -> 14 is still not fixed, 1.5 years later.

**Comment by AceHack** [comment] 2018-06-02 07:54
I'm now getting this issues with .NET core 2.1 docker image dotnet:2.1-sdk

**Comment by rainersigwald** [comment] 2019-11-04 21:23
Duplicate of #937

**Closed by rainersigwald** 2019-11-04 21:23 UTC
Labels: up-for-grabs
