### ISSUE TITLE
dotnet fails to build solution containing solution dependencies

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#2511] opened 2017-09-11 23:30 UTC
_From @dmuehlenhoff on August 28, 2017 6:2_

## Steps to reproduce
git clone https://github.com/dmuehlenhoff/buildorder-repro.git
dotnet build

This solution contains a NetCoreApp (BuildOrder.NetCoreApp) project and a netstandard library (BuildOrder.NetStandardLib) that has a solution dependency (not a reference!) to the NetCoreApp.

## Expected behavior
BuildOrder.NetCoreApp is built before BuildOrder.NetStandardLib. There is no parallelization, but BuildOrder.NetStandardLib waits for BuildOrder.NetCoreApp to finish building.

Visual Studio 2017 shows this behavior.

## Actual behavior
dotnet build fails with an error message

  BuildOrder.NetCoreApp -> C:\Users\dmuehlenhoff\Documents\Visual Studio 2017\Projects\BuildOrder.NetCoreApp\BuildOrder.NetCoreApp\bin\Debug\netcoreapp2.0\BuildOrder.NetCoreApp.dll
C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(87,5): error : Das Projekt "C:\Users\dmuehlenhoff\Documents\Visual Studio 2017\Projects\BuildOrder.NetCoreApp\BuildOrder.NetCoreApp\BuildOrder.NetCoreApp.csproj" hat das Ziel ".NETCoreApp,Version=v2.0". Ein Verweis von einem Projekt mit dem Ziel ".NETStandard,Version=v2.0" ist nicht möglich. [C:\Users\dmuehlenhoff\Documents\Visual Studio 2017\Projects\BuildOrder.NetCoreApp\BuildOrder.NetCoreApp\BuildOrder.NetCoreApp.csproj]

stating that a netstandard library cannot reference a .NET Core application. Which is quite correct, but this is not a reference, this is purely a build order dependency.

## Environment data
λ dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Best regards,
David

_Copied from original issue: dotnet/cli#7537_

**Comment by livarcocc** [comment] 2017-09-11 23:30
MSBuild is the one that generates the metaproj for the sln file. So, moving the issue there.

**Comment by davkean** [comment] 2017-10-10 04:20
Dupe of https://github.com/Microsoft/msbuild/issues/2274

**Closed by davkean** 2017-10-10 04:20 UTC
