### ISSUE TITLE
Can no longer use construction model without MSBuild on the path

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#1456] opened 2016-12-08 06:33 UTC
Since upgrading MSBuild builds, our unit tests are now failing in VS with:

```
Message: System.TypeInitializationException : The type initializer for 'BuildEnvironmentHelperSingleton' threw an exception.
---- System.InvalidOperationException : Could not determine a valid location to MSBuild. Try running this process from the Developer Command Prompt for Visual Studio.
```

```
     "Microsoft.Build": "15.1.262-preview5",
     "Microsoft.Build.Framework": "15.1.262-preview5",
     "Microsoft.Build.Utilities.Core": "15.1.262-preview5", 
     "Microsoft.Build.Tasks.Core": "15.1.262-preview5",
     "Microsoft.Build.Engine": "15.1.262-preview5",
```

What should we be using instead?

**Comment by davkean** [comment] 2016-12-08 06:34
@RaulPerez1

**Comment by jeffkl** [comment] 2016-12-08 06:42
Can you point me to the unit test code so I can see what they're doing?  You might need to use the runtime package which has MSBuild.exe, use a different code path that doesn't hit this exception, or we have a bug somewhere.

**Comment by davkean** [comment] 2016-12-08 07:08
https://github.com/dotnet/roslyn-project-system/blob/b22cf2e196665e747a00c60d53aba0865567f329/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests/ProjectSystem/VS/CSharpProjectCompatibilityProviderTests.cs#L30

**Comment by jeffkl** [comment] 2016-12-08 15:13
@AndyGerlicher this was caused by [this change](https://github.com/Microsoft/msbuild/pull/776/commits/ff5b487b719fb812b60ce0088014de2d9fff81cd#diff-9a30f4def835a37a7d30c1a0a70d4dd2R942) which made this code throw if you're just using our OM:

``` C#
ProjectRootElement projectRootElement = ProjectRootElement.Create();
```

It works in MSBuild 14.0. 

@davkean I've marked this as Pri 1 for RC.3, does that seem appropriate?

**Comment by davkean** [comment] 2016-12-20 22:30
Thanks find, I just want my unit tests to run again...

**Comment by davkean** [comment] 2017-01-05 04:27
How does this going? My unit tests are still broken...

**Comment by jeffkl** [comment] 2017-01-05 15:03
Sorry I forgot to update you.  This PR have addressed the issue: https://github.com/Microsoft/msbuild/pull/1482

I've confirmed that version `15.1.0-preview-000503-01` of our packages let you create new projects like your unit tests are.

**Closed by jeffkl** 2017-01-05 15:03 UTC
Labels: bug, Priority 1
