### ISSUE TITLE
error MSB4018: The "GetOutOfDateItems" task failed unexpectedly

### ISSUE THREAD

**Issue by macrolik9** [microsoft/msbuild#4226] opened 2019-03-11 22:48 UTC
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2094,5): error MSB4018: The "GetOutOfDateItems" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2094,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\Desktop\op\sippin-pp-master\Release\Total Le.22B64E67.tlog\CopyFile.read.1.tlog'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2094,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2094,5): error MSB4018:    at System.IO.File.InternalDelete(String path, Boolean checkHost)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2094,5): error MSB4018:    at System.IO.File.Delete(String path)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2094,5): error MSB4018:    at Microsoft.Build.CPPTasks.GetOutOfDateItems.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2094,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(2094,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by livarcocc** [comment] 2019-03-11 23:08
Do you have a repro for this?

**Comment by davidbuckleyni** [comment] 2019-05-11 02:00
Did u ever fix this I am getting the same >

**Comment by liuyazui** [comment] 2019-06-13 07:39
I also get this issue. 
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(185,5): error MSB4018: The "GetOutOfDateItems" task failed unexpectedly.
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(185,5): error MSB4018: System.NotSupportedException: The given path's format is not supported.
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(185,5): error MSB4018:    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(185,5): error MSB4018:    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(185,5): error MSB4018:    at Microsoft.Build.CPPTasks.MsbuildTaskUtilities.GetWildcardExpandedFileListFromMetadata(IBuildEngine buildEngine, ITaskItem item, String metadataName, Boolean convertToUpperCase)
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(185,5): error MSB4018:    at Microsoft.Build.CPPTasks.GetOutOfDateItems.Execute()
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(185,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(185,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by rainersigwald** [comment] 2019-06-13 15:31
The task that's failing is part of the C++ SDK, which is not part of this repo. Can you please file [Visual Studio Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019#report-a-problem) to report the bug to that team? Please link the feedback item here so that others can find and upvote it.

One thing that would likely be helpful in the bug report is the inputs to the task. Those are logged when the [build verbosity](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-view-save-and-configure-build-log-files?view=vs-2019#to-change-the-amount-of-information-included-in-the-build-log) is set to diagnostic.

**Comment by gvanem** [comment] 2019-07-23 07:44
@macrolik9 I'm having the exact same issue. It doesn't help that the MSbuild error messages are so damn cryptic. This is probably causes by some VSinstaller gone wild (since it installs stuff in 2 or 3 places totally disregarding previously installed locations. Yikes!).

**Comment by MLaurentys** [comment] 2019-08-29 01:31
I have the same issue.

@livarcocc  do you still need a repro?

**Comment by TomzBench** [comment] 2019-12-04 14:22
I get this error on some projects and not on others...

**Comment by rainersigwald** [comment] 2019-12-04 16:08
@TomzBench Can you please file Visual Studio feedback, ideally with the logs mentioned in https://github.com/microsoft/msbuild/issues/4226#issuecomment-501754014?

I'm going to close this because this failure appears to be caused by C++ tasks.

**Closed by rainersigwald** 2019-12-04 16:08 UTC
Labels: C++ tasks and targets

**Comment by TomzBench** [comment] 2019-12-04 16:26
Hey - It turns out my issue was related to my file path being too long!  Apparently having path strings longer than 260 chars can be a problem on Windows.  Good to know - I think it's good to leave this feedback here because I don't know how to use Visual Studio Feedback. I got this error using MSBuild via CMAKE....

**Comment by rainersigwald** [comment] 2019-12-04 16:52
@TomzBench you may also be interested in https://github.com/microsoft/msbuild/issues/53#issuecomment-459062618.

**Comment by TomzBench** [comment] 2019-12-04 17:28
@rainersigwald Awesome that this is fixed. Is a "preview" build considered a stable release? Or is there some time to wait until it's on a stable release?

**Comment by rainersigwald** [comment] 2019-12-04 17:48
That post was a while ago; the fix is in all stable releases of Visual Studio 2019 (but still requires the OS-level opt-in and has the other caveats).

**Comment by TomzBench** [comment] 2019-12-04 17:49
Ok i'll try opting in and seeing if that fixes for me, thanks
