### ISSUE TITLE
MsBuild should 'unescape' properties from the command line on all places

### ISSUE THREAD

**Issue by matthid** [microsoft/msbuild#4718] opened 2019-09-11 16:54 UTC
### Related

https://github.com/microsoft/msbuild/issues/4086
https://github.com/microsoft/msbuild/issues/3468
https://github.com/microsoft/msbuild/issues/2178

### Steps to reproduce

Originally reported here:
https://github.com/fsharp/FAKE/issues/2392

Project file
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Build">
    <UsingTask TaskName="WixAssignCulture" AssemblyFile="$(WixTasksPath)" />
    <Target Name="Build">
        <Message Text="__BEFORE__$(Arg)__AFTER__" />
        <WixAssignCulture />
    </Target>
</Project>
```

Command line
```
msbuild /p:WixTargetsPath=c:%5CCode%5Cpackages%5Cbuild%5CWiX%5Ctools%5Cwix.targets
```

### Expected  behavior

`$(WixTasksPath)` is properly unescaped, according to https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters?view=vs-2017

### Actual behavior

`$(WixTasksPath)` is not unescaped in this position. Others (like printing a message) work.

### Description

The problem is that we don't know a workaround which works "properly" in all situations we have cross platform unit tests and they start failing as soon as we disable escaping for `/` or `\`, I guess this is due to the related issues.

What is the proper way to get a string into a property over the command line which works for all special and non-special characters?

### Environment data
`msbuild /version` output:
```
$ dotnet msbuild /version
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

15.9.20.62856
```

OS info: Windows 10

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
FAKE

/cc @vbfox

**Comment by vbfox** [comment] 2019-09-11 20:15
Seem like the using task case has already been ruled out as by design as it's legacy and won't be changed in https://github.com/Microsoft/msbuild/issues/885#issuecomment-252737626 :(

**Comment by rainersigwald** [comment] 2019-09-23 20:31
Team triage: we think the reasoning from the previous won't-fix decision stands, unfortunately:

> The evaluation of UsingTask elements does not unescape the attribute under `AssemblyFile`: https://github.com/Microsoft/msbuild/blob/master/src/Build/Instance/TaskRegistry.cs#L276
> 
> Since this behaviour has been there forever, changing it could break existing code. The workaround would be to manually unescape the string in the UsingTask via the `[MSBuild]::Unescape` intrinsic property function.

**Comment by rainersigwald** [comment] 2019-09-23 20:31
Duplicate of #885

**Closed by rainersigwald** 2019-09-23 20:31 UTC
