### ISSUE TITLE
MSBuild 16.2p1 seems to have version `0.0.0.0`

### ISSUE THREAD

**Issue by jcouv** [microsoft/msbuild#4381] opened 2019-05-17 22:20 UTC
I updated my VS 2019 int preview this morning (to 16.2p1), but I'm now seeing this when I try to restore and build Roslyn:

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.2.0-pre.1.0
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************

D:\repos\roslyn>Restore.cmd
Roslyn.sln:
Developer Command Prompt for VS 16.0 is not recent enough. Please upgrade to 16.0 or build from a plain CMD window
```

This command prompt is newer than 16.0, so it should be "recent enough".
This message comes from https://github.com/dotnet/roslyn/blob/master/eng/common/tools.ps1

I think the problem stems from MSBuild.exe :
```
PS D:\repos\roslyn> $msbuildCmd = Get-Command "msbuild.exe" -ErrorAction SilentlyContinue
PS D:\repos\roslyn> $msbuildCmd

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     MSBuild.exe                                        0.0.0.0    C:\Program Files (x86)\Microsoft Visual Studio\2019\IntPreview\\MSBuild\Current\Bin\MSBuild.exe
```

A few strange things:
- looking at the file details, the version numbers seem fine:
![image](https://user-images.githubusercontent.com/12466233/57959103-0f25e200-78b7-11e9-9473-dc1c2d380ea2.png)
- running msbuild also produces a proper version number:
```
>"C:\Program Files (x86)\Microsoft Visual Studio\2019\IntPreview\\MSBuild\Current\Bin\MSBuild.exe"
Microsoft (R) Build Engine version 16.2.0-preview.19264.2+c3389964c for .NET Framework
```

**Comment by rainersigwald** [comment] 2019-05-17 22:37
Duplicate of #4380

**Closed by rainersigwald** 2019-05-17 22:37 UTC
