### ISSUE TITLE
ItemDefinitionGroups do not support metadata as an attribute

### ISSUE THREAD

**Issue by jeffkl** [Microsoft/msbuild#2233] opened 2017-06-20 20:15 UTC
Reported by @tmat

The following project fails to evaluate:

```xml
<Project>
  <ItemDefinitionGroup>
    <Compile SomeProperty="SomeValue" />
  </ItemDefinitionGroup>

  <Target Name="Build" />
</Project>
```
```
error MSB4066: The attribute "SomeProperty" in element <Compile> is unrecognized.
```
Using the older syntax works:
```xml
<Project>
  <ItemDefinitionGroup>
    <Compile>
      <SomeProperty>SomeValue</SomeProperty>
    </Compile>
  </ItemDefinitionGroup>

  <Target Name="Build" />
</Project>
```
We need to support metadata as an attribute for `ItemGroupDefinition`.

**Comment by rainersigwald** [comment] 2018-10-12 21:51
Duplicate of #3833, which has a PR out already.

**Closed by rainersigwald** 2018-10-12 21:51 UTC
Labels: Area: Language, Feature - Project File Cleanup
