### ISSUE TITLE
ItemDefinitionGroup ignores KeepMetadata and RemoveMetadata

### ISSUE THREAD

**Issue by AndyGerlicher** [Microsoft/msbuild#3248] opened 2018-04-28 03:14 UTC
Reported by a customer. Internal bug [597908](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597908)
### Steps to reproduce

Project file KeepMetadata.proj
```xml
<Project DefaultTargets="Test">

  <ItemDefinitionGroup>
    <A>
      <bar>barA</bar>
    </A>
  </ItemDefinitionGroup>
  
  <ItemGroup>
    <A Include="1" foo="foo1" />
    <A Include="2" foo="foo2" bar="bar2"/>
    <A Include="3" />
  </ItemGroup>
  
  <Target Name="Test">
    <ItemGroup>
      <B Include="@(A)" KeepMetadata="foo" />
    </ItemGroup>

    <Message Importance="high" Text="%(B.Identity) %(B.foo) %(B.bar)"/>
  </Target>
</Project>
```
Command line
```
msbuild /v:m KeepMetadata.proj
```
### Expected  behavior
```
      1 foo1
      2 foo2
      3 
```

### Actual behavior
```
      1 foo1 barA
      2 foo2 barA
      3  barA
```

Repros on MSBuild 4.0 (with no metadata as attribute of course) to 15.6.

**Comment by AndyGerlicher** [comment] 2018-04-28 03:15
@cdmihai can you spend a half hour or so max to investigate this next week? Given that it repros on 4.0 I'm not sure we even should fix it but I'd like to know if there's an obvious cause or not.

**Comment by cdmihai** [comment] 2018-05-01 21:41
Did this ever work otherwise? The code looks like this is intended behaviour: if there is no direct metadata, then item definition groups act as a fallback. This logic is duplicated in two places, once for build time, and once for evaluation:
- build: https://github.com/Microsoft/msbuild/blob/49af2b9a4fb25044121932910e67c644f407b989/src/Build/Instance/ProjectItemInstance.cs#L1226
- evaluation: https://github.com/Microsoft/msbuild/blob/fd91f9661aa90347fa292f50cbf8387dfb6d1bc2/src/Build/Definition/ProjectItem.cs#L438

**Comment by cdmihai** [comment] 2018-05-01 21:51
Test for this scenario: https://github.com/cdmihai/msbuild/commit/4e9f574f6f5b1bb254936a985cf572a3d0e233f8
Should I invert the assertions and send a pr? :)

**Comment by cdmihai** [comment] 2018-05-02 00:16
Oops, did not initially realize that B is getting its items copied from A, so one expectation would be that A's item definitions do not apply on B anymore.

The item transferring code suggests that keeping around the original item definition might still be intended behaviour: https://github.com/Microsoft/msbuild/blob/49af2b9a4fb25044121932910e67c644f407b989/src/Build/Instance/ProjectItemInstance.cs#L1887-L1892

As a test, I added item definitions for item type B that try to override A's item definition. According to the above rules, A's item definitions will win.

```xml
<Project DefaultTargets="Test">

  <ItemDefinitionGroup>
    <A>
      <AItemDefinition>A-item-definition</AItemDefinition>
    </A>
  </ItemDefinitionGroup>

  <ItemDefinitionGroup>
    <B>
      <AItemDefinition>B-item-definition</AItemDefinition>
    </B>
  </ItemDefinitionGroup>
  
  <ItemGroup>
    <A Include="1" ADirect="ADirect1" />
    <A Include="2" ADirect="ADirect2" AItemDefinition="A overriden"/>
    <A Include="3" />
  </ItemGroup>
  
  <Target Name="Test">
    <ItemGroup>
      <B Include="@(A)" KeepMetadata="ADirect" />
    </ItemGroup>

    <Message Importance="high" Text="%(B.Identity) ADirect=%(B.ADirect) AItemDefinition=%(B.AItemDefinition)"/>
  </Target>
</Project>
```

Output:
```
  1 ADirect=ADirect1 AItemDefinition=A-item-definition
  2 ADirect=ADirect2 AItemDefinition=A-item-definition
  3 ADirect= AItemDefinition=A-item-definition
```

**Closed** 2018-05-02 17:35 UTC
Labels: bug
