### ISSUE TITLE
MSBuild.exe consistently dies with "SerializationException: Unable to find assembly 'Microsoft.VisualStudio.CodeAnalysis, Version=16.0.0.0"

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#4141] opened 2019-02-06 01:34 UTC
### Steps to reproduce

1. Clone https://github.com/natemcmaster/AspNetCore/tree/6c052927ceab5b0b3ef859858e9d9a03ff11561d
1. Run `eng/scripts/InstallVisualStudio.ps1` to install Visual Studio 2019 Preview 2
2. Run `eng/scripts/cibuild.cmd`

### Expected  behavior

Build passes.

### Actual behavior

MSBuild.exe dies unexpectedly. There are two errors from different MSBuild processes.

Error 1 (as seen in console output)

```
System.Runtime.Serialization.SerializationException: Unable to find assembly 'Microsoft.VisualStudio.CodeAnalysis, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketReadTranslator.TranslateDotNet[T](T& value)
```
[MSBuild_pid-7880_52c86c928e7f44af97abd968a86486ec.failure.txt](https://github.com/Microsoft/msbuild/files/2834533/MSBuild_pid-7880_52c86c928e7f44af97abd968a86486ec.failure.txt)

Error 2 - found in MSBuild_pid-x-.failure.txt
```
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
```
[MSBuild_pid-7880_52c86c928e7f44af97abd968a86486ec.failure.txt](https://github.com/Microsoft/msbuild/files/2834531/MSBuild_pid-7880_52c86c928e7f44af97abd968a86486ec.failure.txt)

See https://dev.azure.com/dnceng/public/_build/results?buildId=88315&view=logs for example

### Environment data
`msbuild /version` output: `Microsoft (R) Build Engine version 16.0.218-preview+g5c625fa747 for .NET Framework`

OS info: Windows 10 Enterprise

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc): MSBuild.exe

**Comment by natemcmaster** [comment] 2019-02-09 01:03
Updated to a newer version. It's still happening in 16.0.360-preview+g9781d96883 for .NET Framework

@rainersigwald any thoughts on how I can investigate this more to figure out what the problem is?

**Comment by mavasani** [comment] 2019-02-09 02:16
Likely related to https://github.com/Microsoft/msbuild/issues/1675, which was fixed by https://github.com/Microsoft/msbuild/pull/4139 a day ago. But @rainersigwald can confirm.

**Comment by natemcmaster** [comment] 2019-02-10 01:25
Yes, that appears to be the problem. Manually updating msbuild.exe.config in my installation works.

**Comment by rainersigwald** [comment] 2019-02-11 15:43
Thanks for checking. That fix should ship in Preview 4.

**Comment by rainersigwald** [comment] 2019-02-11 15:44
Duplicate of #1675

**Closed by rainersigwald** 2019-02-11 15:44 UTC

**Comment by rainersigwald** [comment] 2019-02-11 22:08
If you're seeing this and would like a workaround before preview 4:

```powershell
param (
    [string]$vsInstallPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview"
)

function AddCodeAnalysis16CodeBase {
    param ([string]$filePath)

    [xml]$xmlDoc = Get-Content $filePath
    foreach ($binding in $xmldoc.configuration.runtime.assemblyBinding.dependentAssembly) {
        if ($binding.assemblyIdentity.name -in "FxCopTask", 
                    "Microsoft.VisualStudio.CodeAnalysis",
                    "Microsoft.VisualStudio.CodeAnalysis.Sdk") {
            $binding.codeBase.version = "16.0.0.0"
            $binding.codeBase.href = $binding.codeBase.href.Replace("v15.0", "v16.0")
        }
    }

    $xmlDoc.Save($filePath)

    Write-Verbose -Message "Patched $filePath"
}

AddCodeAnalysis16CodeBase (Join-Path $vsInstallPath "MSBuild\Current\Bin\MSBuild.exe.config")
AddCodeAnalysis16CodeBase (Join-Path $vsInstallPath "MSBuild\Current\Bin\amd64\MSBuild.exe.config")
```
