### ISSUE TITLE
Too many extra lines with msbuild console logger on Linux

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#2809] opened 2017-12-14 17:56 UTC
_From @pepone on December 14, 2017 10:35_

## Steps to reproduce
```
dotnet new console -o testapp
dotnet build /v:d
```

## Expected  behavior

The file logger output doesn't show this extra empty lines, compare the output of the previous command with the output of file looger

```
dotnet build /fl /flp:logfile=testapp.log;verbosity=diagnostic
```
## Actual behavior

Console output contains many empty lines making difficult to read it

## Environment data
```
dotnet --info
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

_Copied from original issue: dotnet/cli#8245_

**Comment by rainersigwald** [comment] 2017-12-20 19:54
@pepone I'm pretty sure the lines aren't blank, but printed black-on-black. In an ubuntu:17.10 docker image:

```shellsession
root@e0fe8b9463b9:/testapp# dotnet --info
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff

root@e0fe8b9463b9:/testapp# dotnet build /v:d /flp:v=d > console.log
root@e0fe8b9463b9:/testapp# diff msbuild.log console.log
0a1,3
> Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
>
```

In that case, this is a duplicate of https://github.com/Microsoft/msbuild/issues/754. That has a workaround.

If you think there's some other cause, can you let us know why?

**Closed by rainersigwald** 2017-12-20 19:54 UTC

**Comment by pepone** [comment] 2017-12-22 22:28
@rainersigwald thanks that was it indeed
