### ISSUE TITLE
Updated msbuild introduced build errors: MSB4057: The target "GetNativeManifest" does not exist in the project.

### ISSUE THREAD

**Issue by MIchaelMainer** [Microsoft/msbuild#2874] opened 2018-01-18 08:24 UTC
### Steps to reproduce

* My desktop uses 15.1.1012.6693 where I don't see *MSB4057: The target "GetNativeManifest" does not exist in the project.* I can successfully build with this setup.
* AppVeyor is using 15.5.180.51428 and I see the issue.
* My laptop uses 15.4.8.50001 and I see the same issue.

1. `git clone https://github.com/microsoftgraph/msgraph-sdk-dotnet.git`
2. Restore nuget packages.
3. Run `msbuild` or `dotnet build`.

This is the result:
```
"c:\repos\msgraph-sdk-dotnet\Microsoft.Graph.sln" (default target) (1) ->
"c:\repos\msgraph-sdk-dotnet\tests\Microsoft.Graph.Core.Test\Microsoft.Graph.Core.Test.csproj" (default target) (4) ->
"c:\repos\msgraph-sdk-dotnet\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj" (GetNativeManifest target) (3:16) ->
  c:\repos\msgraph-sdk-dotnet\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj : error MSB4057: The target "GetNativeManifest" does not exist in the project.
```

### Expected  behavior
I expect that AppVeyor and my laptop build the libraries as it has successfully in the past, as my desktop currently does.

### Actual behavior
Build fails with `error MSB4057: The target "GetNativeManifest" does not exist in the project.`

### Environment data
On the laptop: `msbuild /version` output: 15.4.8.50001

OS info: 
Desktop with 15.1.1012.6693 is on latest Windows Server (I don't have version, yet)
Laptop with 15.4.8.50001 is on Windows 10.0.16299.192

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
On the laptop: `dotnet --version` output: 2.1.4

**Comment by rainersigwald** [comment] 2018-01-18 16:28
Looks like something has introduced a bug in this scenario, which is a `net45` non-SDK project referencing a multitargeted SDK project.

In `Microsoft.Graph.Core.Test.csproj`'s `ResolveProjectReferences`, it's actually calling into the _outer_ build of `Microsoft.Graph.Core.csproj` **twice** without setting the TargetFramework correctly. But the passed-in reference item is correctly annotated with `NearestTargetFramework`. That's odd.

# Workaround

Explicitly specify the target framework that you want to use in the test project:

```diff
diff --git a/tests/Microsoft.Graph.Core.Test/Microsoft.Graph.Core.Test.csproj b/tests/Microsoft.Graph.Core.Test/Microsoft.Graph.Core.Test.csproj
index 4878a24e..c24640cc 100644
--- a/tests/Microsoft.Graph.Core.Test/Microsoft.Graph.Core.Test.csproj
+++ b/tests/Microsoft.Graph.Core.Test/Microsoft.Graph.Core.Test.csproj
@@ -112,6 +112,7 @@
     <ProjectReference Include="..\..\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj">
       <Project>{9f04608c-d845-4445-83b1-e6d4eee38cbc}</Project>
       <Name>Microsoft.Graph.Core</Name>
+      <SetTargetFramework>TargetFramework=net45</SetTargetFramework>
     </ProjectReference>
   </ItemGroup>
   <Choose>
```

**Comment by rainersigwald** [comment] 2018-01-18 16:48
Ah, after looking closer, the problem was a doubled ProjectReference. Sent https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/230 to fix that.

That makes this issue a duplicate of #2688, so I'm going to close it.

**Closed by rainersigwald** 2018-01-18 16:48 UTC
Labels: Area: Common Targets, bug, regression

**Comment by akrisiun** [comment] 2018-03-26 07:14
msbuild  version 15.5.180 also raises " target "GetNativeManifest" does not exist in the project" error.
But cause is for stupid dublicate ProjectReference item.
**IMHO, should be more user friendly error message with .csproj error line reference :-(**
.Csproj like this: 
```
  <ItemGroup>
    <ProjectReference Include="..\core\core.csproj" />
    <!-- GetNativeManifest fails? ?? no build error message?     -->
    <ProjectReference Include="..\core\core.csproj" />
    <!-- VisualStudion build fails?, uncomment here :(
    <Reference Include="core">
      <HintPath>..\core\bin\Debug\net47\core.dll</HintPath>
    </Reference>
    -->
```
I created sample solution: https://github.com/akrisiun/msbuild.ManifestProblem

# dotnet build
```
ManifestProblem\src\netexe> dotnet build -v d
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core

   1:9>Project "D:\Beta\Visual\ManifestProblem\src\netexe\netexe.csproj" (1:9) is building "D:\Beta\Visual\ManifestProblem\src\core\core.cs
roj" (2:19) on node 1 (GetNativeManifest target(s)).
  2:19>Building with tools version "15.0".
       Project file contains ToolsVersion="". This toolset may be unknown or missing, in which case you may be able to resolve this by inst
lling the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the p
oject as if it had ToolsVersion="15.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
  2:19>D:\Beta\Visual\ManifestProblem\src\core\core.csproj : error MSB4057: The target "GetNativeManifest" does not exist in the project.
  2:19>Done Building Project "D:\Beta\Visual\ManifestProblem\src\core\core.csproj" (GetNativeManifest target(s)) -- FAILED.
```

**Comment by rainersigwald** [comment] 2018-03-26 14:52
Duplicate of #2688 

(that tracks your request, @akrisiun)
