### ISSUE TITLE
MSBuildLocator can't find NuGet assemblies on netcoreapp

### ISSUE THREAD

**Issue by zivkan** [microsoft/msbuild#5241] opened 2020-04-06 13:59 UTC
### Steps to reproduce

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="16.5.0" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.2.6" />
  </ItemGroup>

</Project>
```

`Program.cs`:
```cs
using Microsoft.Build.Definition;
using Microsoft.Build.Evaluation;
using Microsoft.Build.Logging;
using System;
using System.IO;
using System.Linq;

namespace RoslynDebug
{
    class Program
    {
        static void Main()
        {
            Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults();

            var slnPath = FindSolution();

            if (slnPath == null)
            {
                Console.WriteLine("Couldn't find solution");
                return;
            }

            ProcessSolution(slnPath);
        }

        private static string FindSolution()
        {
            var dir = Environment.CurrentDirectory;

            for (; ; )
            {
                var files = Directory.EnumerateFiles(dir, "*.sln").ToList();

                if (files.Count > 0)
                {
                    return files[0];
                }

                var newDir = Path.GetDirectoryName(dir);
                if (newDir == null || newDir == dir)
                {
                    return null;
                }
                dir = newDir;
            }
        }

        private static void ProcessSolution(string slnPath)
        {
            var solution = Microsoft.Build.Construction.SolutionFile.Parse(slnPath);

            var collection = new ProjectCollection();
            var projectOptions = new ProjectOptions()
            {
                ProjectCollection = collection
            };

            foreach (var project in solution.ProjectsInOrder)
            {
                var proj = Project.FromFile(project.AbsolutePath, projectOptions);
                var targets = new[] { "build" };

                proj.Build(targets, new[] { new ConsoleLogger() });
            }
        }
    }
}
```

### Expected behavior

no errors

### Actual behavior

```text
error MSB4018: The "ProcessFrameworkReferences" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=5.6.0.2, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
error MSB4018: File name: 'NuGet.Frameworks, Version=5.6.0.2, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
error MSB4018:    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
error MSB4018:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
error MSB4018:    at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

### Environment data

No errors when app targets `net472`, only a problem when targeting `netcoreapp*`

**Comment by rainersigwald** [comment] 2020-04-06 17:01
Duplicate of microsoft/MSBuildLocator#86

**Closed by rainersigwald** 2020-04-06 17:01 UTC
