### ISSUE TITLE
Large allocation via GetEnvironmentVariables

### ISSUE THREAD

**Issue by benaadams** [Microsoft/msbuild#2402] opened 2017-08-07 03:24 UTC
`GetEnvironmentVariables` allocates a lot via new `strings` and `GetEnvironmentCharArray` 

e.g. for a Rosyln restore:

![](https://aoa.blob.core.windows.net/aspnet/getenv.png)

![](https://aoa.blob.core.windows.net/aspnet/getenv2.png)

Could these be cached rather than constantly looked up and reconstructed; with only deltas applied and removed?

/cc @davkean

**Comment by rainersigwald** [comment] 2017-08-07 15:41
Unfortunately, I'm not sure how much better we can do here.

Setting/removing environment variables is [done incrementally](https://github.com/Microsoft/msbuild/blob/27f37c5126cf99f8a86ade04cf48c1535e5e7a28/src/Shared/CommunicationsUtilities.cs#L292-L311), but it depends on knowing "what is the current, real environment?"

There's no MSBuild environment abstraction (and if there was, we couldn't enforce its use), so we can't know when user code has called `Environment.SetEnvironmentVariable` (or equivalent). I think that means we're forced to assume that the environment has changed without our knowledge, and thus check it any time we want to know the environment or enforce that the environment is what we want it to be (which we do every time a project yields or resumes in a process).

**Comment by rainersigwald** [comment] 2017-08-07 18:19
One possibility: we could maintain a dirty bit for environment state, and set it whenever we're about to call a task, and any time we manipulate the environment in the engine. That could help with overhead, especially in the calling-to-get-cached-results case. But it'd require a fair amount of discipline; I'm not sure it'd be worth it.

**Comment by AndyGerlicher** [comment] 2017-08-08 22:15
Team Triage:
Discussed the solution that @rainersigwald proposed and given the limitations of the current assumptions and requirements we are closing this (by design). The complexity of doing this partially does not seem worth it. We can reopen if we think of something.

**Comment by davkean** [comment] 2017-08-16 04:01
This is 2% of all allocations in a design-time build: 
![image](https://user-images.githubusercontent.com/1103906/29346816-4c26a19a-828b-11e7-9fad-8a7b43e4078e.png)

Are you sure there's not a better way here? Is there something from Windows that can tell us that the environment has changed?

**Comment by davkean** [comment] 2017-08-16 04:04
Overall GetEnvironmentVariables is 5.4%:

![image](https://user-images.githubusercontent.com/1103906/29346878-c5ff3a40-828b-11e7-89d6-5c33c27daabe.png)

**Comment by davkean** [comment] 2017-08-16 05:04
I think we should reopen this - I can see that we can avoid half the allocations here by avoiding the char* -> char[] -> string transition and instead go from directory from char* -> string. MSBuild has copied the BCL's implementation so there's nothing that I can see blocking that.

This will remove the following:

![image](https://user-images.githubusercontent.com/1103906/29348060-2b0f2e6a-8294-11e7-8c25-b71d17345a39.png)

**Comment by davkean** [comment] 2017-08-17 06:27
Going to reopen this for consideration as I believe there is some reduction here.

**Comment by rainersigwald** [comment] 2017-08-21 22:19
Yup, that was totally workable . . .

**Closed** 2017-08-25 18:19 UTC
Labels: performance
