### ISSUE TITLE
Target ResolveComReference returning wrong items (ReferencePath)

### ISSUE THREAD

**Issue by huizhonglong** [Microsoft/msbuild#2853] opened 2018-01-11 00:23 UTC
Target ResolveComReference (in Microsoft.Common.CurrentVersion.targets) returns wrong items

Line 2650
  <Target
      Name="ResolveComReferences"
      Condition="'@(COMReference)'!='' or '@(COMFileReference)'!=''"
      Returns="@(**ReferencePath**)"
      DependsOnTargets="PrepareForBuild;ResolveKeySource;ResolveAssemblyReferences"
  >
The return line should be replaced with this:
     Returns="@(**ComReferenceWrappers**)"

**Comment by AndyGerlicher** [comment] 2018-06-06 17:39
Duplicate of #2591

**Closed by AndyGerlicher** 2018-06-06 17:39 UTC
