### ISSUE TITLE
Unit-test fails when Windows SDK is not installed

### ISSUE THREAD

**Issue by KirillOsenkov** [Microsoft/msbuild#1656] opened 2017-02-01 22:14 UTC
The unit-test Microsoft.Build.UnitTests.ToolLocationHelper_Tests.GetUnversionedSDKUnionMetadataLocation

fails with
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Build.UnitTests.ToolLocationHelper_Tests.GetUnversionedSDKUnionMetadataLocation() in C:\MSBuild\src\Utilities\UnitTests\ToolLocationHelper_Tests.cs:line 163
...
Assert.False(returnValue.Contains("10.0.10586.0"));
```

when the Windows SDK 10586 is not installed on the machine. Should we change the test to fail with a better error message when the SDK is not installed?

This is the only unit-test that fails without it.

**Comment by rainersigwald** [comment] 2017-02-01 22:20
Dupe of #1609. Looks like other similar tests avoid the need for installation.

**Closed by rainersigwald** 2017-02-01 22:20 UTC
