### ISSUE TITLE
How Do I get MSBuild to Honor Relative Paths

### ISSUE THREAD

**Issue by CodeSwimBikeRunner** [microsoft/msbuild#4416] opened 2019-06-03 19:10 UTC
### Steps to reproduce

Create Solution Y in Folder A with Project 1
Create Solution Z in Folder B with Project 2

Reference Project 1 in Project 2 By adding Project 1 to Solution Z.
Notice the .csproj file contains relative paths 3 `..` up as so

.csproj
```
    <ProjectReference Include="..\..\..\FolderA\Project1\Project1.csproj">
      <Project>{xxxx}</Project>
      <Name>Project 1</Name>
    </ProjectReference>
```
This all works locally with latest Visual Studio Update of 2017. Everything Builds and runs happily.

Move to Build Server hosted on Azure DevOps using MSBuild version 16.0
This command is used.

```
"C:\sw\ADO_Agents\ADOagent3\_work\9\s\SolutionZ\SolutionZ.sln" /nologo /nr:false /dl:CentralLogger,"C:\sw\ADO_Agents\ADOagent3\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=|SolutionDir=C:\sw\ADO_Agents\ADOagent3\_work\9\s\SolutionZ"*ForwardingLogger,"C:\sw\ADO_Agents\ADOagent3\_work\_tasks\MSBuild_c6c4c611-aa2e-4a33-b606-5eaba2196824\1.151.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"  /p:platform="Mixed Platforms" /p:configuration="Release" /p:_MSDeployUserAgent="VSTS_052eef5e-cfe4-4f59-b65c-b3911f1d5901_build_1381_0"
```

cry to yourself. (may not be needed).
### Expected  behavior
Folder/File paths are maintained, whether relative or not.

### Actual behavior
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 6/3/2019 1:43:36 PM.
Project "C:\sw\ADO_Agents\ADOagent3\_work\9\s\SolutionZ\SolutionZ.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Mixed Platforms".
##[error]C:\sw\ADO_Agents\ADOagent3\_work\9\s\SolutionZ\SolutionZ.sln.metaproj(0,0): Error MSB3202: The project file "C:\sw\ADO_Agents\ADOagent3\_work\9\s\SolutionZ\..\..\FolderA\Project1\Project1.csproj" was not found.
```
### Notice
Folder A and Folder B represent git repository folders.
Notice in the Actual behavior, that MSBuild was looking in SolutionZ for a Project in a folder in a separate repository, even though this works locally in Visual Studio.

**Comment by rainersigwald** [comment] 2019-08-30 15:32
Duplicate of #4348

**Closed by rainersigwald** 2019-08-30 15:32 UTC
