### ISSUE TITLE
Binding redirects are not properly created on first solution load

### ISSUE THREAD

**Issue by sharwell** [Microsoft/msbuild#4239] opened 2019-03-15 16:03 UTC
### Steps to reproduce

1. Check out dotnet/roslyn@222c1082
2. `git clean -dxf`
3. Open **Roslyn.sln** in Visual Studio 2019 RC 2

### Expected  behavior

MSB4018 is not reported.

### Actual behavior

MSB4018 is reported.
![image](https://user-images.githubusercontent.com/1408396/54444990-e431dd00-4711-11e9-8937-1a4afe3b3a0f.png)

**Comment by sharwell** [comment] 2019-03-15 18:41
📝 This is the target that creates the .config file on disk that contains assembly binding redirects. It does not perform other tasks or otherwise influence later parts of the build. Omitting this from the design time build altogether *seems* like a reasonable approach.

**Comment by nguerrera** [comment] 2019-03-15 20:36
I can repro. Investigating

**Comment by sharwell** [comment] 2019-03-15 20:38
@nguerrera My proposed workaround for this is dotnet/roslyn@6e47c6b6.

**Comment by nguerrera** [comment] 2019-03-15 20:54
I'm not sure if GenerateBindingRedirects needs to run in design time builds. I don't think it does, but I would not be surprised to find out that I'm missing something. It looks like it has always run in design time builds.

The reason you started seeing it crash like that seems to be this recent change: dotnet/roslyn@0e07a82509

![image](https://user-images.githubusercontent.com/75470/54461325-801b1300-4729-11e9-946c-05a69e5a2abf.png)

cc @tmat

**Comment by nguerrera** [comment] 2019-03-15 21:00
I think the projects references aren't on disk yet, so their version cannot be determined by RAR.

**Comment by nguerrera** [comment] 2019-03-15 21:01
And the change referenced above assumes `%(ReferencePath.Version)` will never be unset.

**Comment by tmat** [comment] 2019-03-15 21:17
I think we can condition `_SuggestBindingRedirectsForNonFrameworkDependencies` to not run at design time. https://github.com/dotnet/roslyn/commit/0e07a82509#diff-c3034bf853e0647d5ec536b5533bdd6bR12

**Comment by nguerrera** [comment] 2019-03-17 04:08
Closing as @davkean suggested a reason for GenerateBindingRedirects to run in design time builds: app.config is part of output groups.

And the crash was caused by the roslyn change referenced above, which should be amended as Tomas suggest or in some other way that prevents adding SuggestedBindingRedirects with empty MaxVersion.

**Closed by nguerrera** 2019-03-17 04:08 UTC
