### ISSUE TITLE
CoreCompileInputs doesn't include the name of the project in the name, possibly causing clashes

### ISSUE THREAD

**Issue by davkean** [Microsoft/msbuild#1645] opened 2017-02-01 11:07 UTC
Most files that get generated into obj, include the project name to avoid clashes:

```
Debug\ConsoleApp146.AssemblyInfo.cs
Debug\ConsoleApp146.csproj.FileListAbsolute.txt
Debug\ConsoleApp146.csprojResolveAssemblyReference.cache
Debug\ConsoleApp146.dll
Debug\ConsoleApp146.pdb
ConsoleApp146.1.0.0.nuspec
ConsoleApp146.csproj.nuget.g.props
ConsoleApp146.csproj.nuget.g.targets
```

CoreCompileInputs.cache does not:

```
CoreCompileInputs.cache
```

This is going to lead to clashes when projects share intermediates.

**Comment by davkean** [comment] 2017-02-10 04:38
Make note this affects projects that live in the same directory: https://github.com/dotnet/roslyn-project-system/issues/1528.

**Comment by Nazgul07** [comment] 2017-03-02 19:53
I can confirm this issue... I run into build issues because of this. We have a solution with 120+ projects in it and the CoreCompileInputs.cache file not being uniquely named is causing issues.

**Comment by rainersigwald** [comment] 2017-03-06 21:18
Fixed by #1783.

**Closed by rainersigwald** 2017-03-06 21:18 UTC
