### ISSUE TITLE
Task satellite assemblies are not used in .NET Core msbuild

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/msbuild#2203] opened 2017-06-08 19:50 UTC
[task-satellite.zip](https://github.com/Microsoft/msbuild/files/1062207/task-satellite.zip) has the contents of the c:\temp\task-satellite in transcript below.

We expect output of "Bonjour" instead of "Hello" in the final step because the task has a satellite assembly that replaces its neutral "Hello" message with "Bonjour" for CurrentUICulture=fr.

On machine with CurrentUICulture=fr-FR
```
C:\temp\task-satellite>type test.proj
<Project>
  <UsingTask TaskName="SomeTask" AssemblyFile="bin\Debug\netcoreapp1.1\task-satellite.dll" />
  <Target Name="Repro">
    <SomeTask />
  </Target>
</Project>

C:\temp\task-satellite>dir /s /b bin\Debug\netcoreapp1.1
C:\temp\task-satellite\bin\Debug\netcoreapp1.1\fr
C:\temp\task-satellite\bin\Debug\netcoreapp1.1\task-satellite.deps.json
C:\temp\task-satellite\bin\Debug\netcoreapp1.1\task-satellite.dll
C:\temp\task-satellite\bin\Debug\netcoreapp1.1\task-satellite.pdb
C:\temp\task-satellite\bin\Debug\netcoreapp1.1\fr\task-satellite.resources.dll

C:\temp\task-satellite>c:\src\cli\artifacts\win10-x64\stage2\dotnet.exe msbuild test.proj
Microsoft (R) Build Engine version 15.3.378.6360 pour .NET Core
Copyright (C) Microsoft Corporation. Tous droits réservés.

  Hello
```

I haven't debugged, but from quick code inspection, it seems [CoreCLRAssemblyLoader](https://github.com/Microsoft/msbuild/blob/master/src/Shared/CoreCLRAssemblyLoader.cs) doesn't probe for satellites correctly.

@AndyGerlicher @cdmihai This is a blocker for CLI localization. None of the dotnet/sdk messages are showing up localized as a result.  Please triage accordingly.

**Comment by rainersigwald** [comment] 2017-06-19 20:13
Looks like _something_ is searching for satellites, but not in the right place.

```
19:50:50,5475323	dotnet.exe	9860	CreateFile	C:\cli\artifacts\win10-x64\stage2\sdk\2.0.0-preview3-006494\fr-FR\task-satellite.resources.dll	PATH NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Delete, AllocationSize: n/a
19:50:50,5492582	dotnet.exe	9860	CreateFile	C:\task-satellite\bin\Debug\netcoreapp1.1\task-satellite.resources.dll	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
19:50:50,5494314	dotnet.exe	9860	QueryDirectory	C:\task-satellite\bin\Debug\netcoreapp1.1\task-satellite.resources.dll	NO SUCH FILE	Filter: task-satellite.resources.dll
19:50:50,5526298	dotnet.exe	9860	CreateFile	C:\cli\artifacts\win10-x64\stage2\sdk\2.0.0-preview3-006494\fr\task-satellite.resources.dll	NAME NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Delete, AllocationSize: n/a
19:50:50,5555222	dotnet.exe	9860	CreateFile	C:\task-satellite\bin\Debug\netcoreapp1.1\task-satellite.resources.dll	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
19:50:50,5557156	dotnet.exe	9860	QueryDirectory	C:\task-satellite\bin\Debug\netcoreapp1.1\task-satellite.resources.dll	NO SUCH FILE	Filter: task-satellite.resources.dll
```

Debugging.

**Comment by rainersigwald** [comment] 2017-06-19 23:02
Ok, I can confirm that if `CoreCLRAssemblyLoader` is forced to attempt to load the assembly from its explicit path, it works. Now I just need to figure out how to
* determine that we're trying to load a localized assembly (`assemblyName.CultureInfo` but that's not available in our current netstandard target so I'll have to reflect it out)
* do the right language fallback (is it correct to just do `CultureInfo.Parent` repeatedly as folders?)

**Comment by nguerrera** [comment] 2017-06-19 23:05
> assemblyName.CultureInfo but that's not available in our current netstandard target so I'll have to reflect it out)

AssemblyName.CultureName should be there.

> do the right language fallback (is it correct to just do CultureInfo.Parent repeatedly as folders?)

The resource manager should handle this and try to load up the parent chain. I would think if you're getting a culture name, you just have to fail the load and you'll be called again with the parent culture.

**Comment by rainersigwald** [comment] 2017-06-20 16:37
Thanks @nguerrera, everything seems to be working fine.

I caused many problems for myself by copying MSBuild and Roslyn assemblies to the wrong folder--at first, I was _very_ confused about why my private CLI wasn't loading Roslyn--that's because it was looking in the wrong path, and then because I had overwritten the Roslyn task assembly with an old one that didn't understand all the new parameters. After resolving those things, I can build your task assembly and use it:

```
C:\task-satellite>C:\cli\artifacts\win10-x64\stage2\dotnet.exe msbuild test.proj
Microsoft (R) Build Engine version 15.3.0.0 pour .NET Core
Copyright (C) Microsoft Corporation. Tous droits réservés.

  Bonjour
```

PR to come shortly.

**Closed** 2017-06-21 22:20 UTC
Labels: .NET Core, Localization
