### ISSUE TITLE
Using $(SolutionDir) causes problems with msbuild

### ISSUE THREAD

**Issue by datalurkur** [Microsoft/msbuild#2784] opened 2017-12-07 22:34 UTC
My project attempts to import a .targets file from a directory higher than the solution directory.  The import looks like so: `<Import Project="$(SolutionDir)..\foo\bar.targets" />`

This results in a build-time error when using msbuild to restore nuget packages via command line:

C:\SolutionDirRepro\SolutionDirRepro.csproj(139,3): error MSB4019: The imported project "C:\SolutionDirRepro\*Undefined*..\foo\test.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

If I move the .targets file to the directory the solution resides in, this problem goes away.

**Comment by cdmihai** [comment] 2017-12-08 22:44
Closed as duplicate of https://github.com/Microsoft/msbuild/issues/2743

**Closed by cdmihai** 2017-12-08 22:44 UTC
