### ISSUE TITLE
GenerateTargetFrameworkMonikerAttribute warns about access issues in parallel builds

### ISSUE THREAD

**Issue by natemcmaster** [Microsoft/msbuild#1882] opened 2017-03-17 17:34 UTC
When build a solution in parallel, the  GenerateTargetFrameworkMonikerAttribute target sometimes produces this warning:

> C:\dev\dotnet\sdk\2.0.0-preview1-005418\Microsoft.Common.CurrentVersion.targets(3140,5): warning MSB3491: Could not write lines to file "C:\Users\namc\AppData\Local\Temp\.NETCoreApp,Version=v1.0.AssemblyAttributes.cs". The process cannot access the file 'C:\Users\namc\AppData\Local\Temp\.NETCoreApp,Version=v1.0.AssemblyAttributes.cs' because it is being used by another process. [C:\dev\DotNetTools\src\Microsoft.DotNet.Watcher.Tools\Microsoft.DotNet.Watcher.Tools.csproj]

May be resolved by #1479 or https://github.com/dotnet/sdk/issues/842

cc @jeffkl

**Comment by AndyGerlicher** [comment] 2017-03-17 17:50
Dupe of #1479

**Closed by AndyGerlicher** 2017-03-17 17:50 UTC
