### ISSUE TITLE
Directory.Build.targets is not imported for multi-targeting projects where TargetFramework is not defined

### ISSUE THREAD

**Issue by AArnott** [Microsoft/msbuild#1991] opened 2017-04-19 01:07 UTC
When a "Microsoft.NET.Sdk" project defines a `TargetFrameworks` property instead of a `TargetFramework` property (effectively activating the multi-targeting behavior), it no longer imports `Directory.Build.targets` in the top-level evaluation.

When a `TargetFramework` is set, it imports *both* Directory.Build.props and Directory.Build.targets. 
But when only `TargetFrameworks` is defined, it only imports `Directory.Build.props`.

This distinction is very subtle and unexpected. It took me quite some time to diagnose a build issue before I figured this out. I trust this was an unintentional oversight that can be fixed.

Repro project:
[dirprops.zip](https://github.com/Microsoft/msbuild/files/931464/dirprops.zip)

When building the `Restore` target, I see this:

```
msbuild /t:restore
  Restoring packages for C:\temp\dirprops\lib\lib.csproj...
  Lock file has not changed. Skipping lock file write. Path: C:\temp\dirprops\lib\obj\project.assets.json
  Restore completed in 378.45 ms for C:\temp\dirprops\lib\lib.csproj.

  NuGet Config files used:
      C:\Users\andarno\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  AddInProps is executing...
```

But when I define `TargetFramework` I see both targets executing:

```
msbuild /t:restore /p:targetframework=netstandard1.3
  Restoring packages for C:\temp\dirprops\lib\lib.csproj...
  Generating MSBuild file C:\temp\dirprops\lib\obj\lib.csproj.nuget.g.props.
  Generating MSBuild file C:\temp\dirprops\lib\obj\lib.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\temp\dirprops\lib\obj\project.assets.json
  Restore completed in 764.25 ms for C:\temp\dirprops\lib\lib.csproj.

  NuGet Config files used:
      C:\Users\andarno\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  AddInProps is executing...
  AddInTargets is executing...
```

**Comment by rainersigwald** [comment] 2017-04-19 15:55
Duplicate of #1721, fixed for the 15.3 release.

**Closed by rainersigwald** 2017-04-19 15:55 UTC
