### ISSUE TITLE
AssemblyInfo.cs how to generate with BOM?

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/msbuild#1912] opened 2017-03-25 19:29 UTC
_From @Looooopy on March 14, 2017 15:29_

Is it possible to generate a AssemblyInfo.cs with BOM?

I have stylecop analyzers that complain on the generated AssemblyInfo.cs and do not want to turn it of.
For now i have set it to down from error to a warning so i can compile the project.

_Copied from original issue: dotnet/sdk#989_

**Comment by livarcocc** [comment] 2017-03-25 19:29
_From @codito on March 24, 2017 8:18_

In VS, the generated assemblyinfo has this header, static analysis tools skip it because of this header. Can such a header added in CLI build as well?

```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```

**Comment by livarcocc** [comment] 2017-03-25 19:29
_From @dasMulli on March 24, 2017 8:26_

Suggest moving this to MSBuild where the responsible Task comes from
(https://github.com/Microsoft/msbuild/blob/xplat/src/Tasks/WriteCodeFragment.cs)

**Comment by rainersigwald** [comment] 2017-06-13 21:04
Closing as a duplicate of #1925 since that has an outstanding PR. Please comment if you think that being able to specify a BOM is critical and it's not sufficient to add the `<auto-generated>` tag and we can reconsider this.

**Closed by rainersigwald** 2017-06-13 21:04 UTC
