### ISSUE TITLE
FindRibbons task fails when including a .NET Standard 2.0 package

### ISSUE THREAD

**Issue by PatrickHofman** [microsoft/msbuild#2475] opened 2017-08-25 12:23 UTC
I am developing an Office add-in which is based on some packages that were recently moved to .NET Standard 2.0.

For one specific add-in I am experiencing an issue with the MSBuild task FindRibbons, included in Visual Studio Tools for Office.

When I compile, I get this error:

> The "FindRibbons" task failed unexpectedly.
> System.IO.FileNotFoundException: Could not load file or assembly 'MyAssembly, Version=2017.8.17229.1332, Culture=neutral, PublicKeyToken=15f3938228f8c5ae' or one of its dependencies. The system cannot find the file specified.
> File name: 'MyAssembly, Version=2017.8.17229.1332, Culture=neutral, PublicKeyToken=15f3938228f8c5ae'
> Server stack trace: 
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
>    at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
>    at System.Reflection.Assembly.Load(String assemblyString)
>    at System.UnitySerializationHolder.GetRealObject(StreamingContext context)
>    at System.Runtime.Serialization.ObjectManager.ResolveObjectReference(ObjectHolder holder)
>    at System.Runtime.Serialization.ObjectManager.DoFixups()
>    at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
>    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
>    at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObject(MemoryStream stm)
>    at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.FixupForNewAppDomain()
>    at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
>    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
>    at Microsoft.Build.Framework.ITask.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
> Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
> Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe
> --- A detailed error log follows. 
> === Pre-bind state information ===
> LOG: DisplayName = MyAssembly, Version=2017.8.17229.1332, Culture=neutral, PublicKeyToken=15f3938228f8c5ae
>  (Fully-specified)
> LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/
> LOG: Initial PrivatePath = NULL
> Calling assembly : (Unknown).
> LOG: This bind starts in default load context.
> LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe.Config
> LOG: Using host configuration file: 
> LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
> LOG: Post-policy reference: MyAssembly, Version=2017.8.17229.1332, Culture=neutral, PublicKeyToken=15f3938228f8c5ae
> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MyAssembly.DLL.
> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MyAssembly/MyAssembly.DLL.
> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MyAssembly.EXE.
> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MyAssembly/MyAssembly.EXE.
> 

Investigating the issue brought me to calling `FindRibbons` from a console app so I could diagnose the issue.

An exception is thrown on `types = assembly.GetTypes()` in the `FindRibbons` class from `Microsoft.VisualStudio.Tools.Office.BuildTasks.dll` in the MSBuild folder `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\OfficeTools`:

> System.Reflection.ReflectionTypeLoadException:
> LoaderExceptions[0]: {"Could not load file or assembly 'System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"}

And indeed, that file **with that version** doesn't exist. The `app.config` contains binding redirects though to version 4.0.2.0, which does exist in the same folder as the inspected assembly:

```
<dependentAssembly>
  <assemblyIdentity name="System.ValueTuple" publicKeyToken="CC7B13FFCD2DDD51" culture="neutral"/>
  <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0"/>
</dependentAssembly>
```

It seems the MSBuild task doesn't take the assembly binding redirects on the file in consideration. When I skip the `FindRibbons` task and pass in the correct values for the `RibbonTypesCollection` variable the vsto file gets generated correctly and the add-in runs as expected.

If I try to adjust the `FindRibbons` code to force loading the correct assembly from the `CurrentDomain_ReflectionOnlyAssemblyResolve`, I get the same exception when calling the method from my test app.

(The code I have used to try to fix this in `CurrentDomain_ReflectionOnlyAssemblyResolve`, which didn't work:)

```
catch (FileLoadException)
{
    this.InitializeMap();

    string assemblyName = args.Name.Split(',').First() + ",";

    string str = this._assemblyFullNameToPathMap.Where(a => a.Key.StartsWith(assemblyName)).Select(k => k.Value).SingleOrDefault();

    if (!string.IsNullOrEmpty(str))
    {
        return Assembly.ReflectionOnlyLoadFrom(str);
    }

    return Assembly.ReflectionOnlyLoad(AppDomain.CurrentDomain.ApplyPolicy(args.Name));
}
```

I think this is the same issue as mentioned here: https://github.com/Microsoft/msbuild/issues/1309, but I am not sure. Also, this seems to become a bigger problem since there is no way out for developers forced to use .NET Standard 2.0 for interoperability reasons.

Is there anything we can do to fix this? Is this something for the MSBuild team or the Office team?

**Comment by PatrickHofman** [comment] 2017-08-25 13:23
I have found a way to circumvent this issue. I just made a custom build of `Microsoft.VisualStudio.Tools.Office.BuildTasks` with only the `Microsoft.VisualStudio.Tools.Office.BuildTasks.FindRibbons` class inside.

This is the code for the `PathReflectionOnlyAssemblyResolver` class which is an inner class of `FindRibbons`:

```
private class PathReflectionOnlyAssemblyResolver
{
    private IDictionary<string, string> _assemblyFullNameToPathMap = new Dictionary<string, string>();
    //
    // BEGIN ADJUSTMENTS
    //
    private IDictionary<string, string> _assemblyNameToPathMap = new Dictionary<string, string>();
    //
    // END ADJUSTMENTS
    //

    private bool _mapInitialized;
    private readonly string _path;

    public PathReflectionOnlyAssemblyResolver(string path)
    {
        if (string.IsNullOrEmpty(path))
        {
            throw new ArgumentNullException(path);
        }
        this._path = path;
    }

    public Assembly CurrentDomain_ReflectionOnlyAssemblyResolve(object sender, ResolveEventArgs args)
    {
        //
        // BEGIN ADJUSTMENTS
        //
        string assemblyName1 = args.Name.Split(',')[0];

        this.InitializeMap();

        if (this._assemblyNameToPathMap.TryGetValue(assemblyName1, out string str1))
        {
            return Assembly.ReflectionOnlyLoadFrom(str1);
        }
        //
        // END ADJUSTMENTS
        //

        try
        {
            return Assembly.ReflectionOnlyLoad(args.Name);
        }
        catch (FileNotFoundException)
        {
            string str;
            this.InitializeMap();
            if (this._assemblyFullNameToPathMap.TryGetValue(args.Name, out str))
            {
                return Assembly.ReflectionOnlyLoadFrom(str);
            }
            return Assembly.ReflectionOnlyLoad(AppDomain.CurrentDomain.ApplyPolicy(args.Name));
        }
    }

    private void InitializeMap()
    {
        if (!this._mapInitialized)
        {
            this._mapInitialized = true;
            foreach (string str in Directory.GetFiles(this._path, "*.dll"))
            {
                try
                {
                    string fullName = System.Reflection.AssemblyName.GetAssemblyName(str).FullName;
                    this._assemblyFullNameToPathMap.Add(fullName, str);

                    //
                    // BEGIN ADJUSTMENTS
                    //
                    string name = System.Reflection.AssemblyName.GetAssemblyName(str).Name;
                    this._assemblyNameToPathMap.Add(name, str);
                    //
                    // END ADJUSTMENTS
                    //
                }
                catch (Exception)
                {
                }
            }
        }
    }
}
```

I understand that particularly the first lines in `CurrentDomain_ReflectionOnlyAssemblyResolve` are problematic, since they could cause a local scoped assembly to overrule the GAC for example, but that isn't an issue in my situation right now.

- Build that file and name it `Fix.Microsoft.VisualStudio.Tools.Office.BuildTasks.dll`.

- Copy the output file to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\OfficeTools`.

- Open `Microsoft.VisualStudio.Tools.Office.targets` and change `<UsingTask TaskName="FindRibbons" AssemblyFile="Microsoft.VisualStudio.Tools.Office.BuildTasks.dll" />` to `<UsingTask TaskName="FindRibbons" AssemblyFile="Fix.Microsoft.VisualStudio.Tools.Office.BuildTasks.dll" />`.

- Now compile your project again.

- Profit!

**Comment by martinhills2000** [comment] 2017-09-12 12:23
Hi Patrick,

Very helpful article as I am having the exact same issue. One thing I would be really grateful if you could tell me - where do I get the source code for microsoft.VisualStudio.Tools.Office.BuildTasks so that I can modify it and create a fix version?

Many thanks,

Martin

**Comment by mxvlshn** [comment] 2018-02-21 10:38
HI, could you please explain how to run findribbons from the console app?

**Comment by PatrickHofman** [comment] 2018-02-21 10:40
@martinhills2000 You have to disassemble the assembly. Reflector would do.

**Comment by PatrickHofman** [comment] 2018-02-21 10:41
@mxvlshn Not sure what you mean. You shouldn't run that from a console app.

**Comment by Kazpers** [comment] 2018-03-28 10:12
Not much I can add to this report, but I can confirm the issue. Adding any .NET Standard NuGet to my Office VSTO plug-in causes this exact error.

Having a redirect in app.config does not help (and actually has to do with a separate issue where VSTO plug-ins ignore app.config binding redirects - presumably because they run inside the Outlook process?).

Nor does it help to set <AutoGenerateBindingRedirects> due to #1310

**Comment by rainersigwald** [comment] 2020-05-27 16:24
Team triage: closing due to age. If you're still seeing this problem, please let us know and we can reactivate it.

**Closed by rainersigwald** 2020-05-27 16:24 UTC

**Comment by ds-evo** [comment] 2021-04-13 13:36
Thank you for the workaround
