### ISSUE TITLE
On Linux msbuild generates error about missing api-ms-win-core-registry-l1-1-0.dll

### ISSUE THREAD

**Issue by JohnChen0** [Microsoft/msbuild#423] opened 2016-01-09 00:36 UTC
While running msbuild on Linux, I received the following error:

    Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-registry-l1-1-0.dll': The specified module could not be found.
     (Exception from HRESULT: 0x8007007E)
       at Interop.mincore.RegCloseKey(IntPtr hKey)
       at Microsoft.Win32.SafeHandles.SafeRegistryHandle.ReleaseHandle()
       at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
       at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
       at System.Runtime.InteropServices.SafeHandle.Finalize()

The error occurred during clean up, after msbuild had already finished its work. Apparently it was trying to do RegCloseKey(HKEY_PERFORMANCE_DATA).

**Comment by gkhanna79** [comment] 2016-01-11 19:17
What is the ETA for this fix? This is blocking https://github.com/dotnet/coreclr/issues/1934#issuecomment-170444117

CC @weshaggard @joshfree

**Comment by rainersigwald** [comment] 2016-01-11 23:52
I'm taking a look at this now.

**Comment by rainersigwald** [comment] 2016-01-12 01:36
I suspect that this is because the feature flag for registry access is set to true when building for Windows [here](https://github.com/Microsoft/msbuild/blob/54c137f24422481e6ecbfc8c8f857cafb09b488b/dir.props#L287-L289), when it should be disabled for all CoreCLR scenarios.

That doesn't explain why the crash only happens at `RegCloseKey` time, though--AFAICT, this key gets opened for any registry query, but I don't see how the handle could have been constructed successfully.

I'm trying to disable registry use entirely for our coreclr flavor.

**Comment by JohnChen0** [comment] 2016-01-12 08:36
For this particular crash, the registry handle that is being closed is a pseudo handle, HKEY_PERFORMANCE_DATA, so there is no corresponding open operation.

**Comment by joperezr** [comment] 2016-01-15 01:44
@rainersigwald were we able to fix this? This is also blocking building corefx using netcore msbuild which we intended to have for tomorrow

**Comment by rainersigwald** [comment] 2016-01-15 16:44
I've reproduced the issue and am building and will test with what I hope is a fix. If this doesn't work I'll have to spend some more time poking at it (and may have to bug someone for help debugging).

**Comment by rainersigwald** [comment] 2016-01-19 23:01
This should be fixed in our packages `v0.1.0-preview-00008` and higher. Let me know if you see otherwise.

**Closed by rainersigwald** 2016-01-19 23:01 UTC

**Comment by JohnChen0** [comment] 2016-01-20 00:33
The fix is verified.
